### ISSUE TITLE
Client crashes soon after start

### ISSUE THREAD

**Issue by PurpleAzurite** [hydrusnetwork/hydrus#1027]
### Hydrus version

465

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Installed from AUR on 5.15.7-arch1-1

### Bug description and reproduction

The client crashes moments after launching. The issue persists whether trying to reload exit session or starting a new search, though in the case of the latter, it crashes once searching has commenced.

### Log output

```text
2021/12/15 10:33:53: hydrus client started
2021/12/15 10:33:54: booting controller…
2021/12/15 10:33:54: booting db…
2021/12/15 10:33:54: checking database
2021/12/15 10:33:54: preparing db caches
2021/12/15 10:33:54: initialising managers
2021/12/15 10:33:54: booting gui…
2021/12/15 10:33:54: A window with frame key "regular_center_dialog" that wanted to display at "PyQt5.QtCore.QPoint(-1445, 293)" was rescued from apparent off-screen to the new location at "PyQt5.QtCore.QPoint(10, 10)".
2021/12/15 10:33:57: Exception:
2021/12/15 10:33:57: TypeError
arguments did not match any overloaded call:
Traceback (most recent call last):
  File "/opt/hydrus/hydrus/core/HydrusPubSub.py", line 138, in Process
    callable( *args, **kwargs )
  File "/opt/hydrus/hydrus/client/gui/pages/ClientGUIResults.py", line 4517, in WaterfallThumbnails
    self._FadeThumbnails( thumbnails )
  File "/opt/hydrus/hydrus/client/gui/pages/ClientGUIResults.py", line 2540, in _FadeThumbnails
    bmp = thumbnail.GetQtImage()
  File "/opt/hydrus/hydrus/client/gui/pages/ClientGUIResults.py", line 4829, in GetQtImage
    raw_thumbnail_qt_image = thumbnail_hydrus_bmp.GetQtImage()
  File "/opt/hydrus/hydrus/client/ClientRendering.py", line 1001, in GetQtImage
    return HG.client_controller.bitmap_manager.GetQtImageFromBuffer( width, height, self._depth * 8, self._GetData() )
  File "/opt/hydrus/hydrus/client/ClientManagers.py", line 183, in GetQtImageFromBuffer
    qt_image = QG.QImage( data, width, height, bytes_per_line, qt_image_format )
TypeError: arguments did not match any overloaded call:
  QImage(): too many arguments
  QImage(QSize, QImage.Format): argument 1 has unexpected type 'bytes'
  QImage(int, int, QImage.Format): argument 1 has unexpected type 'bytes'
  QImage(bytes, int, int, QImage.Format): argument 4 has unexpected type 'float'
  QImage(PyQt5.sip.voidptr, int, int, QImage.Format): argument 4 has unexpected type 'float'
  QImage(bytes, int, int, int, QImage.Format): argument 4 has unexpected type 'float'
  QImage(PyQt5.sip.voidptr, int, int, int, QImage.Format): argument 4 has unexpected type 'float'
  QImage(List[str]): argument 1 has unexpected type 'bytes'
  QImage(str, format: str = None): argument 1 has unexpected type 'bytes'
  QImage(QImage): argument 1 has unexpected type 'bytes'
  QImage(Any): too many arguments

  QImage(): too many arguments
  QImage(QSize, QImage.Format): argument 1 has unexpected type 'bytes'
  QImage(int, int, QImage.Format): argument 1 has unexpected type 'bytes'
  QImage(bytes, int, int, QImage.Format): argument 4 has unexpected type 'float'
  QImage(PyQt5.sip.voidptr, int, int, QImage.Format): argument 4 has unexpected type 'float'
  QImage(bytes, int, int, int, QImage.Format): argument 4 has unexpected type 'float'
  QImage(PyQt5.sip.voidptr, int, int, int, QImage.Format): argument 4 has unexpected type 'float'
  QImage(List[str]): argument 1 has unexpected type 'bytes'
  QImage(str, format: str = None): argument 1 has unexpected type 'bytes'
  QImage(QImage): argument 1 has unexpected type 'bytes'
  QImage(Any): too many arguments
```

**Comment by PurpleAzurite** [comment]
amend: occurs on both window manager and full DE

**Comment by bbappserver** [comment]
It appears that whatever version of PyQt your distribution is built against is incorrectly invoking the C-API 
`QImage(bytes, int, int, int, QImage.Format): argument 4 has unexpected type 'float'`

Depending how it was built this may be correctable with
`sudo pip install --upgrade PyQt`

**Comment by PurpleAzurite** [comment]
I will inform the package maintainer

**Comment by hydrusnetwork** [comment]
Thank you for this report. I just saw this somewhere else as well. I don't know the details of the Arch package of python 3.10 or whatever the specifics are on why this type is being checked so strictly, but I think I have this fixed for today's release. I am basically being lazy about sending 3.0 when I should be sending 3. There's another float/int error related to saving a window's coordinates that I have fixed.

If the other end of this is not easily fixable, please let me know how 466 works for you. There may be some other bad lines like this and I'd like to fix them as well.
