### ISSUE TITLE
Filtering by viewcount throws exception

### ISSUE THREAD

**Issue by Trivernis** [hydrusnetwork/hydrus#1090]
### Hydrus version

474

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Distro: Arch
Kernel: 5.16.10-zen1-1-zen
Installed from AUR

### Bug description and reproduction

From the UI:
1. open the client
2. filter by system:all views < 10
3. loading never finishes

Via Client API:
1. open a client and enable the client API
2. Perform a GET-Request to `/get_files/search_files?tags=%5B%22system%3Aall%20views%20%3C%201000%22%5D`
3. you get an error response with the exception description

### Log output

```text
The repository encountered an error it could not handle! Here is a dump of what happened, which will also be written to your client.log file. If it persists, please forward it to hydrus.admin@gmail.com:

Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.10/site-packages/twisted/_threads/_threadworker.py", line 47, in work
    task()
  File "/usr/lib/python3.10/site-packages/twisted/_threads/_team.py", line 181, in doWork
    task()
--- <exception caught here> ---
  File "/usr/lib/python3.10/site-packages/twisted/python/threadpool.py", line 238, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/lib/python3.10/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/usr/lib/python3.10/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.10/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/opt/hydrus/hydrus/client/networking/ClientLocalServerResources.py", line 1936, in _threadDoGETJob
    hash_ids = HG.client_controller.Read( 'file_query_ids', file_search_context, sort_by = sort_by, apply_implicit_limit = False )
  File "/opt/hydrus/hydrus/core/HydrusController.py", line 684, in Read
    return self._Read( action, *args, **kwargs )
  File "/opt/hydrus/hydrus/core/HydrusController.py", line 200, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 922, in Read
    return job.GetResult()
  File "/opt/hydrus/hydrus/core/HydrusData.py", line 2041, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: OperationalError: misuse of aggregate: SUM()
Database Traceback (most recent call last):
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 605, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 10051, in _Read
    elif action == 'file_query_ids': result = self._GetHashIdsFromQuery( *args, **kwargs )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 5637, in _GetHashIdsFromQuery
    nonzero_hash_ids = self._GetHashIdsFromFileViewingStatistics( view_type, viewing_locations, '>', 0 )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 4535, in _GetHashIdsFromFileViewingStatistics
    hash_ids = self._STS( self._Execute( select_statement ) )
  File "/opt/hydrus/hydrus/core/HydrusDBBase.py", line 219, in _Execute
    return self._c.execute( query, *args )
sqlite3.OperationalError: misuse of aggregate: SUM()
```

**Comment by Trivernis** [comment]
Probably related to #1089

**Comment by hydrusnetwork** [comment]
Thank you for this report. This is fixed for this week's v475. Please let me know if you have any more trouble. As you expected, it was the same problem as #1089
