### ISSUE TITLE
[Issue] Another DB error, this time triggered by trying to manually saving a session. And automatically saving a session.

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#115]
```
`Database Error!
'utf8' codec can't decode byte 0xe7 in position 1209: invalid continuation byte
Unknown Caller, probably GUI.
Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusDB", line 200, in _ProcessJob
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientDB", line 6755, in _Write
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientDB", line 5078, in _SetJSONDump
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\json", line 243, in dumps
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\json.encoder", line 207, in encode
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\json.encoder", line 270, in iterencode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe7 in position 1209: invalid continuation byte
```
I'm pretty freaking sure this is why #102 has been happening to me. I thought it was something broken with the auto-save session at first and now it has become another undecodable byte thing.

I have no idea why and by what these are being triggered and apparently, only with me but @hydrusnetwork also seems to not have any interest in it. Maybe because I use PT-BR Windows 10? 
But then why it only starts after hours that Hydrus has been running?

There's been a long fucking time since I was able to start Hydrus without an open page downloading anything so I dunno if it's because I have queues in the dozens of thousands.

Now knowing my sessions aren't being saved anymore, I'm also not able to even shutdown my PC, because Hydrus will just lose 20K worth of links. Again.

**Comment by hydrusnetwork** [comment]
I am sorry for the slow reply here. I am catching up on my github queue now. Again, this is related to #101 , so I will close this to consolidate the discussion.
