### ISSUE TITLE
Failed to execute script: 'pyi_rth_multiprocessing'

### ISSUE THREAD

**Issue by Ariskapp9** [hydrusnetwork/hydrus#1174]
### Hydrus version

v488

### Operating system

Windows other (specify in comments)

### Install method

Installer

### Install and OS comments

Windows 7 Ultimate, Service Pack 1, 64bit Operating System.

### Bug description and reproduction

1. Launch client.exe
2. Error log shows
![client_Clwl11ZX16](https://user-images.githubusercontent.com/29080475/173565848-773b6fe7-ba8a-402f-826e-3e6711b7866f.png)
 

### Log output

```text
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_multiprocessing.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: The parameter is incorrect.
```

**Comment by floogulinc** [comment]
Do you happen to be using 32 bit Windows?

**Comment by floogulinc** [comment]
It appears PyInstaller has dropped support for Windows 7 (which has been unsupported for over a year) and there are not starting to be some things broken. See https://github.com/pyinstaller/pyinstaller/issues/4855

I suggest you either try [running from source](https://hydrusnetwork.github.io/hydrus/running_from_source.html) or update to a supported operating system.

**Comment by floogulinc** [comment]
Oh also apparently according to https://github.com/pyinstaller/pyinstaller/issues/4855 there may be some updates to Windows 7 that fix the issue. Please make sure your OS is updated.

**Comment by Ariskapp9** [comment]
> Oh also apparently according to [pyinstaller/pyinstaller#4855](https://github.com/pyinstaller/pyinstaller/issues/4855) there may be some updates to Windows 7 that fix the issue. Please make sure your OS is updated. Specifically [KB3126587](https://www.catalog.update.microsoft.com/Search.aspx?q=KB3126587%20windows%207).

Yeah figured it'd be something to do with outdated windows, this did the trick though.
