### ISSUE TITLE
test_duplicates test has occasional failures

### ISSUE THREAD

**Issue by RunningDroid** [hydrusnetwork/hydrus#1217]
### Hydrus version

497

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

I'm running [Void Linux](https://voidlinux.org/) & I get hydrus from a template I've been working on : https://github.com/RunningDroid/void-packages/blob/add-hydrus-and-dependencies/srcpkgs/hydrus/template
(edit:replaced with a more stable link)

### Bug description and reproduction

1. run `python3 test.py`
2. don't change anything
3. run `python3 test.py` again
4. repeat until test_duplicates fails

It seems to be more likely to fail in the latest release.

### Log output

```text
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-runningdroid'
test_dialog_manage_subs (hydrus.test.TestDialogs.TestDBDialogs) ... ok
test_dialog_choose_new_service_method (hydrus.test.TestDialogs.TestNonDBDialogs) ... ok
test_listbox_colour_options (hydrus.test.TestClientListBoxes.TestListBoxes) ... This plugin does not support propagateSizeHints()
ok
test_client_api (hydrus.test.TestClientAPI.TestClientAPI) ... ok
test_import_folders_daemon (hydrus.test.TestClientDaemons.TestDaemons) ... ok
test_services (hydrus.test.TestClientConstants.TestManagers) ... ok
test_undo (hydrus.test.TestClientConstants.TestManagers) ... ok
test_checker_options (hydrus.test.TestClientImportOptions.TestCheckerOptions) ... ok
test_file_import_options (hydrus.test.TestClientImportOptions.TestFileImportOptions) ... ok
test_basics (hydrus.test.TestClientImportOptions.TestNoteImportOptions) ... ok
test_presentation_import_options (hydrus.test.TestClientImportOptions.TestPresentationImportOptions) ... ok
test_additional (hydrus.test.TestClientImportOptions.TestServiceTagImportOptions) ... ok
test_application (hydrus.test.TestClientImportOptions.TestServiceTagImportOptions) ... ok
test_basics (hydrus.test.TestClientImportOptions.TestServiceTagImportOptions) ... ok
test_existing (hydrus.test.TestClientImportOptions.TestServiceTagImportOptions) ... ok
test_get_tags_filtering (hydrus.test.TestClientImportOptions.TestServiceTagImportOptions) ... ok
test_overwrite_deleted_additional (hydrus.test.TestClientImportOptions.TestServiceTagImportOptions) ... ok
test_overwrite_deleted_get_tags_filtering (hydrus.test.TestClientImportOptions.TestServiceTagImportOptions) ... ok
test_basics (hydrus.test.TestClientImportOptions.TestTagImportOptions) ... ok
test_blacklist (hydrus.test.TestClientImportOptions.TestTagImportOptions) ... ok
test_external_tags (hydrus.test.TestClientImportOptions.TestTagImportOptions) ... ok
test_overwrite_deleted_additional (hydrus.test.TestClientImportOptions.TestTagImportOptions) ... ok
test_overwrite_deleted_filterable (hydrus.test.TestClientImportOptions.TestTagImportOptions) ... ok
test_services (hydrus.test.TestClientImportOptions.TestTagImportOptions) ... ok
test_whitelist (hydrus.test.TestClientImportOptions.TestTagImportOptions) ... ok
test_basics (hydrus.test.TestClientParsing.TestStringConverter) ... ok
test_compound (hydrus.test.TestClientParsing.TestStringConverter) ... ok
test_basics (hydrus.test.TestClientParsing.TestStringMatch) ... ok
test_basics (hydrus.test.TestClientParsing.TestStringProcessor) ... ok
test_basics (hydrus.test.TestClientParsing.TestStringSlicer) ... ok
test_basics (hydrus.test.TestClientParsing.TestStringSorter) ... ok
test_basics (hydrus.test.TestClientParsing.TestStringSplitter) ... ok
test_merge (hydrus.test.TestClientTags.TestMergeTagsManagers) ... ok
test_tag_filtering (hydrus.test.TestClientTags.TestTagDisplayManager) ... ok
test_parsed_autocomplete_text (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_counts (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_results_cache_fetch_all_madness (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_results_cache_full_normal (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_results_cache_init (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_results_cache_namespace_bare_fetch_all (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_results_cache_namespace_explicit_fetch_all (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_results_cache_namespaces_into_full_tags (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_results_cache_subtag_exact (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_results_cache_subtag_normal (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_results_cache_system (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_predicate_strings_and_namespaces (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_system_predicate_parsing (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_tag_import_options_simple (hydrus.test.TestClientTags.TestTagObjects) ... ok
test_delete_pending (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_get_current (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_get_deleted (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_get_namespace_slice (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_get_num_tags (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_get_pending (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_get_petitioned (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_get_service_keys_to_statuses_to_tags (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_get_statuses_to_tags (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_has_tag (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_process_content_update (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_reset_service (hydrus.test.TestClientTags.TestTagsManager) ... ok
test_competing_write (hydrus.test.TestClientThreading.TestFileRWLock) ... ok
test_mixed_competing (hydrus.test.TestClientThreading.TestFileRWLock) ... ok
test_shared_read (hydrus.test.TestClientThreading.TestFileRWLock) ... ok
test_simple (hydrus.test.TestClientThreading.TestFileRWLock) ... ok
test_dict_to_content_updates (hydrus.test.TestFunctions.TestFunctions) ... ok
test_number_conversion (hydrus.test.TestFunctions.TestFunctions) ... ok
test_SERIALISABLE_TYPE_APPLICATION_COMMAND (hydrus.test.TestHydrusSerialisable.TestSerialisables) ... ok
test_SERIALISABLE_TYPE_DUPLICATE_ACTION_OPTIONS (hydrus.test.TestHydrusSerialisable.TestSerialisables) ... ok
test_SERIALISABLE_TYPE_SHORTCUT (hydrus.test.TestHydrusSerialisable.TestSerialisables) ... ok
test_SERIALISABLE_TYPE_SHORTCUT_SET (hydrus.test.TestHydrusSerialisable.TestSerialisables) ... ok
test_SERIALISABLE_TYPE_SUBSCRIPTION (hydrus.test.TestHydrusSerialisable.TestSerialisables) ... ok
test_SERIALISABLE_TYPE_TAG_FILTER (hydrus.test.TestHydrusSerialisable.TestSerialisables) ... ok
test_basics (hydrus.test.TestHydrusSerialisable.TestSerialisables) ... ok
test_server (hydrus.test.TestHydrusSessions.TestSessions) ... ok
test_autocomplete (hydrus.test.TestClientDB.TestClientDB) ... ok
test_export_folders (hydrus.test.TestClientDB.TestClientDB) ... ok
test_file_query_ids (hydrus.test.TestClientDB.TestClientDB) ... ok
test_file_system_predicates (hydrus.test.TestClientDB.TestClientDB) ... ok
test_file_updates (hydrus.test.TestClientDB.TestClientDB) ... ok
test_filter_existing_tags (hydrus.test.TestClientDB.TestClientDB) ... ok
test_gui_sessions (hydrus.test.TestClientDB.TestClientDB) ... ok
test_hash_status (hydrus.test.TestClientDB.TestClientDB) ... ok
test_import (hydrus.test.TestClientDB.TestClientDB) ... ok
test_import_folders (hydrus.test.TestClientDB.TestClientDB) ... ok
test_init (hydrus.test.TestClientDB.TestClientDB) ... ok
test_media_results (hydrus.test.TestClientDB.TestClientDB) ... ok
test_nums_pending (hydrus.test.TestClientDB.TestClientDB) ... ok
test_pending (hydrus.test.TestClientDB.TestClientDB) ... ok
test_pixiv_account (hydrus.test.TestClientDB.TestClientDB) ... ok
test_services (hydrus.test.TestClientDB.TestClientDB) ... ok
test_shortcuts (hydrus.test.TestClientDB.TestClientDB) ... ok
test_server (hydrus.test.TestServerDB.TestServerDB) ... ok
test_duplicates (hydrus.test.TestClientDBDuplicates.TestClientDBDuplicates) ... FAIL

======================================================================
FAIL: test_duplicates (hydrus.test.TestClientDBDuplicates.TestClientDBDuplicates)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/hydrus-497/hydrus/test/TestClientDBDuplicates.py", line 1056, in test_duplicates
    self._test_poach_better()
  File "/builddir/hydrus-497/hydrus/test/TestClientDBDuplicates.py", line 461, in _test_poach_better
    self.assertEqual( file_duplicate_types_to_counts[ HC.DUPLICATE_POTENTIAL ], self._get_group_potential_count( file_duplicate_types_to_counts ) )
AssertionError: 20 != 21

----------------------------------------------------------------------
Ran 93 tests in 41.142s

FAILED (failures=1)
A file failed to import from import folder imp:/tmp/hydrusivo2a7ir/3
A file failed to import from import folder imp:/tmp/hydrusivo2a7ir/4
Import folder imp imported 3 files.
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c added a new account type, "regular user".
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c added a new account type, "deletee user".
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c deleted the account type, "deletee user", replacing them with "regular user".
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c changed the account type of 2c825b2ba563eda62e13522a1c2690d48cfc4387a0a86ea1b5d958bfb36ed032 from "regular user" to "administrator".
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c changed the account type of 2c825b2ba563eda62e13522a1c2690d48cfc4387a0a86ea1b5d958bfb36ed032 from "administrator" to "regular user".
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c banned 2c825b2ba563eda62e13522a1c2690d48cfc4387a0a86ea1b5d958bfb36ed032 with reason "oh no no no" until "does not expire".
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c banned 2c825b2ba563eda62e13522a1c2690d48cfc4387a0a86ea1b5d958bfb36ed032 with reason "just having a giggle m8" until "expires in 1 day".
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c unbanned 2c825b2ba563eda62e13522a1c2690d48cfc4387a0a86ea1b5d958bfb36ed032.
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c changed the expiration of 2c825b2ba563eda62e13522a1c2690d48cfc4387a0a86ea1b5d958bfb36ed032 from "expires in 1 year" to "expired 5 seconds ago".
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c changed the expiration of 2c825b2ba563eda62e13522a1c2690d48cfc4387a0a86ea1b5d958bfb36ed032 from "expired 5 seconds ago" to "expires in 1 day".
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c changed the expiration of 2c825b2ba563eda62e13522a1c2690d48cfc4387a0a86ea1b5d958bfb36ed032 from "expires in 1 day" to "does not expire".
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c set 2c825b2ba563eda62e13522a1c2690d48cfc4387a0a86ea1b5d958bfb36ed032 with a message.
Account 7186a1539651b3f095bce226b80d370b4056f2d6382af61a3bc7861f07ec790c cleared 2c825b2ba563eda62e13522a1c2690d48cfc4387a0a86ea1b5d958bfb36ed032 of any message.
This was version 497
```

**Comment by hydrusnetwork** [comment]
Thank you for this report! Sorry I am late to it. I get this damn thing myself too, usually after I have forgotten about it, and always at the time when I am most busy on Wednesday and never make a proper job to fix it. I'm pretty sure it is due to me foolishly making a giganto unit test populated by a bunch of random data that sometimes makes one complex structure, sometimes another. The count test is now patched and, hopefully, will not cause trouble again.

Please let me know if you discover any more like this.
