### ISSUE TITLE
[Issue] Hydrus failing to download hundreds of normally accessable booru links

### ISSUE THREAD

**Issue by HASJ** [hydrusnetwork/hydrus#123]
SFW
https://chan.sankakucomplex.com/post/show/3954108
https://chan.sankakucomplex.com/post/show/3954101
https://chan.sankakucomplex.com/post/show/3954108

NFSW
https://chan.sankakucomplex.com/post/show/1371929
This one has been on the list for 1 month and 1 day. Working normally through the browser but Hydrus just won't download it, no matter how many times I 'Try again'.

This is what the log gives me:
```
2015/12/16 15:28:46: hydrus client started
2015/12/16 15:28:46: booting controller...
2015/12/16 15:28:46: booting db...
2015/12/16 15:28:53: booting gui...
2015/12/16 15:47:23: Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientImporting", line 230, in _WorkOnFiles
ValueError: need more than 0 values to unpack

2015/12/16 15:47:29: Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientImporting", line 230, in _WorkOnFiles
ValueError: need more than 0 values to unpack

2015/12/16 15:47:35: Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientImporting", line 230, in _WorkOnFiles
ValueError: need more than 0 values to unpack

2015/12/16 15:47:41: Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientImporting", line 230, in _WorkOnFiles
ValueError: need more than 0 values to unpack

2015/12/16 15:47:46: Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientImporting", line 230, in _WorkOnFiles
ValueError: need more than 0 values to unpack

2015/12/16 15:47:52: Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientImporting", line 230, in _WorkOnFiles
ValueError: need more than 0 values to unpack
```
ad nauseum

EDIT: This one just happened:
```
2015/12/16 16:55:51: Traceback (most recent call last):
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.ClientImporting", line 211, in _WorkOnFiles
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusController", line 254, in WriteSynchronous
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusController", line 77, in _Write
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusDB", line 341, in Write
  File "C:\code\Hydrus\build\client\out00-PYZ.pyz\include.HydrusData", line 1692, in GetResult
DBException: (u'image file is truncated (10 bytes not processed)', 'Stack Trace (most recent call last):\r\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\threading", line 783, in __bootstrap\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\threading", line 810, in __bootstrap_inner\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\threading", line 763, in run\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.ClientImporting", line 412, in _THREADWork\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.ClientImporting", line 211, in _WorkOnFiles\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.HydrusController", line 254, in WriteSynchronous\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.HydrusController", line 77, in _Write\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.HydrusDB", line 341, in Write\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.HydrusData", line 1688, in GetResult\n', 'Traceback (most recent call last):\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.HydrusDB", line 200, in _ProcessJob\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.ClientDB", line 6763, in _Write\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.ClientDB", line 4144, in _ImportFile\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.HydrusFileHandling", line 74, in GenerateThumbnail\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.HydrusFileHandling", line 47, in SaveThumbnailToStream\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\include.HydrusImageHandling", line 70, in EfficientlyThumbnailPILImage\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\PIL.Image", line 1776, in thumbnail\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\PIL.Image", line 1517, in resize\n\r\n  File "C:\\code\\Hydrus\\build\\client\\out00-PYZ.pyz\\PIL.ImageFile", line 222, in load\n\r\nIOError: image file is truncated (10 bytes not processed)\n')
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. There was a bug in my gallery code that was attempting to load previously deleted files in some circumstances. This imports fine for me:

https://chan.sankakucomplex.com/post/show/3954108

But I suspect you have previously deleted it, which was causing the ValueError exception. This is fixed for v187.

You can confirm the file was previously deleted by downloading it to hard drive and importing it through the normal drag-and-drop hdd import, which should correctly report that the file was previously deleted.

Unfortunately, the file at:

https://chan.sankakucomplex.com/post/show/1371929

Is actually broken. If you look at the bottom right hand corner, you may see a small grey box. The jpg is missing some data. Some image libraries can handle broken files, and they usually fill in the missing data with grey or similar, but I am afraid hydrus cannot. The image probably should not be on Sankaku, or it should be replaced with a non truncated version.

If you do not care about the image being slightly broken, try downloading it in your browser and loading and then resaving it in photoshop or another good image program. A clever image program should be able to handle the truncation, and when you save the image, it should fill in the broken area with grey or something else valid. You should be able to import the fixed file into hydrus.
