### ISSUE TITLE
Freeze, crash, and excessive hard-drive use during shutdown maintenance

### ISSUE THREAD

**Issue by TheCommandoChicken** [hydrusnetwork/hydrus#1239]
### Hydrus version

v499

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Extract

### Install and OS comments

Ubuntu 20.04.4

### Bug description and reproduction

When attempting to perform shutdown maintenance, the client hits a point where it freezes and stops progressing, and begins filling up my hard-drive with data at around 8+ MB/s until it inevitably runs out of space, which causes it to crash. After the client is closed the data it wrote is wiped, and the hard-drive returns to normal. This began on an older version, but has not gone away after updating.

### Log output

```text
v499, 2022/09/24 13:41:46: shutting down gui…
v499, 2022/09/24 13:41:46: waiting for managers to exit
v499, 2022/09/24 13:41:46: waiting for workers to exit
v499, 2022/09/24 13:41:46: waiting for idle shutdown work
v499, 2022/09/24 15:43:58: A serious error occurred while trying to exit the program. Its traceback may be shown next. It should have also been written to client.log. You may need to quit the program from task manager.
v499, 2022/09/24 15:43:58: When the transaction failed, attempting to rollback the database failed. Please restart the client as soon as is convenient.
v499, 2022/09/24 15:43:58: Traceback (most recent call last):
  File "hydrus/client/ClientController.py", line 1978, in ShutdownView
    self.DoIdleShutdownWork()
  File "hydrus/client/ClientController.py", line 765, in DoIdleShutdownWork
    self.MaintainDB( maintenance_mode = HC.MAINTENANCE_SHUTDOWN, stop_time = stop_time )
  File "hydrus/client/ClientController.py", line 1357, in MaintainDB
    self.WriteSynchronous( 'maintain_similar_files_tree', maintenance_mode = maintenance_mode, stop_time = tree_stop_time )
  File "hydrus/core/HydrusController.py", line 934, in WriteSynchronous
    return self._Write( action, True, *args, **kwargs )
  File "hydrus/core/HydrusController.py", line 241, in _Write
    result = self.db.Write( action, synchronous, *args, **kwargs )
  File "hydrus/core/HydrusDB.py", line 953, in Write
    if synchronous: return job.GetResult()
  File "hydrus/core/HydrusData.py", line 2057, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: OperationalError: database or disk is full
Database Traceback (most recent call last):
  File "hydrus/core/HydrusDB.py", line 614, in _ProcessJob
    result = self._Write( action, *args, **kwargs )
  File "hydrus/client/db/ClientDB.py", line 12094, in _Write
    elif action == 'maintain_similar_files_tree': self.modules_similar_files.MaintainTree( *args, **kwargs )
  File "hydrus/client/db/ClientDBSimilarFiles.py", line 545, in MaintainTree
    self._RegenerateBranch( job_key, biggest_perceptual_hash_id )
  File "hydrus/client/db/ClientDBSimilarFiles.py", line 349, in _RegenerateBranch
    unbalanced_nodes = self._Execute( with_clause + ' SELECT branch_phash_id, phash FROM branch, shape_perceptual_hashes ON phash_id = branch_phash_id;', ( perceptual_hash_id, ) ).fetchall()
  File "hydrus/core/HydrusDBBase.py", line 228, in _Execute
    return self._c.execute( query, *args )
sqlite3.OperationalError: database or disk is full


v499, 2022/09/24 15:43:58: shutdown error
v499, 2022/09/24 15:43:58: A serious error occurred while trying to exit the program. Its traceback may be shown next. It should have also been written to client.log. You may need to quit the program from task manager.
v499, 2022/09/24 15:44:03: Tried to release a database savepoint, but failed!
v499, 2022/09/24 17:00:07: shutdown error
v499, 2022/09/24 17:00:07: Traceback (most recent call last):
  File "hydrus/client/ClientController.py", line 1978, in ShutdownView
    self.DoIdleShutdownWork()
  File "hydrus/client/ClientController.py", line 765, in DoIdleShutdownWork
    self.MaintainDB( maintenance_mode = HC.MAINTENANCE_SHUTDOWN, stop_time = stop_time )
  File "hydrus/client/ClientController.py", line 1357, in MaintainDB
    self.WriteSynchronous( 'maintain_similar_files_tree', maintenance_mode = maintenance_mode, stop_time = tree_stop_time )
  File "hydrus/core/HydrusController.py", line 934, in WriteSynchronous
    return self._Write( action, True, *args, **kwargs )
  File "hydrus/core/HydrusController.py", line 241, in _Write
    result = self.db.Write( action, synchronous, *args, **kwargs )
  File "hydrus/core/HydrusDB.py", line 953, in Write
    if synchronous: return job.GetResult()
  File "hydrus/core/HydrusData.py", line 2057, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: OperationalError: database or disk is full
Database Traceback (most recent call last):
  File "hydrus/core/HydrusDB.py", line 614, in _ProcessJob
    result = self._Write( action, *args, **kwargs )
  File "hydrus/client/db/ClientDB.py", line 12094, in _Write
    elif action == 'maintain_similar_files_tree': self.modules_similar_files.MaintainTree( *args, **kwargs )
  File "hydrus/client/db/ClientDBSimilarFiles.py", line 545, in MaintainTree
    self._RegenerateBranch( job_key, biggest_perceptual_hash_id )
  File "hydrus/client/db/ClientDBSimilarFiles.py", line 349, in _RegenerateBranch
    unbalanced_nodes = self._Execute( with_clause + ' SELECT branch_phash_id, phash FROM branch, shape_perceptual_hashes ON phash_id = branch_phash_id;', ( perceptual_hash_id, ) ).fetchall()
  File "hydrus/core/HydrusDBBase.py", line 228, in _Execute
    return self._c.execute( query, *args )
sqlite3.OperationalError: database or disk is full


v499, 2022/09/24 17:00:14: waiting for services to exit
v499, 2022/09/24 17:00:14: stopping services…
v499, 2022/09/24 17:00:14: shutting down db…
v499, 2022/09/24 17:00:14: saving and exiting objects
v499, 2022/09/24 17:00:19: cleaning up…
v499, 2022/09/24 17:00:19: shutting down controller…
v499, 2022/09/24 17:00:19: hydrus client shut down
```

**Comment by hydrusnetwork** [comment]
Thank you very much for this report. The traceback is extremely useful. I had a similar report from someone else recently, and I am sorry for the trouble. Please disable your maintenance work in **idle time** and **shutdown** for now under _options->maintenance and processing_. I will examine what is going on here and fix it for v500.

**Comment by hydrusnetwork** [comment]
Sorry again! This is fixed for v500 tomorrow. You can turn idle/shutdown maintenance back on then, and please let me know if you have any more trouble with it.
