### ISSUE TITLE
Searching for empty array with file search API throws error

### ISSUE THREAD

**Issue by floogulinc** [hydrusnetwork/hydrus#1250]
### Hydrus version

501

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Installer

### Bug description and reproduction

1. Search for `[]`, for example `http://127.0.0.1:45869/get_files/search_files?tags=[]`
2. get error

### Log output

```text
The repository encountered an error it could not handle! Here is a dump of what
happened, which will also be written to your client.log file. If it persists,
please forward it to hydrus.admin@gmail.com:

Traceback (most recent call last):
File "threading.py", line 932, in _bootstrap_inner

File "threading.py", line 870, in run

File "twisted\_threads\_threadworker.py", line 47, in work

File "twisted\_threads\_team.py", line 182, in doWork

--- <exception caught here> ---
  File "twisted\python\threadpool.py", line 244, in inContext

  File "twisted\python\threadpool.py", line 260, in <lambda>

    File "twisted\python\context.py", line 117, in callWithContext

    File "twisted\python\context.py", line 82, in callWithContext

    File "hydrus\client\networking\ClientLocalServerResources.py", line 2227, in
    _threadDoGETJob
    if return_hashes:
    builtins.UnboundLocalError: local variable 'return_hashes' referenced before
    assignment
```

**Comment by evanjs** [comment]
No idea if it's a valid fix, but this ensures that I get "No results found" rather than a 500 error

<details>
<summary><code>hydrus/client/networking/ClientLocalServerResources.py</code></summary>

```diff
diff --git a/hydrus/client/networking/ClientLocalServerResources.py b/hydrus/client/networking/ClientLocalServerResources.py
index 1ab773c6..48aa20c4 100644
--- a/hydrus/client/networking/ClientLocalServerResources.py
+++ b/hydrus/client/networking/ClientLocalServerResources.py
@@ -2117,6 +2117,8 @@ class HydrusResourceClientAPIRestrictedGetFiles( HydrusResourceClientAPIRestrict
 class HydrusResourceClientAPIRestrictedGetFilesSearchFiles( HydrusResourceClientAPIRestrictedGetFiles ):

     def _threadDoGETJob( self, request: HydrusServerRequest.HydrusRequest ):
+        return_hashes = False
+        return_file_ids =  True

         location_context = ParseLocationContext( request, ClientLocation.LocationContext.STATICCreateSimple( CC.COMBINED_LOCAL_MEDIA_SERVICE_KEY ) )

@@ -2199,8 +2201,6 @@ class HydrusResourceClientAPIRestrictedGetFilesSearchFiles( HydrusResourceClient
             # newest first
             sort_by = ClientMedia.MediaSort( sort_type = ( 'system', file_sort_type ), sort_order = sort_order )

-            return_hashes = False
-
             if 'return_hashes' in request.parsed_request_args:

                 return_hashes = request.parsed_request_args.GetValue( 'return_hashes', bool )
```

</details>

**Comment by hydrusnetwork** [comment]
Thanks again for this report. Fixed in tomorrow's release! It now always gives [] on an empty input, and it throws a 400 if you give it any invalid tags.
