### ISSUE TITLE
No module named 'dateutil'

### ISSUE THREAD

**Issue by Wyrrrd** [hydrusnetwork/hydrus#1251]
My hydrus is not starting correctly on docker and throws a ModuleNotFoundError exception.

I am using the latest image (version 502), and only persist `/opt/hydrus/db/` from the previous version.

```
2022-10-13 12:48:54,055 INFO spawned: 'hydrus' with pid 1652
2022-10-13 12:48:55,056 INFO success: hydrus entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
v502, 2022/10/13 12:48:55: hydrus client started
v502, 2022/10/13 12:48:55: hydrus client failed
v502, 2022/10/13 12:48:55: Traceback (most recent call last):
  File "/opt/hydrus/hydrus/hydrus_client.py", line 230, in boot
    from hydrus.client import ClientController
  File "/usr/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/opt/hydrus/hydrus/client/ClientController.py", line 26, in <module>
    from hydrus.client import ClientAPI
  File "/usr/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/opt/hydrus/hydrus/client/ClientAPI.py", line 10, in <module>
    from hydrus.client import ClientSearch
  File "/usr/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/opt/hydrus/hydrus/client/ClientSearch.py", line 19, in <module>
    from hydrus.client import ClientTime
  File "/usr/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/opt/hydrus/hydrus/client/ClientTime.py", line 2, in <module>
    from dateutil.relativedelta import relativedelta
  File "/usr/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'dateutil'
v502, 2022/10/13 12:48:55: hydrus client shut down
2022-10-13 12:48:56,528 INFO exited: hydrus (exit status 0; expected)
```

**Comment by OwDoge42** [comment]
Same exact issue here, same persistent volume. Hydrus container is up, but non-functional atm.

**Comment by docchaoswizard** [comment]
Same issue here on MacOS:

```
╰─$ /Applications/Hydrus\ Network.app/Contents/MacOS/client
v502, 2022/10/15 15:18:44: hydrus client started
v502, 2022/10/15 15:18:44: hydrus client failed
v502, 2022/10/15 15:18:44: Traceback (most recent call last):
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/hydrus_client.py", line 230, in boot
    from hydrus.client import ClientController
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/ClientController.py", line 26, in <module>
    from hydrus.client import ClientAPI
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/ClientAPI.py", line 10, in <module>
    from hydrus.client import ClientSearch
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/ClientSearch.py", line 19, in <module>
    from hydrus.client import ClientTime
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/ClientTime.py", line 2, in <module>
    from dateutil.relativedelta import relativedelta
ModuleNotFoundError: No module named 'dateutil'

v502, 2022/10/15 15:18:44: hydrus client shut down
```

**Comment by schneckenschnabel** [comment]
I am using hydrus via virtualenv and the problem is fixable if you install the missing module via "pip install python-dateutil"
I guess the package from your package manager could fix the issue too

**Comment by docchaoswizard** [comment]
> I am using hydrus via virtualenv and the problem is fixable if you install the missing module via "pip install python-dateutil" I guess the package from your package manager could fix the issue too

This does not fix the issue on MacOS when running via the package. Which makes sense because the release is a compiled executable. Maybe we should split the issue?

**Comment by hydrusnetwork** [comment]
Hey, sorry guys! Thank you for the reports. I thought this library was default to python, and all my dev and the Windows/Linux builds were no problem, but it seems on macOS and Docker this is not true. I just pushed a hotfix that includes the library explicitly and also fails safely if it somehow isn't, the Docker package is built, v502a, and the macOS build is being made now here: https://github.com/hydrusnetwork/hydrus/releases/tag/v502a

I will update my release post macOS links once the build is done.
