### ISSUE TITLE
Crash on trying to launch client.exe

### ISSUE THREAD

**Issue by NdymBzyd** [hydrusnetwork/hydrus#1254]
### Hydrus version

v502a

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

Updated from v498 to v502a
Produces a crash log without visibly launching the client.

### Log output

```text
Traceback (most recent call last):
  File "hydrus\hydrus_client.py", line 24, in <module>
    from hydrus.client.gui import QtInit
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "hydrus\client\gui\QtInit.py", line 33, in <module>
    from qtpy import QtCore as QC
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "qtpy\QtCore.py", line 116, in <module>
  File "shibokensupport/enum_310.py", line 529, in __setattr__
AttributeError: Cannot reassign members.
```

**Comment by ProNoob135** [comment]
Same issue on Arch
`Traceback (most recent call last):
  File "/opt/hydrus/hydrus/hydrus_client.py", line 24, in <module>
    from hydrus.client.gui import QtInit
  File "/opt/hydrus/hydrus/client/gui/QtInit.py", line 33, in <module>
    from qtpy import QtCore as QC
  File "/usr/lib/python3.10/site-packages/qtpy/QtCore.py", line 90, in <module>
    Qt.MidButton = Qt.MouseButton.MiddleButton = Qt.MiddleButton
  File "/usr/lib/python3.10/enum.py", line 480, in __setattr__
    raise AttributeError('Cannot reassign members.')
AttributeError: Cannot reassign members.
`

**Comment by ProNoob135** [comment]
![image](https://user-images.githubusercontent.com/17394474/196553197-5a4bb463-7284-413c-8ebf-5590acb217b1.png)

**Comment by hydrusnetwork** [comment]
Sorry lads. Thank you for the report, this is fixed in tomorrow's release. I've done some extra work to make sure this stupid stuff shouldn't happen again.
