### ISSUE TITLE
Clicking the Hydrus tray icon in Gnome launches a new hydrus session (which just gives a db lock error)

### ISSUE THREAD

**Issue by sbstratos79** [hydrusnetwork/hydrus#1274]
### Hydrus version

v499

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

EndeavourOS, Linux 6.0.7-arch1-1
Gnome 43.1
Hydrus was installed via Flatpak

### Bug description and reproduction

I am not certain but I think this issue started after the latest Gnome update, 3 days ago.
Clicking the Hydrus tray icon launches a new instance (which just ends up throwing a db lock error, because of the already running Hydrus instance), instead of restoring the old Hydrus window.

Clicking the "Show" option from the tray icon context menu restores the Hydrus window like it used to before the Gnome update.

The attached log is generated when I click the Hydrus tray icon.

### Log output

```text
v499, 2022/11/10 15:13:00: hydrus client started
v499, 2022/11/10 15:13:02: booting controller…
v499, 2022/11/10 15:13:02: booting db…
v499, 2022/11/10 15:13:02: Found and deleted the durable temporary database on boot. The last exit was probably not clean.
v499, 2022/11/10 15:13:07: If the db crashed, another error may be written just above ^.
v499, 2022/11/10 15:13:07: A serious error occurred while trying to start the program. The error will be shown next in a window. More information may have been written to client.log.
v499, 2022/11/10 15:13:07: Traceback (most recent call last):
  File "/app/hydrus/hydrus/core/HydrusDB.py", line 559, in _InitDBConnection
    self._cursor_transaction_wrapper.BeginImmediate()
  File "/app/hydrus/hydrus/core/HydrusDBBase.py", line 417, in BeginImmediate
    self._Execute( 'BEGIN IMMEDIATE;' )
  File "/app/hydrus/hydrus/core/HydrusDBBase.py", line 228, in _Execute
    return self._c.execute( query, *args )
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/hydrus/hydrus/client/ClientController.py", line 2117, in THREADBootEverything
    self.InitModel()
  File "/app/hydrus/hydrus/client/ClientController.py", line 1006, in InitModel
    HydrusController.HydrusController.InitModel( self )
  File "/app/hydrus/hydrus/core/HydrusController.py", line 545, in InitModel
    self.db = self._InitDB()
  File "/app/hydrus/hydrus/client/ClientController.py", line 215, in _InitDB
    return ClientDB.DB( self, self.db_dir, 'client' )
  File "/app/hydrus/hydrus/client/db/ClientDB.py", line 239, in __init__
    HydrusDB.HydrusDB.__init__( self, controller, db_dir, db_name )
  File "/app/hydrus/hydrus/core/HydrusDB.py", line 248, in __init__
    self._InitDB()
  File "/app/hydrus/hydrus/core/HydrusDB.py", line 452, in _InitDB
    self._InitDBConnection()
  File "/app/hydrus/hydrus/core/HydrusDB.py", line 565, in _InitDBConnection
    raise HydrusExceptions.DBAccessException( 'Database appeared to be locked. Please ensure there is not another client already running on this database, and then try restarting the client.' )
hydrus.core.HydrusExceptions.DBAccessException: Database appeared to be locked. Please ensure there is not another client already running on this database, and then try restarting the client.

v499, 2022/11/10 15:13:07: boot error
v499, 2022/11/10 15:13:07: A serious error occurred while trying to start the program. The error will be shown next in a window. More information may have been written to client.log.
v499, 2022/11/10 15:13:10: boot error
v499, 2022/11/10 15:13:10: Traceback (most recent call last):
  File "/app/hydrus/hydrus/core/HydrusDB.py", line 559, in _InitDBConnection
    self._cursor_transaction_wrapper.BeginImmediate()
  File "/app/hydrus/hydrus/core/HydrusDBBase.py", line 417, in BeginImmediate
    self._Execute( 'BEGIN IMMEDIATE;' )
  File "/app/hydrus/hydrus/core/HydrusDBBase.py", line 228, in _Execute
    return self._c.execute( query, *args )
sqlite3.OperationalError: database is locked

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/hydrus/hydrus/client/ClientController.py", line 2117, in THREADBootEverything
    self.InitModel()
  File "/app/hydrus/hydrus/client/ClientController.py", line 1006, in InitModel
    HydrusController.HydrusController.InitModel( self )
  File "/app/hydrus/hydrus/core/HydrusController.py", line 545, in InitModel
    self.db = self._InitDB()
  File "/app/hydrus/hydrus/client/ClientController.py", line 215, in _InitDB
    return ClientDB.DB( self, self.db_dir, 'client' )
  File "/app/hydrus/hydrus/client/db/ClientDB.py", line 239, in __init__
    HydrusDB.HydrusDB.__init__( self, controller, db_dir, db_name )
  File "/app/hydrus/hydrus/core/HydrusDB.py", line 248, in __init__
    self._InitDB()
  File "/app/hydrus/hydrus/core/HydrusDB.py", line 452, in _InitDB
    self._InitDBConnection()
  File "/app/hydrus/hydrus/core/HydrusDB.py", line 565, in _InitDBConnection
    raise HydrusExceptions.DBAccessException( 'Database appeared to be locked. Please ensure there is not another client already running on this database, and then try restarting the client.' )
hydrus.core.HydrusExceptions.DBAccessException: Database appeared to be locked. Please ensure there is not another client already running on this database, and then try restarting the client.

v499, 2022/11/10 15:13:12: doing fast shutdown…
v499, 2022/11/10 15:13:12: shutting down gui…
v499, 2022/11/10 15:13:12: shutting down db…
v499, 2022/11/10 15:13:12: saving and exiting objects
v499, 2022/11/10 15:13:12: cleaning up…
v499, 2022/11/10 15:13:12: shutting down controller…
v499, 2022/11/10 15:13:12: hydrus client shut down
```

**Comment by Zweibach** [comment]
Your Hydrus is out of date.
