### ISSUE TITLE
SIGSEGV on theme change

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#13]
After changing theme in lxappearance (actually just applying the same theme):

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff35ac354 in wxWindowBase::OnSysColourChanged(wxSysColourChangedEvent&) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
(gdb) bt
#0  0x00007ffff35ac354 in wxWindowBase::OnSysColourChanged(wxSysColourChangedEvent&) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#1  0x00000030fc66fb5e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#2  0x00000030fc80c508 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#3  0x00000030fc80c60b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/libwx_baseu-3.0.so.0
#4  0x00000030fc80c9b8 in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#5  0x00000030fc80ca43 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#6  0x00000030fc80caa5 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#7  0x00007ffff35ac395 in wxWindowBase::OnSysColourChanged(wxSysColourChangedEvent&) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#8  0x00000030fc66fb5e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#9  0x00000030fc80c508 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#10 0x00000030fc80c60b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/libwx_baseu-3.0.so.0
#11 0x00000030fc80c9b8 in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#12 0x00000030fc80ca43 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#13 0x00000030fc80caa5 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#14 0x00007ffff35ac395 in wxWindowBase::OnSysColourChanged(wxSysColourChangedEvent&) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#15 0x00000030fc66fb5e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#16 0x00000030fc80c508 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#17 0x00000030fc80c60b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/libwx_baseu-3.0.so.0
#18 0x00000030fc80c9b8 in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#19 0x00000030fc80ca43 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#20 0x00000030fc80caa5 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#21 0x00007ffff35ac395 in wxWindowBase::OnSysColourChanged(wxSysColourChangedEvent&) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#22 0x00000030fc66fb5e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#23 0x00000030fc80c508 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#24 0x00000030fc80c60b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/libwx_baseu-3.0.so.0
#25 0x00000030fc80c9b8 in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#26 0x00000030fc80ca43 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#27 0x00000030fc80caa5 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#28 0x00007ffff35ac395 in wxWindowBase::OnSysColourChanged(wxSysColourChangedEvent&) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#29 0x00000030fc66fb5e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#30 0x00000030fc80c508 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#31 0x00000030fc80c60b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/libwx_baseu-3.0.so.0
#32 0x00000030fc80c9b8 in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#33 0x00000030fc80ca43 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#34 0x00000030fc80caa5 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#35 0x00007ffff35ac395 in wxWindowBase::OnSysColourChanged(wxSysColourChangedEvent&) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#36 0x00000030fc66fb5e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#37 0x00000030fc80c508 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#38 0x00000030fc80c60b in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () from /usr/lib/libwx_baseu-3.0.so.0
#39 0x00000030fc80c9b8 in wxEvtHandler::TryHereOnly(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#40 0x00000030fc80ca43 in wxEvtHandler::ProcessEventLocally(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#41 0x00000030fc80caa5 in wxEvtHandler::ProcessEvent(wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
#42 0x00007ffff35ac395 in wxWindowBase::OnSysColourChanged(wxSysColourChangedEvent&) () from /usr/lib/libwx_gtk2u_core-3.0.so.0
#43 0x00000030fc66fb5e in wxAppConsoleBase::CallEventHandler(wxEvtHandler*, wxEventFunctor&, wxEvent&) const () from /usr/lib/libwx_baseu-3.0.so.0
#44 0x00000030fc80c508 in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () from /usr/lib/libwx_baseu-3.0.so.0
```

the trace continues for several thousand lines in the same way

**Comment by CuddleBear92** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
