### ISSUE TITLE
MacOS File Permissions Error when Exporting

### ISSUE THREAD

**Issue by KamillaPup** [hydrusnetwork/hydrus#1322]
### Hydrus version

512

### Qt major version

Qt 6

### Operating system

macOS 12 "Monterey" (Apple silicon)

### Install method

Installer

### Bug description and reproduction

![CleanShot 2023-01-12 at 12 13 52](https://user-images.githubusercontent.com/26353056/212147220-394a1b4e-d6d5-49f3-997f-e1f7828dd413.png)

When exporting files to my home folder, it keeps telling me PermissionError, Operation not permitted. This is weird as the files are being exported just fine so not sure why it's crying.

**Comment by KamillaPup** [comment]
So I tried this again with an external drive formatted with exFat so no permissions and it still gives it despite Hydrus Network having full disk access. Here is the full trace back:
`v519, darwin, frozen
PermissionError
[Errno 1] Operation not permitted: '/Volumes/Wolf/red-wolf-hydrus/z00p/149645.jpg'
Traceback (most recent call last):
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/core/HydrusPaths.py", line 649, in MirrorFile
    safe_copy2( source, dest )
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/core/HydrusPaths.py", line 530, in safe_copy2
    shutil.copy2( source, dest )
  File "shutil", line 445, in copy2
    copystat(src, dst, follow_symlinks=follow_symlinks)
  File "shutil", line 405, in copystat
    lookup("chflags")(dst, st.st_flags, follow_symlinks=follow)
PermissionError: [Errno 1] Operation not permitted: '/Volumes/Wolf/red-wolf-hydrus/z00p/149645.jpg'
`

**Comment by KamillaPup** [comment]
Thanks for the reply! No, the db files are all stored on the boot drive in the default location along with the thumbs. 
![CleanShot 2023-03-10 at 21 26 05](https://user-images.githubusercontent.com/26353056/224462586-970769c4-27c7-4bb8-add4-413a472dcdb4.png)
I made sure to grant the app full disk access. 
![CleanShot 2023-03-10 at 21 20 11](https://user-images.githubusercontent.com/26353056/224462250-dc80e109-7bcf-44c2-a2e9-bc7f70b21b64.png)
The cp command works fine with no errors.
```Mac-Studio ~ % cp /Volumes/home/Hydrus/client_files/f8b/8b0c34dcf50b4aa20d6156136d20dee479fe0f0153d18347a07179dcd074194a.jpg /Volumes/Wolf/red-wolf-hydrus/z00p```

**Comment by bbappserver** [comment]
@KamillaPup
This error while annoying is safe to ignore based on your description.
Hydrus is using `shutil.copy2()`, which attempts to preserve any file attributes.
It is failing when attempting to copy flags from the source to the target.  It is failing for one of the following reasons

## Failure modes of `chflags()`
[[EPERM](https://manpages.debian.org/bullseye/freebsd-manpages/chflags.2freebsd.en.html#EPERM)]
The effective user ID does not match the owner of the file and the effective user ID is not the super-user.
[[EPERM](https://manpages.debian.org/bullseye/freebsd-manpages/chflags.2freebsd.en.html#EPERM~2)]
One of SF_IMMUTABLE, SF_APPEND, or SF_NOUNLINK is set and the user is either not the super-user or securelevel is greater than 0.
[[EPERM](https://manpages.debian.org/bullseye/freebsd-manpages/chflags.2freebsd.en.html#EPERM~3)]
A non-super-user attempted to toggle one of SF_ARCHIVED, SF_IMMUTABLE, SF_APPEND, or SF_NOUNLINK.
[[EPERM](https://manpages.debian.org/bullseye/freebsd-manpages/chflags.2freebsd.en.html#EPERM~4)]
An attempt was made to toggle the SF_SNAPSHOT flag.
https://manpages.debian.org/bullseye/freebsd-manpages/chflags.2freebsd.en.html
