### ISSUE TITLE
Cannot generate webm thumbnails, preventing file upload. (name 'cv2' is not defined)

### ISSUE THREAD

**Issue by outfoxxed** [hydrusnetwork/hydrus#1344]
### Hydrus version

520

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

nixos 22.11, sway (wayland)

Installed via nixpkgs, since I didn't want to update my whole system I overrode the package definition to match https://github.com/NixOS/nixpkgs/blob/548a54f4d56155df4beadad2621ae5111ad309ad/pkgs/applications/graphics/hydrus/default.nix

Note: I have tested that the symbol is reachable with the package's python environment using the following method (creating a python environment containing hydrus's listed runtime dependencies)
```
❯ nix repl '<nixpkgs>'
warning: future versions of Nix will require using `--file` to load a file
Welcome to Nix 2.13.3. Type :? for help.

Loading installable ''...
Added 18552 variables.
nix-repl> :b pkgs.python3.withPackages (_: pkgs.hydrus.propagatedBuildInputs)

This derivation produced the following outputs:
  out -> /nix/store/1v2g36slfyjy8zij3528mma0haxgni5k-python3-3.10.10-env

nix-repl> :q
❯ /nix/store/1v2g36slfyjy8zij3528mma0haxgni5k-python3-3.10.10-env/bin/python
Python 3.10.10 (main, Feb  7 2023, 12:19:31) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.INTER_LANCZOS4
4
>>> quit()
```

### Bug description and reproduction

To reproduce: upload any webm to a server (tested with a few different ones).

### Log output

```text
v520, 2023/03/21 23:52:59: uploading pending to my file repo
my file repo error
v520, 2023/03/21 23:52:59: Traceback (most recent call last):
  File "/nix/store/2zrg5lv6cay5f29cxmwy4x5h5bwdxydm-python3.10-hydrus-519/lib/python3.10/site-packages/hydrus/core/HydrusThreading.py", line 401, in run
    callable( *args, **kwargs )
  File "/nix/store/2zrg5lv6cay5f29cxmwy4x5h5bwdxydm-python3.10-hydrus-519/lib/python3.10/site-packages/hydrus/client/gui/ClientGUI.py", line 313, in THREADUploadPending
    service.Request( HC.POST, 'file', { 'file' : file_bytes } )
  File "/nix/store/2zrg5lv6cay5f29cxmwy4x5h5bwdxydm-python3.10-hydrus-519/lib/python3.10/site-packages/hydrus/client/ClientServices.py", line 1344, in Request
    network_job.WaitUntilDone()
  File "/nix/store/2zrg5lv6cay5f29cxmwy4x5h5bwdxydm-python3.10-hydrus-519/lib/python3.10/site-packages/hydrus/client/networking/ClientNetworkingJobs.py", line 1973, in WaitUntilDone
    raise self._error_exception
hydrus.core.HydrusExceptions.BadRequestException: 400: Could not generate thumbnail from that file:
Traceback (most recent call last):
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/networking/HydrusNetworkVariableHandling.py", line 198, in ParseFileArguments
    thumbnail_bytes = HydrusFileHandling.GenerateThumbnailBytes( path, target_resolution, mime, duration, num_frames, clip_rect = clip_rect )
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/HydrusFileHandling.py", line 161, in GenerateThumbnailBytes
    numpy_image = HydrusImageHandling.ResizeNumPyImage( numpy_image, target_resolution ) # just in case ffmpeg doesn't deliver right
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/HydrusImageHandling.py", line 1056, in ResizeNumPyImage
    interpolation = cv2.INTER_LANCZOS4
NameError: name 'cv2' is not defined


v520, 2023/03/21 23:52:59: Exception:
v520, 2023/03/21 23:52:59: BadRequestException
400: Could not generate thumbnail from that file:
Traceback (most recent call last):
  File "/nix/store/2zrg5lv6cay5f29cxmwy4x5h5bwdxydm-python3.10-hydrus-519/lib/python3.10/site-packages/hydrus/core/HydrusThreading.py", line 401, in run
    callable( *args, **kwargs )
  File "/nix/store/2zrg5lv6cay5f29cxmwy4x5h5bwdxydm-python3.10-hydrus-519/lib/python3.10/site-packages/hydrus/client/gui/ClientGUI.py", line 313, in THREADUploadPending
    service.Request( HC.POST, 'file', { 'file' : file_bytes } )
  File "/nix/store/2zrg5lv6cay5f29cxmwy4x5h5bwdxydm-python3.10-hydrus-519/lib/python3.10/site-packages/hydrus/client/ClientServices.py", line 1344, in Request
    network_job.WaitUntilDone()
  File "/nix/store/2zrg5lv6cay5f29cxmwy4x5h5bwdxydm-python3.10-hydrus-519/lib/python3.10/site-packages/hydrus/client/networking/ClientNetworkingJobs.py", line 1973, in WaitUntilDone
    raise self._error_exception
hydrus.core.HydrusExceptions.BadRequestException: 400: Could not generate thumbnail from that file:
Traceback (most recent call last):
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/networking/HydrusNetworkVariableHandling.py", line 198, in ParseFileArguments
    thumbnail_bytes = HydrusFileHandling.GenerateThumbnailBytes( path, target_resolution, mime, duration, num_frames, clip_rect = clip_rect )
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/HydrusFileHandling.py", line 161, in GenerateThumbnailBytes
    numpy_image = HydrusImageHandling.ResizeNumPyImage( numpy_image, target_resolution ) # just in case ffmpeg doesn't deliver right
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/HydrusImageHandling.py", line 1056, in ResizeNumPyImage
    interpolation = cv2.INTER_LANCZOS4
NameError: name 'cv2' is not defined


Traceback (most recent call last):
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/networking/HydrusNetworkVariableHandling.py", line 198, in ParseFileArguments
    thumbnail_bytes = HydrusFileHandling.GenerateThumbnailBytes( path, target_resolution, mime, duration, num_frames, clip_rect = clip_rect )
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/HydrusFileHandling.py", line 161, in GenerateThumbnailBytes
    numpy_image = HydrusImageHandling.ResizeNumPyImage( numpy_image, target_resolution ) # just in case ffmpeg doesn't deliver right
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/HydrusImageHandling.py", line 1056, in ResizeNumPyImage
    interpolation = cv2.INTER_LANCZOS4
NameError: name 'cv2' is not defined
```

**Comment by thatfuckingbird** [comment]
You are missing the python-opencv (or however it is called on nix) dependency.

**Comment by outfoxxed** [comment]
> @thatfuckingbird 
> You are missing the python-opencv (or however it is called on nix) dependency.

`python-opencv` is called `opencv4`
https://github.com/NixOS/nixpkgs/blob/548a54f4d56155df4beadad2621ae5111ad309ad/pkgs/applications/graphics/hydrus/default.nix#L44

Additionally I was able to import cv2 and access that variable in a python environment with the same dependencies.

**Comment by thatfuckingbird** [comment]
Hmm, looking at the file the error originates from, it does try to import opencv (around line 83), but if there is an import error it suppresses  it and just sets a flag. Probably that's why you're not getting an import error with further info on why it fails... If you want to debug further I would start by removing the try...except there and see why the import fails.

But if this is a nix specific packaging problem, you should contact the maintainers, since hydev won't be able to help with Nix or other 3rd party packages.

**Comment by outfoxxed** [comment]
@thatfuckingbird does the server generate the thumbnail by any chance? I'm noticing only half the error is from my new path
```
v520, 2023/03/22 01:21:21: Exception:
v520, 2023/03/22 01:21:21: BadRequestException
400: Could not generate thumbnail from that file:
Traceback (most recent call last):
  File "/tmp/tmp.mwk76Pd9JQ/source/hydrus/core/HydrusThreading.py", line 401, in run
    callable( *args, **kwargs )
  File "/tmp/tmp.mwk76Pd9JQ/source/hydrus/client/gui/ClientGUI.py", line 313, in THREADUploadPending
    service.Request( HC.POST, 'file', { 'file' : file_bytes } )
  File "/tmp/tmp.mwk76Pd9JQ/source/hydrus/client/ClientServices.py", line 1344, in Request
    network_job.WaitUntilDone()
  File "/tmp/tmp.mwk76Pd9JQ/source/hydrus/client/networking/ClientNetworkingJobs.py", line 1973, in WaitUntilDone
    raise self._error_exception
hydrus.core.HydrusExceptions.BadRequestException: 400: Could not generate thumbnail from that file:
Traceback (most recent call last):
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/networking/HydrusNetworkVariableHandling.py", line 198, in ParseFileArguments
    thumbnail_bytes = HydrusFileHandling.GenerateThumbnailBytes( path, target_resolution, mime, duration, num_frames, clip_rect = clip_rect )
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/HydrusFileHandling.py", line 161, in GenerateThumbnailBytes
    numpy_image = HydrusImageHandling.ResizeNumPyImage( numpy_image, target_resolution ) # just in case ffmpeg doesn't deliver right
  File "/nix/store/70ycn9j20arnblzikk9a5dx8656wj7x9-python3.10-hydrus-503/lib/python3.10/site-packages/hydrus/core/HydrusImageHandling.py", line 1056, in ResizeNumPyImage
    interpolation = cv2.INTER_LANCZOS4
NameError: name 'cv2' is not defined
```

**Comment by thatfuckingbird** [comment]
Oh it's a file repo... No idea about that, never used it. But now that you mention it does look like it (since the error starts with a 400 BadRequestException, so you are getting this back from the server). And the source file is in core/ which is shared between both the client and server. So yeah, check your server environment for cv2.

**Comment by outfoxxed** [comment]
My server environment also has cv2. I do however remove some packages that have dependencies on UI things and stop my server from building (and disable the tests because they depend on them too).
```
❯ nix repl '<nixpkgs>'
warning: future versions of Nix will require using `--file` to load a file
Welcome to Nix 2.13.3. Type :? for help.

Loading installable ''...
Added 17751 variables.
nix-repl> hydrus = pkgs.hydrus.overrideAttrs (old: {
              propagatedBuildInputs = lib.subtractLists (with pkgs.python3Packages; [
                qtpy
                mpv
                pyside2
              ]) old.propagatedBuildInputs;

              nativeBuildInputs = lib.subtractLists [
                pkgs.libsForQt5.wrapQtAppsHook
              ] old.nativeBuildInputs;

              doCheck = false;
              installCheckPhase = "true";
            })

nix-repl> :b pkgs.python3.withPackages (_: hydrus.propagatedBuildInputs)

This derivation produced the following outputs:
  out -> /nix/store/q33psliyslfa3bhzswz79zlbm41f3pq2-python3-3.10.9-env

nix-repl> :q
❯ /nix/store/q33psliyslfa3bhzswz79zlbm41f3pq2-python3-3.10.9-env/bin/python
Python 3.10.9 (main, Dec  6 2022, 18:44:57) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.INTER_LANCZOS4
4
>>>
```

**Comment by outfoxxed** [comment]
Sorry, it appears my deployment tool was being flaky and the server was actually running a build without opencv in path due to it timing out and rolling back the system.
