### ISSUE TITLE
mpv crash

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#1355]
### Hydrus version

v523

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### Install and OS comments

os is a clean install on a new ssd, hydrus is from the old one copy pasted over. was hoping this was a windows 7 issue that would be resolved on 10, I think it may be something else now. 

### Bug description and reproduction

scroll though some mpvs
eventually full program closeing crash
nothing in log that would show anything. 

### Log output

```text
-- the crash happened around 7:35 2023/04/22, there is nothing major in the logs, nealry everything seems to be a hiccup with watchers --

v523, 2023/04/21 20:08:46: PIL\TiffImagePlugin.py:864: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
v523, 2023/04/21 20:49:45: PIL\TiffImagePlugin.py:864: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
v523, 2023/04/22 01:34:19: Error when processing https://www.redgifs.com/watch/deliciousquestionablesiberiantiger!
v523, 2023/04/22 01:34:19: Traceback (most recent call last):
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1364, in WorkOnURL
    network_job.WaitUntilDone()
  File "hydrus\client\networking\ClientNetworkingJobs.py", line 1973, in WaitUntilDone
    raise self._error_exception
hydrus.core.HydrusExceptions.MissingCredentialsException: 401: {"error":{"code":"MissingAuthorizationHeader","description":"authorization required to access this service","docs":"https://github.com/Redgifs/api/wiki/API-access"}}

v523, 2023/04/22 01:41:40: Error when processing https://www.redgifs.com/watch/fatskyblueiberianemeraldlizard!
v523, 2023/04/22 01:41:40: Traceback (most recent call last):
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1364, in WorkOnURL
    network_job.WaitUntilDone()
  File "hydrus\client\networking\ClientNetworkingJobs.py", line 1973, in WaitUntilDone
    raise self._error_exception
hydrus.core.HydrusExceptions.MissingCredentialsException: 401: {"error":{"code":"MissingAuthorizationHeader","description":"authorization required to access this service","docs":"https://github.com/Redgifs/api/wiki/API-access"}}

v523, 2023/04/22 05:09:43: PIL\TiffImagePlugin.py:864: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
v523, 2023/04/22 07:04:23: PIL\TiffImagePlugin.py:864: UserWarning: Corrupt EXIF data.  Expecting to read 4 bytes but only got 0. 
v523, 2023/04/22 07:34:40: hydrus client started
v523, 2023/04/22 07:34:42: booting controller…
v523, 2023/04/22 07:34:42: booting db…
v523, 2023/04/22 07:34:42: Found and deleted the durable temporary database on boot. The last exit was probably not clean.
v523, 2023/04/22 07:34:55: checking database
v523, 2023/04/22 07:35:02: preparing db caches
v523, 2023/04/22 07:35:02: initialising managers
v523, 2023/04/22 07:35:03: booting gui…
v523, 2023/04/22 07:35:04: starting services…
v523, 2023/04/22 07:35:05: Running "client api" on port 45869.
v523, 2023/04/22 07:35:05: services started
```

**Comment by hydrusnetwork** [comment]
Thank you for this report, and I am sorry for the trouble. Crashes are tricky, and doubly so like this where there's no indication of problems before it happens.

*I am assuming when you say 'hydrus is from the old one copy pasted over', this means the install dir and the database directory, not the database directory transplanted to a fresh install. If the latter case is true, then ignore the following, a clean install will not help.*

On Windows 7, we had to use an older mpv dll (`mpv-1.dll`), which I assume you were lingering on, but in the newer installer we use `mpv-2.dll`, which absolutely would cause crashes or simply fail to load on older OSes. You seem to have hit a problem with both the old dll and the new.

I wonder if, since it sounds like you have copied your install folder from the old machine to the new, if you still have 'mpv-1.dll' in your install directory. It is possible that is causing a conflict. If you have both '1' and '2', then I recommend doing a 'clean install', as here:

MAKE SURE YOU MAKE A BACKUP BEFORE THIS

https://hydrusnetwork.github.io/hydrus/getting_started_installing.html#clean_installs

I'd normally just tell you to delete the mpv-1.dll file, but if you have updated an older Win-7-happy install, there could be more conflicts like this, so best to do a full clean install to purge everything. Just delete everything but your database and then reinstall. **PROTIP: Don't delete your database!**

As it happens, I am rolling in a new mpv dll in tomorrow's release, going from 2.0 to 2.1 (although it is still called mpv-2.dll). If this crash is truly because of both the old dlls, and isn't a dll conflict, there's a small chance that the newer one will be nicer to you.

Let me know how it goes for you. If things still crash in the same way with a clean install and the new dll, then I would be suspicious of external problems. Most likely would be a GPU driver thing, I think, or something bizarre, for instance I heard having some streaming service apps open with hydrus can cause audio mute or instability because the streaming service stomps over audio drivers or something while setting up DRM.

**Comment by novastar88** [comment]
Same here, but hydrus crashing when minimalised (error never occurring when hydrus is opened).
I'm getting error and hydrus is freezed and I must kill the process.

[https://imgur.com/xIT16IM](url)

**Comment by hydrusnetwork** [comment]
As an update here--I have decided to try and implement the Qt media player (https://doc.qt.io/qt-6/qmediaplayer.html) as a fallback for mpv. I can't speak for performance until I have played with it, but it should have sound, unlike my 'native' player. Ideally this will happen next week.

@novastar88 sorry for the trouble. Let me know how tomorrow's release, which will have a new 'python-mpv' version, and the QMediaPlayer futher in the future, work for you. I know that minimising to system tray leads to program hangs for some people, which may be related to your problem or something else.

**Comment by alidan** [comment]
Ok, I have been setting things up on my computer so I have back burnered doing anything with mpv/video in hydrus, I am on 526 now, and I am assuming whatever change was made is nothing I need to interface with. 
I have also just done a clean install and booted the db, i'm making sure all my shortcuts function before I got ahead with testing, 

and yea, I had mpv-1 and mpv-2

testing will be a videogame music thread opening each file till sound plays and going to the next, as it never really crashed on playing, just from opening/starting im going to go for 13 passes of 207 files to give 2691 opens. 

pass 1 - pass
pass 2 - crash

Ok, I have a relatively large session, currently about 6 million, and it will hang, I am not 100% sure, but I think that if I change webm when a hang is imminent, this causes the crash. i'm thinking of saving off this session starting a fresh one and doing another test but it may take a while for this.

**Comment by alidan** [comment]
Ok, got a bit of an update, I am now on 537 and with a new gpu, amd 7900 xt, I decided to record a video of it going on, I realized that task manage on the ram tab should be opened about half way through the video, at the 12:12 mark I hit a webm and I couldn't go further, you see how fast I was moving through them beforehand, and I couldnt do anything, however I was able to stop the music, I thought this was just another hang, I am so use to the program just shutting down rather than hanging when it does this, but over on the task manager it says suspended, thats new, about a minute later I realize I went from about 14gb of ram used to about 200mb, then at the end it switched to not responding the suspended then closed. 

https://www.mediafire.com/file/ggvz5kv94rw0f1z/2023-08-08_17-37-51.mkv/file

file is 185mb and 720p, you cant really read much on it but it shows the process of testing it from begning to end, going to do this again and see if I get the same results, if its the normal crash ill post, if its the same as this time ill just do nothing... 

hre is a bit of the log that is relavant, and this crash may have been my fault, going to run though the webm's slow this time, as I actually got an error message in the log for once...

v537, 2023/08/08 15:19:04: saving and hiding gui…
v537, 2023/08/08 15:20:21: shutting down gui…
v537, 2023/08/08 15:20:21: waiting for managers to exit
v537, 2023/08/08 15:20:52: waiting for workers to exit
v537, 2023/08/08 15:20:52: waiting for services to exit
v537, 2023/08/08 15:20:52: stopping services…
v537, 2023/08/08 15:20:52: shutting down db…
v537, 2023/08/08 15:20:52: saving and exiting objects
v537, 2023/08/08 15:20:53: cleaning up…
v537, 2023/08/08 15:20:53: shutting down controller…
v537, 2023/08/08 15:20:53: hydrus client shut down
v537, 2023/08/08 16:55:42: hydrus client started
v537, 2023/08/08 16:55:44: booting controller…
v537, 2023/08/08 16:55:44: booting db…
v537, 2023/08/08 16:55:57: checking database
v537, 2023/08/08 16:56:03: preparing db caches
v537, 2023/08/08 16:56:04: initialising managers
v537, 2023/08/08 16:56:06: booting gui…
v537, 2023/08/08 16:56:07: starting services…
v537, 2023/08/08 16:56:07: Running "client api" on port 45869.
v537, 2023/08/08 16:56:07: services started
v537, 2023/08/08 17:01:39: You have 300 pages open! You can only open a few more before program stability is affected! Please close some now!
v537, 2023/08/08 17:12:04: Your session weight is 26,297,151, which is pretty big! To keep your UI lag-free, please try to close some pages or clear some finished downloaders!
v537, 2023/08/08 17:40:03: [MPV error] main: Too many events queued.

v537, 2023/08/08 17:40:05: [MPV error] main: Too many events queued.

going to make a seperate post for this because I don't believe the results to be fully relevant to the issue, but it was still an mpv crash.

**Comment by alidan** [comment]
Ok got it to crash again for the same reason, over about 1 hour I went though the files at about 1 per 3~ seconds, 

at 55:05 it suspends again, it is the same error as last time, and if I remember correctly, roughly the same number of passes so seemingly around 800~ file loads for this to occur, 640mb only the last I think 5 minutes is really relavant

https://www.mediafire.com/file/m3l8pnevgd0g47n/2023-08-08_18-28-30.mkv/file


v537, 2023/08/08 17:53:11: hydrus client started
v537, 2023/08/08 17:53:12: booting controller…
v537, 2023/08/08 17:53:12: booting db…
v537, 2023/08/08 17:53:12: Found and deleted the durable temporary database on boot. The last exit was probably not clean.
v537, 2023/08/08 17:53:24: checking database
v537, 2023/08/08 17:53:31: preparing db caches
v537, 2023/08/08 17:53:31: initialising managers
v537, 2023/08/08 17:53:32: booting gui…
v537, 2023/08/08 17:53:33: starting services…
v537, 2023/08/08 17:53:33: Running "client api" on port 45869.
v537, 2023/08/08 17:53:33: services started
v537, 2023/08/08 17:59:15: You have 300 pages open! You can only open a few more before program stability is affected! Please close some now!
v537, 2023/08/08 18:10:03: Your session weight is 26,301,791, which is pretty big! To keep your UI lag-free, please try to close some pages or clear some finished downloaders!
v537, 2023/08/08 18:11:29: Failed to refresh account for read-only art file repository:
v537, 2023/08/08 18:11:29: Download cancelled: This hydrus service (hydrus service: read-only art file repository) could not do work because: ValidationException("Service has had a recent error or is otherwise not functional! You might like to try refreshing its account in 'review services'. Specific error was: Could not connect! - next request in 13 hours 53 minutes")
v537, 2023/08/08 18:11:30: Failed to refresh account for read-only art file repository1:
v537, 2023/08/08 18:11:30: Download cancelled: This hydrus service (hydrus service: read-only art file repository1) could not do work because: ValidationException("Service has had a recent error or is otherwise not functional! You might like to try refreshing its account in 'review services'. Specific error was: Could not connect! - next request in 13 hours 53 minutes")
v537, 2023/08/08 18:34:31: [MPV error] main: Too many events queued.

v537, 2023/08/08 18:34:35: [MPV error] main: Too many events queued.

**Comment by Ylevo** [comment]
Got the same issue here with mpv on 536. It crashes after around 5 to 20 in preview, even if I wait a while before each of them.
I thought the Qt Media Player would be my saviour so I installed from source, but hydrus freezes with the audio ongoing after a while. Windows 10 here too. I also tried the wasapi audio fix and it didn't change anything. Same issue with videos with no audio in fact.

It didn't used to crash like that at all in the past, a shame I can't remember when it started doing it. It makes hydrus for video formats completely unusable for me.

**Comment by alidan** [comment]
For me its never not crashed, but this is the first time that I got any feedback on what the crash is, and it's somewhat consistent in what causes the crash. 

before it was just program shut down with no indication of what happened, now, I have an indication just no idea if its the same problem. it has so far crashed across 2 gpus, 1 amd and 1 nvidia, across every version since mpv was introduced, and across 2 oses and with a 'clean' install. 

for me, even crashing, it working with audio is SO much more important than just seeing the video that even if it crashes, I get more done, it just comes down to restarting the program more often when I do start to parse video. would be nice if the crashing was a solved issue, but at least for me, as imperfect as it is, its still not a deal breaker.

**Comment by Ylevo** [comment]
Little update to say that after upgrading to 552a, the issue has completely disappeared for me. Don't ask me why.
