### ISSUE TITLE
Deleting an inc/dec service borks many things

### ISSUE THREAD

**Issue by AngusThermo-Pyle** [hydrusnetwork/hydrus#1357]
### Hydrus version

524

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Running from source

### Bug description and reproduction

Deleting an empty inc/dec service appears to leave references to the service data as well as the service key.  The service was row 16 is the database and generated the KeyError: 16 entry in the logging below.

There was also a line:

DataMissing: Service id error in database: key "7481f124ae52ae8eb0613b62e58d428a03cbe8edb4190d9638d37a9d84dfaec1" does not exist!

This allowed me to create a new inc/dec service and swap in the old service key to eliminate the errors for the time being.

### Log output

```text
File "c:\Hydrus Network\hydrus\core\HydrusThreading.py", line 401, in run
    callable( *args, **kwargs )
  File "c:\Hydrus Network\hydrus\client\gui\pages\ClientGUIManagement.py", line 5878, in THREADDoQuery
    more_media_results = controller.Read( 'media_results_from_ids', sub_query_hash_ids )
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Hydrus Network\hydrus\core\HydrusController.py", line 684, in Read
    return self._Read( action, *args, **kwargs )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Hydrus Network\hydrus\core\HydrusController.py", line 200, in _Read
    result = self.db.Read( action, *args, **kwargs )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Hydrus Network\hydrus\core\HydrusDB.py", line 919, in Read
    return job.GetResult()
           ^^^^^^^^^^^^^^^
  File "c:\Hydrus Network\hydrus\core\HydrusData.py", line 2069, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: KeyError: 16

Database Traceback (most recent call last):
  File "c:\Hydrus Network\hydrus\core\HydrusDB.py", line 602, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Hydrus Network\hydrus\client\db\ClientDB.py", line 6311, in _Read
    elif action == 'media_results_from_ids': result = self._GetMediaResults( *args, **kwargs )
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Hydrus Network\hydrus\client\db\ClientDB.py", line 3184, in _GetMediaResults
    service_keys_to_ratings = { service_ids_to_service_keys[ service_id ] : rating for ( service_id, rating ) in hash_ids_to_local_ratings[ hash_id ] }
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Hydrus Network\hydrus\client\db\ClientDB.py", line 3184, in <dictcomp>
    service_keys_to_ratings = { service_ids_to_service_keys[ service_id ] : rating for ( service_id, rating ) in hash_ids_to_local_ratings[ hash_id ] }
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^~
KeyError: 16
```

**Comment by Tumbolisu** [comment]
I got the same problem. I'm a new Hydrus user, so I wanted to see what an inc/dec rating service does. After trying it out on one image, I came to the conclusion that I don't need it and deleted the service. (I also tried using the other rating services and deleted all but one.) Next time I launched Hydrus my archive became inaccessible, spitting out the same error but with a KeyError of 15.

@AngusThermo-Pyle While I am a programmer, I do not have much experience with databases. And as I mentioned earlier, I'm new to Hydrus. What are the steps you took to eliminate the errors so I can do it myself too? I didn't see any mention of a hash popping up anywhere, am I just screwed?

Traceback:
```
v524, win32, frozen
DBException
KeyError: 15
Traceback (most recent call last):
  File "hydrus\core\HydrusThreading.py", line 427, in run
    callable( *args, **kwargs )
  File "hydrus\client\gui\pages\ClientGUIManagement.py", line 5881, in THREADDoQuery
    more_media_results = controller.Read( 'media_results_from_ids', sub_query_hash_ids )
  File "hydrus\core\HydrusController.py", line 685, in Read
    return self._Read( action, *args, **kwargs )
  File "hydrus\core\HydrusController.py", line 201, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "hydrus\core\HydrusDB.py", line 921, in Read
    return job.GetResult()
  File "hydrus\core\HydrusData.py", line 1488, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: KeyError: 15
Database Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 604, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 6313, in _Read
    elif action == 'media_results_from_ids': result = self._GetMediaResults( *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 3186, in _GetMediaResults
    service_keys_to_ratings = { service_ids_to_service_keys[ service_id ] : rating for ( service_id, rating ) in hash_ids_to_local_ratings[ hash_id ] }
  File "hydrus\client\db\ClientDB.py", line 3186, in <dictcomp>
    service_keys_to_ratings = { service_ids_to_service_keys[ service_id ] : rating for ( service_id, rating ) in hash_ids_to_local_ratings[ hash_id ] }
KeyError: 15


Database Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 604, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 6313, in _Read
    elif action == 'media_results_from_ids': result = self._GetMediaResults( *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 3186, in _GetMediaResults
    service_keys_to_ratings = { service_ids_to_service_keys[ service_id ] : rating for ( service_id, rating ) in hash_ids_to_local_ratings[ hash_id ] }
  File "hydrus\client\db\ClientDB.py", line 3186, in <dictcomp>
    service_keys_to_ratings = { service_ids_to_service_keys[ service_id ] : rating for ( service_id, rating ) in hash_ids_to_local_ratings[ hash_id ] }
KeyError: 15

```

**Comment by Tumbolisu** [comment]
Ok I managed to "fix" my archive with these steps:
1. Create a new inc/dec service in Hydrus. I used the same name as the one I originally deleted just to be safe.
2. Close Hydrus and open "client.db" in SQLiteStudio. (Thanks for the "how to see inside the db.txt" file!)
3. Go to "services" and change the ID of the new inc/dec service to 15. (Since that is the Key that is missing and causing errors.)

**Comment by hydrusnetwork** [comment]
Thank you for this report--I am very sorry, this slipped through testing completely!

I have fixed it so deleting an inc/dec service properly clears out old inc/dec rating numbers, so it won't happen again, and in the v524->525 update step, it will clear out any lingering numbers for anyone else affected by this.

If you or anyone else are interested in the simple line to fix this issue once it has happened, here it is:

`DELETE FROM local_incdec_ratings WHERE service_id NOT IN ( SELECT service_id FROM services );`

Let me know if you have any more trouble with it!
