### ISSUE TITLE
Hydrus crash on start, Date and/or Favourite Search Manager related(?)

### ISSUE THREAD

**Issue by schneckenschnabel** [hydrusnetwork/hydrus#1362]
### Hydrus version

v525a

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Running from source

### Install and OS comments

Fedora 36

### Bug description and reproduction

Starting Hydrus results in an error when he is trying to load the Favourite Search Manager stuff.

Logfile seems to say something about the "Favourite Search Manager" and/or a wrong/illegal date somewhere.

Just started happening today, didn't do anything yesterday and had a clean exit. So no idea where this is coming from.

Also I don't care about the fav searches so if there is a way to just nuke them and have hydrus start again that would be fine.

### Log output

```text
v525, 2023/05/01 11:52:30: hydrus client started
v525, 2023/05/01 11:52:31: booting controller…
v525, 2023/05/01 11:52:31: booting db…
v525, 2023/05/01 11:52:32: checking database
v525, 2023/05/01 11:52:32: preparing db caches
v525, 2023/05/01 11:52:32: initialising managers
v525, 2023/05/01 11:52:40: If the db crashed, another error may be written just above ^.
v525, 2023/05/01 11:52:40: A serious error occurred while trying to start the program. The error will be shown next in a window. More information may have been written to client.log.
v525, 2023/05/01 11:52:40: Traceback (most recent call last):
  File "/home/someuser/hydrus/hydrus/client/ClientController.py", line 2155, in THREADBootEverything
    self.InitModel()
  File "/home/someuser/hydrus/hydrus/client/ClientController.py", line 1186, in InitModel
    favourite_search_manager = self.Read( 'serialisable', HydrusSerialisable.SERIALISABLE_TYPE_FAVOURITE_SEARCH_MANAGER )
  File "/home/someuser/hydrus/hydrus/core/HydrusController.py", line 685, in Read
    return self._Read( action, *args, **kwargs )
  File "/home/someuser/hydrus/hydrus/core/HydrusController.py", line 201, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "/home/someuser/hydrus/hydrus/core/HydrusDB.py", line 921, in Read
    return job.GetResult()
  File "/home/someuser/hydrus/hydrus/core/HydrusData.py", line 1488, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: SerialisationException: Could not initialise this object of type Favourite Search Manager!
Database Traceback (most recent call last):
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 330, in InitialiseFromSerialisableInfo
    self._InitialiseFromSerialisableInfo( serialisable_info )
  File "/home/someuser/hydrus/hydrus/client/ClientSearch.py", line 972, in _InitialiseFromSerialisableInfo
    self._InitialiseTemporaryVariables()
  File "/home/someuser/hydrus/hydrus/client/ClientSearch.py", line 979, in _InitialiseTemporaryVariables
    self._system_predicates = FileSystemPredicates( system_predicates )
  File "/home/someuser/hydrus/hydrus/client/ClientSearch.py", line 456, in __init__
    dt = HydrusTime.CalendarDeltaToDateTime( years, months, days, hours )
  File "/home/someuser/hydrus/hydrus/core/HydrusTime.py", line 142, in CalendarDeltaToDateTime
    dayrange = calendar.monthrange( new_year, new_month )
  File "/usr/lib64/python3.10/calendar.py", line 126, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 0; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 330, in InitialiseFromSerialisableInfo
    self._InitialiseFromSerialisableInfo( serialisable_info )
  File "/home/someuser/hydrus/hydrus/client/ClientSearch.py", line 1309, in _InitialiseFromSerialisableInfo
    file_search_context = HydrusSerialisable.CreateFromSerialisableTuple( serialisable_file_search_context )
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 186, in CreateFromSerialisableTuple
    obj.InitialiseFromSerialisableInfo( version, serialisable_info, raise_error_on_future_version = raise_error_on_future_version )
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 340, in InitialiseFromSerialisableInfo
    raise HydrusExceptions.SerialisationException( 'Could not initialise this object of type {}!'.format( self.SERIALISABLE_NAME ) )
hydrus.core.HydrusExceptions.SerialisationException: Could not initialise this object of type File Search Context!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/someuser/hydrus/hydrus/core/HydrusDB.py", line 604, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "/home/someuser/hydrus/hydrus/client/db/ClientDB.py", line 6327, in _Read
    elif action == 'serialisable': result = self.modules_serialisable.GetJSONDump( *args, **kwargs )
  File "/home/someuser/hydrus/hydrus/client/db/ClientDBSerialisable.py", line 366, in GetJSONDump
    obj = HydrusSerialisable.CreateFromSerialisableTuple( ( dump_type, version, serialisable_info ) )
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 186, in CreateFromSerialisableTuple
    obj.InitialiseFromSerialisableInfo( version, serialisable_info, raise_error_on_future_version = raise_error_on_future_version )
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 340, in InitialiseFromSerialisableInfo
    raise HydrusExceptions.SerialisationException( 'Could not initialise this object of type {}!'.format( self.SERIALISABLE_NAME ) )
hydrus.core.HydrusExceptions.SerialisationException: Could not initialise this object of type Favourite Search Manager!


v525, 2023/05/01 11:52:40: boot error
v525, 2023/05/01 11:52:40: A serious error occurred while trying to start the program. The error will be shown next in a window. More information may have been written to client.log.
v525, 2023/05/01 11:52:42: boot error
v525, 2023/05/01 11:52:42: Traceback (most recent call last):
  File "/home/someuser/hydrus/hydrus/client/ClientController.py", line 2155, in THREADBootEverything
    self.InitModel()
  File "/home/someuser/hydrus/hydrus/client/ClientController.py", line 1186, in InitModel
    favourite_search_manager = self.Read( 'serialisable', HydrusSerialisable.SERIALISABLE_TYPE_FAVOURITE_SEARCH_MANAGER )
  File "/home/someuser/hydrus/hydrus/core/HydrusController.py", line 685, in Read
    return self._Read( action, *args, **kwargs )
  File "/home/someuser/hydrus/hydrus/core/HydrusController.py", line 201, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "/home/someuser/hydrus/hydrus/core/HydrusDB.py", line 921, in Read
    return job.GetResult()
  File "/home/someuser/hydrus/hydrus/core/HydrusData.py", line 1488, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: SerialisationException: Could not initialise this object of type Favourite Search Manager!
Database Traceback (most recent call last):
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 330, in InitialiseFromSerialisableInfo
    self._InitialiseFromSerialisableInfo( serialisable_info )
  File "/home/someuser/hydrus/hydrus/client/ClientSearch.py", line 972, in _InitialiseFromSerialisableInfo
    self._InitialiseTemporaryVariables()
  File "/home/someuser/hydrus/hydrus/client/ClientSearch.py", line 979, in _InitialiseTemporaryVariables
    self._system_predicates = FileSystemPredicates( system_predicates )
  File "/home/someuser/hydrus/hydrus/client/ClientSearch.py", line 456, in __init__
    dt = HydrusTime.CalendarDeltaToDateTime( years, months, days, hours )
  File "/home/someuser/hydrus/hydrus/core/HydrusTime.py", line 142, in CalendarDeltaToDateTime
    dayrange = calendar.monthrange( new_year, new_month )
  File "/usr/lib64/python3.10/calendar.py", line 126, in monthrange
    raise IllegalMonthError(month)
calendar.IllegalMonthError: bad month number 0; must be 1-12

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 330, in InitialiseFromSerialisableInfo
    self._InitialiseFromSerialisableInfo( serialisable_info )
  File "/home/someuser/hydrus/hydrus/client/ClientSearch.py", line 1309, in _InitialiseFromSerialisableInfo
    file_search_context = HydrusSerialisable.CreateFromSerialisableTuple( serialisable_file_search_context )
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 186, in CreateFromSerialisableTuple
    obj.InitialiseFromSerialisableInfo( version, serialisable_info, raise_error_on_future_version = raise_error_on_future_version )
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 340, in InitialiseFromSerialisableInfo
    raise HydrusExceptions.SerialisationException( 'Could not initialise this object of type {}!'.format( self.SERIALISABLE_NAME ) )
hydrus.core.HydrusExceptions.SerialisationException: Could not initialise this object of type File Search Context!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/someuser/hydrus/hydrus/core/HydrusDB.py", line 604, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "/home/someuser/hydrus/hydrus/client/db/ClientDB.py", line 6327, in _Read
    elif action == 'serialisable': result = self.modules_serialisable.GetJSONDump( *args, **kwargs )
  File "/home/someuser/hydrus/hydrus/client/db/ClientDBSerialisable.py", line 366, in GetJSONDump
    obj = HydrusSerialisable.CreateFromSerialisableTuple( ( dump_type, version, serialisable_info ) )
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 186, in CreateFromSerialisableTuple
    obj.InitialiseFromSerialisableInfo( version, serialisable_info, raise_error_on_future_version = raise_error_on_future_version )
  File "/home/someuser/hydrus/hydrus/core/HydrusSerialisable.py", line 340, in InitialiseFromSerialisableInfo
    raise HydrusExceptions.SerialisationException( 'Could not initialise this object of type {}!'.format( self.SERIALISABLE_NAME ) )
hydrus.core.HydrusExceptions.SerialisationException: Could not initialise this object of type Favourite Search Manager!


v525, 2023/05/01 11:52:44: doing fast shutdown…
v525, 2023/05/01 11:52:44: shutting down controller…
v525, 2023/05/01 11:52:44: hydrus client shut down
```

**Comment by hydrusnetwork** [comment]
Hey, I am very sorry for this! Thank you for the report. I messed up some month-subtraction logic in my new date-calculating code, and an awkward date predicate in your favourite searches triggered it here when it needed to do some date math on load.

I have fixed this for tomorrow's release. You don't have to do anything special--just update to v526 and it should just work again. Please let me know if you have any more trouble!
