### ISSUE TITLE
PyQt5 and PySide2 did not import

### ISSUE THREAD

**Issue by kinescou** [hydrusnetwork/hydrus#1395]
### Hydrus version

v534

### Qt major version

Qt 5

### Operating system

Linux (specify distro and version in comments)

### Install method

Running from source

### Install and OS comments

Fedora Linux 38 (KDE Plasma) x86_64
Python 3.11.4
Qt 5.15.10
Running from source using easy scripts

Note: Looking online for this error: https://forum.qt.io/topic/144843/pyside2-shiboken2-support-for-python-3-11
It seems that Fedora's Qt version (5.15.10) does not support pyside2. I'm not sure how relevant this is.

### Bug description and reproduction

1. Running from source using ./setup_venv.sh
2. Installation process runs with error (see first half of log)
3. Running ./hydrus_client.sh results in crash (see second half of log)

### Log output

```text
Environment setup

Collecting QtPy==2.2.1 (from -r static/requirements/advanced/requirements_qt5.txt (line 1))
  Using cached QtPy-2.2.1-py3-none-any.whl (82 kB)
ERROR: Ignored the following versions that require a different python version: 5.14.0 
Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.9; 5.14.1 
Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.9; 5.14.2 
Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.9; 5.14.2.1 
Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.9; 5.14.2.2 
Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.9; 5.14.2.3 
Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.9; 5.15.0 
Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.9; 5.15.1 
Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.10; 5.15.2 
Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.10; 5.15.2.1 
Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, <3.11
ERROR: Could not find a version that satisfies the requirement PySide2==5.15.2.1 (from versions: 0.0.0a1, 5.11.0, 5.11.1, 5.11.2, 5.12.0, 5.12.1, 5.12.2, 5.12.3, 5.12.4, 5.12.5, 5.12.6, 5.13.0, 5.13.1, 5.13.2)
ERROR: No matching distribution found for PySide2==5.15.2.1

-------------------------------------------------------------------------------------------------
Running it

Traceback (most recent call last):
  File "/home/user/hydrus/hydrus/client/gui/QtInit.py", line 116, in <module>
    import qtpy
ModuleNotFoundError: No module named 'qtpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/hydrus/hydrus/hydrus_client_boot.py", line 24, in <module>
    from hydrus.client.gui import QtInit
  File "/home/user/hydrus/hydrus/client/gui/QtInit.py", line 134, in <module>
    raise Exception( message )
Exception: Either the qtpy module was not found, or qtpy could not find a Qt to use!

Are you sure you installed and activated your venv correctly? Check the 'running from source' section of the help if you are confused!

Here is info on QT_API:
QT_API was initially not set. Currently QT_API is not set. FORCE_QT_API is not set.

Here is info on your available Qt Libraries:
PyQt5 did not import ok:
Traceback (most recent call last):
  File "/home/user/hydrus/hydrus/client/gui/QtInit.py", line 116, in <module>
    import qtpy
ModuleNotFoundError: No module named 'qtpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/hydrus/hydrus/client/gui/QtInitImportTest.py", line 11, in get_qt_library_str_status
    import PyQt5
ModuleNotFoundError: No module named 'PyQt5'

PySide2 did not import ok:
Traceback (most recent call last):
  File "/home/user/hydrus/hydrus/client/gui/QtInit.py", line 116, in <module>
    import qtpy
ModuleNotFoundError: No module named 'qtpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/hydrus/hydrus/client/gui/QtInitImportTest.py", line 22, in get_qt_library_str_status
    import PySide2
ModuleNotFoundError: No module named 'PySide2'

PyQt6 did not import ok:
Traceback (most recent call last):
  File "/home/user/hydrus/hydrus/client/gui/QtInit.py", line 116, in <module>
    import qtpy
ModuleNotFoundError: No module named 'qtpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/hydrus/hydrus/client/gui/QtInitImportTest.py", line 33, in get_qt_library_str_status
    import PyQt6
ModuleNotFoundError: No module named 'PyQt6'

PySide6 did not import ok:
Traceback (most recent call last):
  File "/home/user/hydrus/hydrus/client/gui/QtInit.py", line 116, in <module>
    import qtpy
ModuleNotFoundError: No module named 'qtpy'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/hydrus/hydrus/client/gui/QtInitImportTest.py", line 44, in get_qt_library_str_status
    import PySide6
ModuleNotFoundError: No module named 'PySide6'
```

**Comment by hydrusnetwork** [comment]
Damn, it looks like time has moved on and we may have run into a tricky wall here. I believe the exact problem is that my requirements.txt asks for PySide2 5.15.2.1, but that requires python <3.10. Since your Fedora has 3.11, it therefore cannot find a version of PySide2 5.15.2.1 to install that'll run.

PySide2 (Qt5) is offered as a legacy support option for people running older OSes like Windows 7. Please run the setup_venv script again and select 6 for Qt(6), which will install PySide6 instead. If you absolutely need Qt5, then you'll want to install your venv manually from the command line, as here:

https://hydrusnetwork.github.io/hydrus/running_from_source.html#what_you_need

You might be able to find a newer version of PySide2 that runs on Python 3.11, or PyQt5, or with some special trickery you could set up a venv with Python 3.9. Easiest answer though is just to use the modern Qt with a modern OS.
