### ISSUE TITLE
Client API request failure on /add_tags/add_tags

### ISSUE THREAD

**Issue by staff0rd** [hydrusnetwork/hydrus#1401]
### Hydrus version

534

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Extract

### Bug description and reproduction

1. Start Client API
2. Get an access key
3. Find a `file_id`
4. Tag the `file_id` with the following api request:

```
POST {{host}}/add_tags/add_tags
Hydrus-Client-API-Access-Key:{{access_key}}
Content-Type: application/json
{
    "file_id": 13199,
    "service_keys_to_actions_to_tags": {
        "6c6f63616c2074616773":{
            "0": ["my-tag"]
        }
    }
}
```
See failure result below:

### Log output

```text
The repository encountered an error it could not handle! Here is a dump of what happened, which will also be written to your client.log file. If it persists, please forward it to hydrus.admin@gmail.com:

Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
    
  File "threading.py", line 917, in run
    
  File "twisted\_threads\_threadworker.py", line 47, in work
    
  File "twisted\_threads\_team.py", line 182, in doWork
    
--- <exception caught here> ---
  File "twisted\python\threadpool.py", line 244, in inContext
    
  File "twisted\python\threadpool.py", line 260, in <lambda>
    
  File "twisted\python\context.py", line 117, in callWithContext
    
  File "twisted\python\context.py", line 82, in callWithContext
    
  File "hydrus\client\networking\ClientLocalServerResources.py", line 1925, in _threadDoPOSTJob
    
  File "hydrus\client\networking\ClientLocalServerResources.py", line 727, in ParseHashes
    
  File "hydrus\client\networking\ClientLocalServerResources.py", line 118, in CheckHashLength
    
builtins.TypeError: object of type 'int' has no len()
```

**Comment by hydrusnetwork** [comment]
Thank you for this report and the fix, sorry for the trouble!
