### ISSUE TITLE
Hydrus v535 won't start

### ISSUE THREAD

**Issue by CatPlanet** [hydrusnetwork/hydrus#1406]
### Hydrus version

v535

### Qt major version

Qt 5

### Operating system

Windows other (specify in comments)

### Install method

Running from source

### Install and OS comments

Windows 7, installed from source, after setup_venv
Python 3.8.16
mpv 0.35.0-221-ga40958cd
sqlite 3.41.2.0

### Bug description and reproduction

1. update from v533 -> v535
2. setup_venv
3. client-user
4. ???
5. no profit

### Log output

```text
v535, 2023/07/20 14:32:25: hydrus client started
v535, 2023/07/20 14:32:26: hydrus client failed
v535, 2023/07/20 14:32:26: Traceback (most recent call last):
  File "C:\Hydrus Network 2\hydrus\hydrus_client_boot.py", line 244, in boot
    from hydrus.client import ClientController
  File "C:\Hydrus Network 2\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Hydrus Network 2\hydrus\client\ClientController.py", line 33, in <module>
    from hydrus.client import ClientDownloading
  File "C:\Hydrus Network 2\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Hydrus Network 2\hydrus\client\ClientDownloading.py", line 14, in <module>
    from hydrus.client.importing import ClientImportFiles
  File "C:\Hydrus Network 2\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Hydrus Network 2\hydrus\client\importing\ClientImportFiles.py", line 6, in <module>
    from hydrus.core import HydrusFileHandling
  File "C:\Hydrus Network 2\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Hydrus Network 2\hydrus\core\HydrusFileHandling.py", line 8, in <module>
    from hydrus.core import HydrusSVGHandling
  File "C:\Hydrus Network 2\venv\Lib\site-packages\shiboken2\files.dir\shibokensupport\__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "C:\Hydrus Network 2\hydrus\core\HydrusSVGHandling.py", line 27, in <module>
    def GenerateThumbnailBytesFromSVGPath(path: str, target_resolution: tuple[int, int], clip_rect = None) -> bytes:
TypeError: 'type' object is not subscriptable

v535, 2023/07/20 14:32:26: hydrus client shut down
```

**Comment by CatPlanet** [comment]
on side note upgrading to v534 works perfectly

**Comment by thatfuckingbird** [comment]
I think it might be that tuple[int, int] thing, don't know what Python version added that syntax but apperantly it was 3.9 or 3.10. I would try updating Python. Workaround is to remove the `: tuple[int, int]` from that line, though if there are other similar uses those will have to be patched too.

**Comment by CatPlanet** [comment]
JFYI the last python for Windows 7 (with actuall installer) is 3.8.10 (3.8.17 with compile-it-yourself-nerd method)
3.9.x and above are no-go

**Comment by thatfuckingbird** [comment]
Yea, then for now that workaround remains I wrote above (it's safe because it does not change the meaning of the code, these annotations are only to help with development). And devman will have to change this back to the older syntax if 3.8 is still meant to be supported.

**Comment by floogulinc** [comment]
If you update your source to the latest `HydrusSVGHandling.py` is optional and you just won't have SVG support when it fails to load.

**Comment by CatPlanet** [comment]
@floogulinc If you mean latest `HydrusSVGHandling.py` as in from `284126e` commit then I'm afraid it crashes the whole Hydrus even before splash screen shows up, it isn't optional in that sense.
Also yes, I'm aware of https://github.com/NulAsh/cpython and https://github.com/adang1345/PythonWin7 projects. I'll use them if I have to, for time being I want to let dev know that, as it is, v535 kills "vanilla" support for Windows 7.

**Comment by floogulinc** [comment]
> @floogulinc If you mean latest `HydrusSVGHandling.py` as in from `284126e` commit then I'm afraid it crashes the whole Hydrus even before splash screen shows up, it isn't optional in that sense. 

I meant 4333baa, the latest commit on `master`.
