### ISSUE TITLE
Some exif-scanning failed to schedule! This is not super important...

### ISSUE THREAD

**Issue by ZacTheHac** [hydrusnetwork/hydrus#1414]
### Hydrus version

536

### Qt major version

Qt 6

### Operating system

Windows 11

### Install method

Extract

### Install and OS comments

Windows 10
Just upgraded from 533 to 536
I extract from zip into my folder, overwriting files as needed (last clean install was probably 527)

### Bug description and reproduction

1. Start client after updating
2. client asks if it should scan for old pngs with exif data
3. say yes
4. error as soon as main GUI loads.

- checking "file maintenance" window shows that the job "determine if the file has EXIF metadata" has 43,586 scheduled jobs.
- there are 43,576 PNGs in my client, so it would seem that they were likely all scheduled successfully?
- (the "No random potential duplicates were found." in the log happens when I select a group of files and mark them all as alternates or unrelated all at once, then cause the page to try to load a random group from the now empty list of potential duplicates. Just a quirk of processing duplicates outside of the duplicate filter. The count never updates until I hit refresh.)

### Log output

```text
v533, 2023/07/26 03:18:59: hydrus\client\ClientStrings.py:246: FutureWarning: Possible nested set at position 12
v533, 2023/07/26 03:18:59: hydrus\client\ClientStrings.py:246: FutureWarning: Possible nested set at position 72
v533, 2023/07/26 03:44:13: No random potential duplicates were found. Try refreshing the count, and if this keeps happening, please let hydrus_dev know.
v533, 2023/07/26 19:34:30: database maintenance - analyzing

done!
v533, 2023/07/26 20:52:43: Physically deleted 9 files and 9 thumbnails from file storage.
v533, 2023/07/26 21:52:44: Physically deleted 6 files and 6 thumbnails from file storage.
v533, 2023/07/26 23:40:33: saving and hiding gui…
v533, 2023/07/26 23:41:43: shutting down gui…
v533, 2023/07/26 23:41:43: waiting for managers to exit
v533, 2023/07/26 23:41:45: waiting for workers to exit
v533, 2023/07/26 23:41:45: waiting for idle shutdown work
v533, 2023/07/26 23:41:45: waiting for services to exit
v533, 2023/07/26 23:41:45: stopping services…
v533, 2023/07/26 23:41:45: shutting down db…
v533, 2023/07/26 23:41:45: saving and exiting objects
v533, 2023/07/26 23:43:26: cleaning up…
v533, 2023/07/26 23:43:27: shutting down controller…
v533, 2023/07/26 23:43:27: hydrus client shut down
v536, 2023/07/27 00:25:50: hydrus client started
v536, 2023/07/27 00:25:51: booting controller…
v536, 2023/07/27 00:25:51: booting db…
v536, 2023/07/27 00:25:51: checking database
v536, 2023/07/27 00:25:53: updating db to v534
v536, 2023/07/27 00:26:27: 
v536, 2023/07/27 00:26:27: Exception:
v536, 2023/07/27 00:26:27: AttributeError: 'Controller' object has no attribute 'files_maintenance_manager'

Traceback (most recent call last):
  File "hydrus\client\db\ClientDB.py", line 9508, in _UpdateDB
  File "hydrus\client\db\ClientDBFilesMaintenanceQueue.py", line 45, in AddJobs
AttributeError: 'Controller' object has no attribute 'files_maintenance_manager'


  File "threading.py", line 937, in _bootstrap
  File "threading.py", line 980, in _bootstrap_inner
  File "hydrus\core\HydrusThreading.py", line 427, in run
  File "hydrus\client\ClientController.py", line 2184, in THREADBootEverything
  File "hydrus\client\ClientController.py", line 1016, in InitModel
  File "hydrus\core\HydrusController.py", line 564, in InitModel
  File "hydrus\client\ClientController.py", line 228, in _InitDB
  File "hydrus\client\db\ClientDB.py", line 245, in __init__
  File "hydrus\core\HydrusDB.py", line 267, in __init__
  File "hydrus\client\db\ClientDB.py", line 9513, in _UpdateDB
  File "hydrus\core\HydrusData.py", line 872, in PrintException
  File "hydrus\core\HydrusData.py", line 901, in PrintExceptionTuple

v536, 2023/07/27 00:26:28: updated db to v534
v536, 2023/07/27 00:26:30: updating db to v535
v536, 2023/07/27 00:26:30: updated db to v535
v536, 2023/07/27 00:26:32: updating db to v536
v536, 2023/07/27 00:27:18: updated db to v536
v536, 2023/07/27 00:27:39: preparing db caches
v536, 2023/07/27 00:27:39: initialising managers
v536, 2023/07/27 00:27:46: booting gui…
v536, 2023/07/27 00:27:46: starting services…
v536, 2023/07/27 00:27:46: The client has updated to version 536!
v536, 2023/07/27 00:27:46: Some exif-scanning failed to schedule! This is not super important, but hydev would be interested in seeing the error that was printed to the log.
v536, 2023/07/27 00:27:47: Running "Client API" on port 45869.
v536, 2023/07/27 00:27:47: services started
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. There is nothing to worry about here; it is some bit rot from a recent change. Nothing was broken here, and in fact the job ran exactly as desired. Just the last final reporting line got messed up. All fixed for tomorrow.
