### ISSUE TITLE
URLs with "[" but no "]" cannot be added: "Invalid IPv6 URL"

### ISSUE THREAD

**Issue by pozieuto** [hydrusnetwork/hydrus#1444]
### Hydrus version

544

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

Trying to add any URL to a file that has a [ left square bracket but no ] right square bracket fails with "Invalid IPv6 URL".

### Log output

```text
v544, 2023/09/23 19:24:19: Clipboard Error!
I was expecting: Lines of URLs
Content received (9B):
file://[

v544, 2023/09/23 19:24:19: 
v544, 2023/09/23 19:24:19: Exception:
v544, 2023/09/23 19:24:19: URLClassException: Invalid IPv6 URL

Traceback (most recent call last):
  File "hydrus\client\networking\ClientNetworkingFunctions.py", line 448, in ParseURL
  File "urllib\parse.py", line 392, in urlparse
  File "urllib\parse.py", line 483, in urlsplit
ValueError: Invalid IPv6 URL

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydrus\client\gui\ClientGUIScrolledPanelsManagement.py", line 4822, in _Paste
  File "hydrus\client\gui\ClientGUIScrolledPanelsManagement.py", line 4770, in _EnterURL
  File "hydrus\client\networking\ClientNetworkingDomain.py", line 1514, in NormaliseURL
  File "hydrus\client\networking\ClientNetworkingDomain.py", line 302, in _GetURLClass
  File "hydrus\client\networking\ClientNetworkingFunctions.py", line 280, in ConvertURLIntoSecondLevelDomain
  File "hydrus\client\networking\ClientNetworkingFunctions.py", line 262, in ConvertURLIntoDomain
  File "hydrus\client\networking\ClientNetworkingFunctions.py", line 452, in ParseURL
hydrus.core.HydrusExceptions.URLClassException: Invalid IPv6 URL


  File "hydrus_client.pyw", line 11, in <module>
  File "hydrus\hydrus_client_boot.py", line 248, in boot
  File "hydrus\client\ClientController.py", line 1668, in Run
  File "hydrus\client\gui\pages\ClientGUIResults.py", line 3463, in mouseReleaseEvent
  File "hydrus\client\gui\pages\ClientGUIResults.py", line 4377, in ShowMenu
  File "hydrus\client\gui\ClientGUICore.py", line 73, in PopupMenu
  File "qtpy\QtWidgets.py", line 54, in <lambda>
  File "hydrus\client\gui\ClientGUIMenus.py", line 271, in event_callable
  File "hydrus\client\gui\pages\ClientGUIResults.py", line 1125, in _ManageURLs
  File "hydrus\client\gui\widgets\ClientGUICommon.py", line 285, in EventButton
  File "hydrus\client\gui\ClientGUIScrolledPanelsManagement.py", line 4828, in _Paste
  File "hydrus\client\gui\ClientGUIFunctions.py", line 394, in PresentClipboardParseError
  File "hydrus\core\HydrusData.py", line 872, in PrintException
  File "hydrus\core\HydrusData.py", line 901, in PrintExceptionTuple
```

**Comment by floogulinc** [comment]
According to [RFC 3986](http://www.ietf.org/rfc/rfc3986.txt) square brackets are reserved for IPv6 addresses and that's the only place they're valid in a URI. The should be percent encoded when used anywhere else. Can you give and example of one of these you've ran into that are failing?

**Comment by pozieuto** [comment]
A minimal example is in the log above: I always use `file://` URLs to archive filenames (using a tag namespace like `filename:` discards capitalization information, which I need to preserve when I encounter filenames with Base64-encoded data). My understanding was that Hydrus skips running parsing / validation functions on URLs with the `file` scheme in specific, so this behaviour was unexpected.

**Comment by floogulinc** [comment]
File URIs are still URIs and should be valid. You can percent encoded characters that are not allowed like the square brackets. I think any library that generates file URIs should do this for you. `[` is replaced by `%5B` and `]` replaced by `%5D`.

**Comment by hydrusnetwork** [comment]
Sorry for catching up to this late. I have made the 'manage URLs' dialog handle invalid URLs more flexibly--if you try to import something that doesn't parse, it says 'I don't recommend this, but do you want to add it anyway?', and you can force it. Note that there are other places in the program that'll hide invalid URLs (we've had bad imports before, so I think the system is ok/safe to store basically any string), but by the sounds of it you don't need to interact with these in UI too much, just store them.

Whether a URL should or shouldn't have [ or [] in it is beyond my paygrade, I'm afraid. I mostly just toss things at the python url parsing library and accept what it gives me. I also treat 'file://' URIs basically the same as http(s) atm. I'd like to have better recognition of the file schema in future, including even actual imports via 'file://', but there's some other work I have to do first.

I can see the URL system eventually evolving to a 'known locations/names' storage, and perhaps known good filenames would have a place here. I haven't thought about it fully though.
