### ISSUE TITLE
[Linux] migrating failes because hydrus does not create destination folders (or there is a missing slash)

### ISSUE THREAD

**Issue by bigretromike** [hydrusnetwork/hydrus#1484]
### Hydrus version

v551

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Extract

### Install and OS comments

Debian 12, Xfce

### Bug description and reproduction

0. install requirement dependency
1. open fresh install
2. add same access key to admin/tag/storage server
3. sync them
4. try to migrate media file location inside your home directory (add /home/brm/Applications/hydrus_data/) and hit migrate now.
5. Error files are not moved

Looks like hydrus is 

### Log output

```text
v551, linux, frozen
DBException
Exception: Cannot directory-merge "/home/brm/Applications/hydrus/db/client_files/f64" to "/home/brm/Applications/hydrus_data/f64"--the destination is not a directory!
Traceback (most recent call last):
  File "hydrus/core/HydrusThreading.py", line 427, in run
  File "hydrus/client/ClientFiles.py", line 1686, in Rebalance
  File "hydrus/core/HydrusController.py", line 965, in WriteSynchronous
  File "hydrus/core/HydrusController.py", line 245, in _Write
  File "hydrus/core/HydrusDB.py", line 926, in Write
  File "hydrus/core/HydrusData.py", line 1512, in GetResult
hydrus.core.HydrusExceptions.DBException: Exception: Cannot directory-merge "/home/brm/Applications/hydrus/db/client_files/f64" to "/home/brm/Applications/hydrus_data/f64"--the destination is not a directory!
Database Traceback (most recent call last):
  File "hydrus/core/HydrusDB.py", line 584, in _ProcessJob
  File "hydrus/client/db/ClientDB.py", line 10394, in _Write
  File "hydrus/client/db/ClientDBFilesPhysicalStorage.py", line 189, in RelocateClientFiles
  File "hydrus/core/HydrusPaths.py", line 570, in MergeTree
Exception: Cannot directory-merge "/home/brm/Applications/hydrus/db/client_files/f64" to "/home/brm/Applications/hydrus_data/f64"--the destination is not a directory!


Database Traceback (most recent call last):
  File "hydrus/core/HydrusDB.py", line 584, in _ProcessJob
  File "hydrus/client/db/ClientDB.py", line 10394, in _Write
  File "hydrus/client/db/ClientDBFilesPhysicalStorage.py", line 189, in RelocateClientFiles
  File "hydrus/core/HydrusPaths.py", line 570, in MergeTree
Exception: Cannot directory-merge "/home/brm/Applications/hydrus/db/client_files/f64" to "/home/brm/Applications/hydrus_data/f64"--the destination is not a directory!
```

When I create f64 in destination folder, hyrus move files from src to dst and then error popup about next folder.
```

**Comment by thatfuckingbird** [comment]
should be  fixed in v552a

**Comment by bigretromike** [comment]
@thatfuckingbird yes, it is fixed in v552a. Sorry I didn't checked it sooner. Thanks for quick respond.
