### ISSUE TITLE
Cannot update from v546 to v559.

### ISSUE THREAD

**Issue by C1rn0-9** [hydrusnetwork/hydrus#1512]
### Hydrus version

v546

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

1. Install update.
2. Start Hydrus.

Fresh install (delete all except db) not helping either.

### Log output

```text
v559, 2024/01/21 18:49:11: hydrus client started
v559, 2024/01/21 18:49:12: booting controller…
v559, 2024/01/21 18:49:12: booting db…
v559, 2024/01/21 18:49:12: Found and deleted the durable temporary database on boot. The last exit was probably not clean.
v559, 2024/01/21 18:49:12: checking database
v559, 2024/01/21 18:49:14: updating db to v548
v559, 2024/01/21 18:49:14: [[[41, 3, [2, 4, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 46]], [[0, "simple_data"], [0, null]]]]]]], [[41, 3, [2, 4, 0, [3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 46]], [[0, "simple_data"], [0, null]]]]]]], [[41, 3, [2, 3, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 46]], [[0, "simple_data"], [0, null]]]]]]], [[41, 3, [2, 3, 0, [3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 46]], [[0, "simple_data"], [0, null]]]]]]], [[41, 3, [2, 28, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 47]], [[0, "simple_data"], [0, null]]]]]]], [[41, 3, [2, 13, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [0, 0]]]]]]]], [[41, 3, [2, 13, 0, [3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [0, 0]]]]]]]], [[41, 3, [2, 13, 0, [2]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [0, 1]]]]]]]], [[41, 3, [2, 13, 0, [2, 3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [0, 1]]]]]]]], [[41, 3, [2, 14, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [1, 0]]]]]]]], [[41, 3, [2, 14, 0, [3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [1, 0]]]]]]]], [[41, 3, [2, 14, 0, [2]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [1, 1]]]]]]]], [[41, 3, [2, 14, 0, [2, 3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [1, 1]]]]]]]], [[41, 3, [2, 11, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [2, 0]]]]]]]], [[41, 3, [2, 11, 0, [3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [2, 0]]]]]]]], [[41, 3, [2, 11, 0, [2]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [2, 1]]]]]]]], [[41, 3, [2, 11, 0, [2, 3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [2, 1]]]]]]]], [[41, 3, [2, 12, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [3, 0]]]]]]]], [[41, 3, [2, 12, 0, [3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [3, 0]]]]]]]], [[41, 3, [2, 12, 0, [2]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [3, 1]]]]]]]], [[41, 3, [2, 12, 0, [2, 3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [3, 1]]]]]]]], [[41, 3, [2, 9, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [4, 0]]]]]]]], [[41, 3, [2, 9, 0, [3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [4, 0]]]]]]]], [[41, 3, [2, 9, 0, [2]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [4, 1]]]]]]]], [[41, 3, [2, 9, 0, [2, 3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [4, 1]]]]]]]], [[41, 3, [2, 10, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [5, 0]]]]]]]], [[41, 3, [2, 10, 0, [3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [5, 0]]]]]]]], [[41, 3, [2, 10, 0, [2]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [5, 1]]]]]]]], [[41, 3, [2, 10, 0, [2, 3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [5, 1]]]]]]]], [[41, 3, [2, 15, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [6, 0]]]]]]]], [[41, 3, [2, 15, 0, [3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [6, 0]]]]]]]], [[41, 3, [2, 15, 0, [2]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [6, 1]]]]]]]], [[41, 3, [2, 15, 0, [2, 3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [6, 1]]]]]]]], [[41, 3, [2, 16, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [7, 0]]]]]]]], [[41, 3, [2, 16, 0, [3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [7, 0]]]]]]]], [[41, 3, [2, 16, 0, [2]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [7, 1]]]]]]]], [[41, 3, [2, 16, 0, [2, 3]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 148]], [[0, "simple_data"], [0, [7, 1]]]]]]]], [[41, 3, [0, 97, 0, [0]]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 149]], [[0, "simple_data"], [2, [126, 1, [0, null]]]]]]]]], [[41, 3, [2, 6, 0, []]], [42, 5, [0, [21, 2, [[[0, "simple_action"], [0, 149]], [[0, "simple_data"], [2, [126, 1, [2, null]]]]]]]]]]
v559, 2024/01/21 18:49:14: Had a problem saving a JSON object. The dump has been printed to the log.
v559, 2024/01/21 18:49:14: Dump had length 4.66 KB!
v559, 2024/01/21 18:49:14: If the db crashed, another error may be written just above ^.
v559, 2024/01/21 18:49:14: A serious error occurred while trying to start the program. The error will be shown next in a window. More information may have been written to client.log.
v559, 2024/01/21 18:49:14: Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 266, in __init__
  File "hydrus\client\db\ClientDB.py", line 9830, in _UpdateDB
  File "hydrus\client\db\ClientDBSerialisable.py", line 747, in SetJSONDump
  File "hydrus\core\HydrusDBBase.py", line 289, in _Execute
sqlite3.OperationalError: table json_dumps_named has no column named timestamp_ms

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydrus\client\ClientController.py", line 2212, in THREADBootEverything
  File "hydrus\client\ClientController.py", line 1003, in InitModel
  File "hydrus\core\HydrusController.py", line 588, in InitModel
  File "hydrus\client\ClientController.py", line 207, in _InitDB
  File "hydrus\client\db\ClientDB.py", line 239, in __init__
  File "hydrus\core\HydrusDB.py", line 287, in __init__
Exception: Updating the client db to version 548 caused this error:

Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 266, in __init__
  File "hydrus\client\db\ClientDB.py", line 9830, in _UpdateDB
  File "hydrus\client\db\ClientDBSerialisable.py", line 747, in SetJSONDump
  File "hydrus\core\HydrusDBBase.py", line 289, in _Execute
sqlite3.OperationalError: table json_dumps_named has no column named timestamp_ms


v559, 2024/01/21 18:49:14: boot error
v559, 2024/01/21 18:49:14: A serious error occurred while trying to start the program. The error will be shown next in a window. More information may have been written to client.log.
v559, 2024/01/21 18:49:18: boot error
v559, 2024/01/21 18:49:18: Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 266, in __init__
  File "hydrus\client\db\ClientDB.py", line 9830, in _UpdateDB
  File "hydrus\client\db\ClientDBSerialisable.py", line 747, in SetJSONDump
  File "hydrus\core\HydrusDBBase.py", line 289, in _Execute
sqlite3.OperationalError: table json_dumps_named has no column named timestamp_ms

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydrus\client\ClientController.py", line 2212, in THREADBootEverything
  File "hydrus\client\ClientController.py", line 1003, in InitModel
  File "hydrus\core\HydrusController.py", line 588, in InitModel
  File "hydrus\client\ClientController.py", line 207, in _InitDB
  File "hydrus\client\db\ClientDB.py", line 239, in __init__
  File "hydrus\core\HydrusDB.py", line 287, in __init__
Exception: Updating the client db to version 548 caused this error:

Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 266, in __init__
  File "hydrus\client\db\ClientDB.py", line 9830, in _UpdateDB
  File "hydrus\client\db\ClientDBSerialisable.py", line 747, in SetJSONDump
  File "hydrus\core\HydrusDBBase.py", line 289, in _Execute
sqlite3.OperationalError: table json_dumps_named has no column named timestamp_ms


v559, 2024/01/21 18:49:46: doing fast shutdown…
v559, 2024/01/21 18:49:46: shutting down gui…
v559, 2024/01/21 18:49:46: shutting down db…
v559, 2024/01/21 18:49:46: saving and exiting objects
v559, 2024/01/21 18:49:46: cleaning up…
v559, 2024/01/21 18:49:46: shutting down controller…
v559, 2024/01/21 18:49:46: hydrus client shut down
```

**Comment by floogulinc** [comment]
Try updating to v558 and then update to v559 and as always backup your DB beforehand.

**Comment by C1rn0-9** [comment]
It helped, thanks.

**Comment by hydrusnetwork** [comment]
Thank you for making this report, and sorry for the trouble. I will also write a version check into v561 so people in future are told what to do explicitly.
