### ISSUE TITLE
Danbooru url import fails if file is already in the database

### ISSUE THREAD

**Issue by PorchettaMan** [hydrusnetwork/hydrus#1516]
### Hydrus version

v560 Hotfix

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### Bug description and reproduction

1. Import any image that is also available on Danbooru, either manually or from a different site
2. Import the image's Danbooru page url
3. What should happen: Hydrus recognizes the file is already in the database, and still downloads tags, urls, and other information
4. What happens: import fails with the following error

I am not 100% sure it's a Danbooru only issue, but it's the only site I've managed to trigger this behavior with  (e.g. testing using the same image and a Gelbooru url works fine).

### Log output

```text
TypeError("ContentUpdatePackage.AddContentUpdate() missing 1 required positional argument: 'content_update'")… (Copy note to see full error)
Traceback (most recent call last):
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1523, in WorkOnURL
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 738, in DownloadAndImportRawFile
    def GetExampleNetworkJob( self, network_job_factory ):
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1005, in Import
  File "hydrus\client\importing\ClientImportFiles.py", line 244, in DoWork
    HydrusImageHandling.ConvertToPNGIfBMP( self._temp_path )
  File "hydrus\client\importing\ClientImportFiles.py", line 555, in PubsubContentUpdates
TypeError: ContentUpdatePackage.AddContentUpdate() missing 1 required positional argument: 'content_update'
```

**Comment by PorchettaMan** [comment]
Works again in v561. I'm guessing this is what this point in the changelog was about.

> - fixed another stupid content update typo that was causing 'already in db' results to not get metadata updates

Thanks for the fix.
