### ISSUE TITLE
Copy/Pasting Timestamps Doesn't Work

### ISSUE THREAD

**Issue by Tumbolisu** [hydrusnetwork/hydrus#1520]
### Hydrus version

561

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### To reproduce the issue:

1. Open the "manage times" dialogue for any file.
2. Edit any of the times, such as "file modified time" or a web domain time.
3. Click "Copy timestamp to the clipboard."
4. Click "Paste timestamp from another datetime widget."
5. A window titled "Clipboard Error!" appears.

### The Error reads:

> Sorry, I could not understand what was in the clipboard. I was expecting "A simple integer timestamp" but recieved this text:
> 1640948400
> More details have been written to the log, but the general error was:
> Exception('Not a timestamp!')

### Investigation:
The timestamp is clearly copied correctly. The problem is with the parser. Looking at the log reveals that the timestamp is expected to be surrounded by double quote characters. So, I pasted the timestamp into a text editor, surrounded it with double quotes, and then copied that. Clicking the paste button then worked perfectly fine!

### Suggestion:
Adjust the parser to allow both timestamps that are just an integer and timestamps that are an integer surrounded by double quote characters. Or get rid of the double quote thing entirely. What's even up with that?

### Log output

```text
v561, 2024-02-11 16:02:43: Clipboard Error!
I was expecting: A simple integer timestamp
Content received (10B):
1640948400
v561, 2024-02-11 16:02:43: 
================ Exception ================
Exception: Not a timestamp!
================ Traceback ================
Traceback (most recent call last):
  File "hydrus\client\gui\ClientGUITime.py", line 846, in _Paste
    if self._monthly_allowed:
Exception: Not a timestamp!
================== Stack ==================
  File "hydrus_client.pyw", line 11, in <module>
  File "hydrus\hydrus_client_boot.py", line 215, in boot
  File "hydrus\client\ClientController.py", line 1717, in Run
  File "hydrus\client\gui\ClientGUIShortcuts.py", line 1465, in eventFilter
  File "hydrus\client\gui\ClientGUIShortcuts.py", line 1403, in _ProcessShortcut
  File "hydrus\client\gui\pages\ClientGUIResults.py", line 3756, in ProcessApplicationCommand
  File "hydrus\client\gui\pages\ClientGUIResults.py", line 2493, in ProcessApplicationCommand
    ( thumbnail_span_width, thumbnail_span_height ) = self._GetThumbnailSpanDimensions()
  File "hydrus\client\gui\pages\ClientGUIResults.py", line 1184, in _ManageTimestamps
    path = client_files_manager.GetFilePath( hash, mime )
  File "hydrus\client\gui\ClientGUIMediaActions.py", line 190, in EditFileTimestamps
  File "hydrus\client\gui\widgets\ClientGUICommon.py", line 285, in EventButton
  File "hydrus\client\gui\ClientGUITime.py", line 619, in _EditDateTime
    self._monthly_allowed = monthly_allowed
  File "hydrus\client\gui\widgets\ClientGUICommon.py", line 250, in EventButton
  File "hydrus\client\gui\ClientGUITime.py", line 864, in _Paste
  File "hydrus\client\gui\ClientGUIFunctions.py", line 401, in PresentClipboardParseError
  File "hydrus\core\HydrusData.py", line 932, in PrintException
    record_string += str( me.create_time() )
  File "hydrus\core\HydrusData.py", line 963, in PrintExceptionTuple
    if not me.startswith( '"' ):
=================== End ===================
v561, 2024-02-11 16:02:43: Clipboard Error!
v561, 2024-02-11 16:02:43: Sorry, I could not understand what was in the clipboard. I was expecting "A simple integer timestamp" but received this text:

1640948400

More details have been written to the log, but the general error was:

Exception('Not a timestamp!')
```

**Comment by Charsy89** [comment]
In my case, just adding the decimals for milliseconds works fine. E.g. 1640948400 -> 1640948400.000.
It would be nice if Hydrus would fill in missing decimals as .000, though.

**Comment by Tumbolisu** [comment]
Speaking of, the copy button should include the actual number of milliseconds.

**Comment by hydrusnetwork** [comment]
Thank you for this report! It was a stupid typo from the big rewrite. Fixed for tomorrow, and it has milliseconds now. Let me know if you have any more trouble with it!
