### ISSUE TITLE
MacOS videos stopped working after migrating db

### ISSUE THREAD

**Issue by 66363633** [hydrusnetwork/hydrus#1534]
### Hydrus version

566

### Qt major version

Qt 6

### Operating system

macOS other (specify in comments)

### Install method

Installer

### Install and OS comments

OS: macOS 14.3.1 Sonoma (Apple silicon)

### Bug description and reproduction

Videos stopped working as intended after migrating db from Windows to macOS — now Hydrus shows thumbnails and says "open webm externally"/"open mp4 externally" and such popups appear:

```
v566, 2024-03-28 10:24:57: MPV is not available!
v566, 2024-03-28 10:30:45: The macOS App does not come with MPV support on its own, but if your system has the dev library, libmpv1, it will try to import it. It seems your system does not have this, or it failed to import. The specific error follows:
v566, 2024-03-28 10:30:45: Traceback (most recent call last):
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/gui/canvas/ClientGUIMPV.py", line 32, in <module>
    import mpv
  File "/Applications/Hydrus Network.app/Contents/MacOS/lib/mpv.py", line 53, in <module>
    raise OSError("Cannot find libmpv in the usual places. Depending on your distro, you may try installing an "
OSError: Cannot find libmpv in the usual places. Depending on your distro, you may try installing an mpv-devel or mpv-libs package. If you have libmpv around but this script can't find it, consult the documentation for ctypes.util.find_library which this script uses to look up the library filename.
```

Before migration videos worked correctly.
Migration was done by copying .db files and 'client_files' folder directly in the default database location. Clear reinstalls, loading up new empty db and updating/reinstalling mpv haven't resolved the issue

**Comment by floogulinc** [comment]
It's a known issue that mpv doesn't work on macOS.
