### ISSUE TITLE
Client crash on startup: "ModuleNotFoundError: No module named 'cv2'"

### ISSUE THREAD

**Issue by kchousos** [hydrusnetwork/hydrus#1567]
### Hydrus version

v578

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Running from source

### Install and OS comments

Running on Fedora 40. Cloned the repo and run `./setup_venv.sh`.

### Bug description and reproduction

Choosing the advanced install, whatever combination of options I choose I still get the segfault at startup.

### Log output

```text
❯ ./hydrus_client.sh
~/Bin/Repos/hydrus ~/Bin/Repos/hydrus
./hydrus_client.sh: line 28: 735560 Segmentation fault      (core dumped) python hydrus_client.py "$@"
~/Bin/Repos/hydrus

-------------------------------------------------------------------------------------------

❯ python hydrus_client.py
v578, 2024-06-15 02:25:21: hydrus client started
v578, 2024-06-15 02:25:21: hydrus client failed
v578, 2024-06-15 02:25:21: Traceback (most recent call last):
  File "/home/kchou/Bin/Repos/hydrus/hydrus/hydrus_client_boot.py", line 211, in boot
    from hydrus.client import ClientController
  File "/home/kchou/Bin/Repos/hydrus/hydrus/client/ClientController.py", line 27, in <module>
    from hydrus.client import ClientDaemons
  File "/home/kchou/Bin/Repos/hydrus/hydrus/client/ClientDaemons.py", line 9, in <module>
    from hydrus.client.metadata import ClientContentUpdates
  File "/home/kchou/Bin/Repos/hydrus/hydrus/client/metadata/ClientContentUpdates.py", line 11, in <module>
    from hydrus.client import ClientGlobals as CG
  File "/home/kchou/Bin/Repos/hydrus/hydrus/client/ClientGlobals.py", line 3, in <module>
    from hydrus.client.interfaces import ClientControllerInterface
  File "/home/kchou/Bin/Repos/hydrus/hydrus/client/interfaces/ClientControllerInterface.py", line 7, in <module>
    from hydrus.client import ClientThreading
  File "/home/kchou/Bin/Repos/hydrus/hydrus/client/ClientThreading.py", line 13, in <module>
    from hydrus.client.gui import QtPorting as QP
  File "/home/kchou/Bin/Repos/hydrus/hydrus/client/gui/QtPorting.py", line 25, in <module>
    from hydrus.client.gui import ClientGUIFunctions
  File "/home/kchou/Bin/Repos/hydrus/hydrus/client/gui/ClientGUIFunctions.py", line 15, in <module>
    from hydrus.core.files.images import HydrusImageNormalisation
  File "/home/kchou/Bin/Repos/hydrus/hydrus/core/files/images/HydrusImageNormalisation.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

v578, 2024-06-15 02:25:21: hydrus client shut down
```

**Comment by hydrusnetwork** [comment]
Hey I am sorry for the trouble. It looks like the setup_venv script had trouble finding 'OpenCV' (the `cv2`). Can you try running it again and search/scroll through the logging output as it installs things for `opencv-python-headless`? Is there info there about it not being able to find a certain version for your python? You'll often get a long string a bit like this:

```
ERROR: Ignored the following versions that require a different python version: 6.0.0 Requires-Python >=3.6, <3.10; 6.0.0a1.dev1606911628 Requires-Python >=3.6, <3.10; 6.0.1 Requires-Python >=3.6, <3.10; 6.0.2 Requires-Python >=3.6, <3.10; 6.0.3 Requires-Python >=3.6, <3.10; 6.0.4 Requires-Python >=3.6, <3.10; 6.1.0 Requires-Python >=3.6, <3.10; 6.1.1 Requires-Python >=3.6, <3.10; 6.1.2 Requires-Python >=3.6, <3.10; 6.1.3 Requires-Python >=3.6, <3.10; 6.2.0 Requires-Python >=3.6, <3.11; 6.2.1 Requires-Python >=3.6, <3.11; 6.2.2 Requires-Python >=3.6, <3.11; 6.2.2.1 Requires-Python >=3.6, <3.11; 6.2.3 Requires-Python >=3.6, <3.11; 6.2.4 Requires-Python >=3.6, <3.11; 6.3.0 Requires-Python <3.11,>=3.6; 6.3.1 Requires-Python <3.11,>=3.6; 6.3.2 Requires-Python <3.11,>=3.6; 6.4.0 Requires-Python <3.11,>=3.6; 6.4.0.1 Requires-Python <3.12,>=3.7; 6.4.1 Requires-Python <3.12,>=3.7; 6.4.2 Requires-Python <3.12,>=3.7; 6.4.3 Requires-Python <3.12,>=3.7; 6.5.0 Requires-Python <3.12,>=3.7; 6.5.1 Requires-Python <3.12,>=3.7; 6.5.1.1 Requires-Python <3.12,>=3.7; 6.5.2 Requires-Python <3.12,>=3.7; 6.5.3 Requires-Python <3.12,>=3.7
ERROR: Could not find a version that satisfies the requirement PySide6==6.4.1 (from versions: 6.6.0, 6.6.1, 6.6.2, 6.6.3, 6.6.3.1, 6.7.0)
ERROR: No matching distribution found for PySide6==6.4.
```

Also, if you put your terminal in your base install directory and enter this, what do you get?

```
source venv/bin/activate
pip list
pip show opencv-python-headless
```

Ideally you should get quite a long list of all your installed modules (as opposed to just like two things), and the 'show' line might show some useful info about OpenCV but given your error here it will probably say 'not found'.

You might also like to do this:
```
source venv/bin/activate (if you aren't still in the previous session)
pip install opencv-python-headless==4.5.3.56
pip install opencv-python-headless==4.8.1.78
pip install opencv-python-headless==4.9.0.80
```

Those are the different versions of OpenCV the setup script tries to go for, but if we do it separately and manually in a terminal like this, we'll get a better look at the different(?) error messages you are getting.

**Comment by kchousos** [comment]
This is the output for `pip list` and `pip show opencv-python-headless`:

```
❯ pip list
Package                Version
---------------------- ------------
aggdraw                1.3.18.post0
attrs                  23.2.0
Automat                22.10.0
beautifulsoup4         4.12.3
cbor2                  5.6.4
certifi                2024.6.2
cffi                   1.16.0
chardet                5.2.0
charset-normalizer     3.3.2
cloudscraper           1.2.71
constantly             23.10.4
cryptography           42.0.8
dateparser             1.2.0
docopt                 0.6.2
html5lib               1.1
hyperlink              21.0.0
idna                   3.7
imageio                2.34.1
incremental            22.10.0
lazy_loader            0.4
lxml                   5.2.2
lz4                    4.3.3
mpv                    1.0.6
networkx               3.3
numpy                  2.0.0
olefile                0.47
opencv-python-headless 4.9.0.80
packaging              24.1
pillow                 10.3.0
pillow_heif            0.16.0
pip                    24.0
psd-tools              1.9.33
psutil                 5.9.8
pyasn1                 0.6.0
pyasn1_modules         0.4.0
pycparser              2.22
Pympler                1.0.1
pyOpenSSL              24.1.0
pyparsing              3.1.2
PySide6                6.6.0
PySide6-Addons         6.6.0
PySide6-Essentials     6.6.0
PySocks                1.7.1
python-dateutil        2.9.0.post0
pytz                   2024.1
pyxdg                  0.28
PyYAML                 6.0.1
QtPy                   2.4.1
regex                  2024.5.15
requests               2.31.0
requests-toolbelt      1.0.0
scikit-image           0.23.2
scipy                  1.13.1
Send2Trash             1.8.3
service-identity       24.1.0
setuptools             69.1.1
shiboken6              6.6.0
show-in-file-manager   1.1.5
six                    1.16.0
soupsieve              2.5
tifffile               2024.5.22
Twisted                24.3.0
typing_extensions      4.12.2
tzlocal                5.2
urllib3                2.2.2
webencodings           0.5.1
wheel                  0.43.0
zope.interface         6.4.post2
hydrus on  master [!] via 🐍 v3.12.3 (venv)                                                                                                                                        
❯ pip show opencv-python-headless
Name: opencv-python-headless
Version: 4.9.0.80
Summary: Wrapper package for OpenCV python bindings.
Home-page: https://github.com/opencv/opencv-python
Author: 
Author-email: 
License: Apache 2.0
Location: /home/kchou/Bin/Repos/hydrus/venv/lib64/python3.12/site-packages
Requires: numpy, numpy, numpy, numpy, numpy, numpy
Required-by: 
hydrus on  master [!] via 🐍 v3.12.3 (venv)                                                                                                                                        
❯ 
```

Now, even though I try to setup the venv the same way, the error I get is this:

```
❯ ./hydrus_client.sh
~/Bin/Repos/hydrus ~/Bin/Repos/hydrus

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/home/kchou/Bin/Repos/hydrus/hydrus_client.py", line 7, in <module>
    from hydrus import hydrus_client_boot
  File "/home/kchou/Bin/Repos/hydrus/hydrus/hydrus_client_boot.py", line 24, in <module>
    from hydrus.client.gui import QtInit
  File "/home/kchou/Bin/Repos/hydrus/hydrus/client/gui/QtInit.py", line 27, in <module>
    import PySide6 # Qt6
  File "/home/kchou/Bin/Repos/hydrus/venv/lib64/python3.12/site-packages/PySide6/__init__.py", line 124, in <module>
    _setupQtDirectories()
  File "/home/kchou/Bin/Repos/hydrus/venv/lib64/python3.12/site-packages/PySide6/__init__.py", line 64, in _setupQtDirectories
    from shiboken6 import Shiboken
  File "/home/kchou/Bin/Repos/hydrus/venv/lib64/python3.12/site-packages/shiboken6/__init__.py", line 27, in <module>
    from shiboken6.Shiboken import *
./hydrus_client.sh: line 28: 771050 Segmentation fault      (core dumped) python hydrus_client.py "$@"
~/Bin/Repos/hydrus
```

**Comment by hydrusnetwork** [comment]
Thank you, how interesting. I did not know there was a new version of numpy. I wonder if that is causing our issues with OpenCV, although now I look it seems like it just came out yesterday: https://pypi.org/project/numpy/#history, so I do not think it is totally related to your original issue, but it will give me other issues to fix, which I will do for v579.

Please now try this:

```
source venv/bin/activate
pip install numpy==1.26.4
python
import cv2
exit()
```
Any errors? It is super strange that you seemingly now have OpenCV available in your venv but hydrus was previously unable to import it. Or maybe something other than numpy changed in the past few days, and whatever was breaking for you a few days ago is also now fixed. So, let's try to reset numpy to that 1.26.4 functional old version and try booting hydrus again, and we'll see if everything magically works.

**Comment by kchousos** [comment]
I do not get any errors when importing cv2. I forgot to mention that the error of `./hydrus_client.sh` in my previous reply is when I use python3.10 for the venv. In this venv --- the python3.10 --- the solution of installing numpy==1.26.4 works! For now I'll just keep this venv and not bother with python3.12.

Thank you very much for your quick help and for your quality software. Have a great day!
