### ISSUE TITLE
Windows: Don't extract new versions over old ones.

### ISSUE THREAD

**Issue by Mooninaut** [hydrusnetwork/hydrus#162]
I have an older version of Python (2.7.9) installed on my Windows 7 x64 system.

I ran Hydrus v195 and it bombed out with the following crash log:

```
Traceback (most recent call last):
  File "<string>", line 24, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "include\ServerController.py", line 11, in <module>
    import ServerDaemons
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "include\ServerDaemons.py", line 9, in <module>
    import HydrusServer
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "include\HydrusServer.py", line 2, in <module>
    import HydrusServerResources
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "include\HydrusServerResources.py", line 13, in <module>
    from twisted.web.server import NOT_DONE_YET
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\twisted\web\server.py", line 36, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\twisted\web\util.py", line 304, in <module>
  File "site-packages\twisted\web\util.py", line 387, in FailureElement
  File "site-packages\twisted\web\template.py", line 401, in __init__
  File "site-packages\twisted\web\template.py", line 344, in _flatsaxParse
  File "xml\sax\__init__.py", line 93, in make_parser
SAXReaderNotAvailable: No parsers found
```

Clearly, Hydrus should be using its embedded Python libraries in preference to the system ones, at least on Windows.

**Comment by Mooninaut** [comment]
OK, well, now I'm confused. I uninstalled Python 2.7.9 and I'm getting the same error. ?_?

**Comment by Mooninaut** [comment]
Apparently my problem was following the directions and extracting the new version (195) over the old version (168). Deleting everything except the "db" folder and re-extracting 195 fixed it.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
