### ISSUE TITLE
TypeError: Parameters to generic types must be types.

### ISSUE THREAD

**Issue by chaskayote** [hydrusnetwork/hydrus#1630]
### Hydrus version

599

### Qt major version

Qt 6

### Operating system

macOS 12 "Monterey" (Apple silicon)

### Install method

Installer

### Install and OS comments

Model Name:	MacBook Pro
Model Identifier:	Mac15,9
Model Number:	MUW63LL/A
Chip:	Apple M3 Max
Total Number of Cores:	16 (12 performance and 4 efficiency)
Memory:	48 GB
System Firmware Version:	10151.101.3
OS Loader Version:	10151.101.3

### Bug description and reproduction

1. Updated from 598 to 599.
2. Launch application.
3. Closes quietly.

### Log output

```text
v599, 2024-11-21 00:36:39: hydrus client started
v599, 2024-11-21 00:36:40: hydrus client failed
v599, 2024-11-21 00:36:40: Traceback (most recent call last):
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/hydrus_client_boot.py", line 225, in boot
    from hydrus.client import ClientController
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/ClientController.py", line 34, in <module>
    from hydrus.client import ClientOptions
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/ClientOptions.py", line 15, in <module>
    from hydrus.client.duplicates import ClientDuplicates
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/duplicates/ClientDuplicates.py", line 23, in <module>
    from hydrus.client.media import ClientMediaFileFilter
  File "/Applications/Hydrus Network.app/Contents/MacOS/hydrus/client/media/ClientMediaFileFilter.py", line 487, in <module>
    def ReportDeleteLockFailures( media_results: typing.Collection[ ClientMedia.ClientMediaResult ] ):
  File "typing", line 312, in inner
    return func(*args, **kwds)
  File "typing", line 1143, in __getitem__
    params = tuple(_type_check(p, msg) for p in params)
  File "typing", line 1143, in <genexpr>
    params = tuple(_type_check(p, msg) for p in params)
  File "typing", line 176, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Parameters to generic types must be types. Got <module 'hydrus.client.media.ClientMediaResult' from '/Applications/Hydrus Network.app/Contents/MacO.

v599, 2024-11-21 00:36:40: hydrus client shut down
```

**Comment by hydrusnetwork** [comment]
Hey, I am very sorry for the trouble here. There was a typo that I thought only hit certain users who run from source, but it looks like the macOS App runs on that too.

Roll back to v598 if you have not already; this will be fixed in v600. I am improving my test situation to ensure this specific problem (it is an issue with python 3.10, which is a little older) will not happen again.

**Comment by chaskayote** [comment]
Okay, thanks! I did roll back to v598 and have no current issues. I just have to deal with the duplicates sidebar lol.
