### ISSUE TITLE
Attempting to download from e621.net gives a BadRequestException '400' error 

### ISSUE THREAD

**Issue by gabriel-cmf** [hydrusnetwork/hydrus#1631]
### Hydrus version

v599

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Extract

### Bug description and reproduction

Hello, After updating to v599, Hydrus will fail to download files from e621 and will give out an error, detailed in notes on the file log as:

> BadRequestException('400: <html>\r\n<head><title>400 Bad Request</title></head>\r\n<body>\r\n<center><h1>400 Bad Request</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n')… (Copy note to see full error)
Traceback (most recent call last):
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1661, in WorkOnURL
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 765, in DownloadAndImportRawFile
  File "hydrus\client\networking\ClientNetworkingJobs.py", line 2046, in WaitUntilDone
hydrus.core.HydrusExceptions.BadRequestException: 400: <html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>

This affects both the gallery downloader and the url importer.

I can download from other sites normally, and some of the downloader components of the e621 downloader are working correctly, so I don't know what's causing this.

**Comment by gabriel-cmf** [comment]
The issue was on my side, I configured the headers incorrectly
