### ISSUE TITLE
DLL load failed while importing QtGui

### ISSUE THREAD

**Issue by Raichu98** [hydrusnetwork/hydrus#1632]
### Hydrus version

Version 599

### Qt major version

Qt 6

### Operating system

Windows other (specify in comments)

### Install method

Running from source

### Bug description and reproduction

Hello
I was trying to install hydrus from souce since I only have Windows 8.1
Even though I ran into a few problems (git and my already installed python weren't on path and i had to put them manually) I still believed everything went well
Yet when I'm trying to do the final step of running the app, when i do it the cmd quickly opens and closes and this crash.log file appears on my desktop
Not sure where I went wrong. I searched for installing the Qt6 library pack to see if that makes it work (which seemed to had been installed correctly) yet that didn't seem to solve the issue.
Anyway I hope this can get solved :(

### Log output

```text
Critical boot error occurred! Details written to crash.log in either your db dir, userdir, or desktop!

DLL load failed while importing QtGui: No se puede encontrar el módulo especificado.

Traceback (most recent call last):
  File "C:\Users\Raichu\Documents\Hydrus\install_dir\hydrus\hydrus_client_boot.py", line 24, in <module>
    from hydrus.client.gui import QtInit
  File "C:\Users\Raichu\Documents\Hydrus\install_dir\hydrus\client\gui\QtInit.py", line 139, in <module>
    from qtpy import QtCore as QC
  File "C:\Users\Raichu\Documents\Hydrus\install_dir\venv\Lib\site-packages\qtpy\QtCore.py", line 134, in <module>
    from PySide6.QtGui import Qt as guiQt
ImportError: DLL load failed while importing QtGui: No se puede encontrar el módulo especificado.
```

**Comment by hydrusnetwork** [comment]
Hey, I am sorry for the trouble here. I hate to say it, but I think Windows 8.1 may simply be too old to run modern hydrus. I know for certain that Windows 7 crossed this line around v578, and the issues that hit 7 are not so different to 8.1.

For more background, please check out the recently added 'Windows 7' note under this section: https://hydrusnetwork.github.io/hydrus/running_from_source.html#walkthrough

I assume this is your first attempt to run hydrus, that you haven't been able to run, say, v597? If you can run v578 but not v580, then I have to assume that we have a similar obsolescence issue. When you run 'setup_venv.bat' in the older version, you will want to choose Qt5. I suspect your problem here is that Win 8.1 won't run Qt6. Modern versions of hydrus no longer support Qt5.

Let me know how you get on, and I will update the help.

**Comment by hydrusnetwork** [comment]
Closing this as I now truly no longer support Qt5. The help has been updated with info about which versions should work in legacy situations. Please re-open if this is still an issue and the help does not address it!
