### ISSUE TITLE
TypeError: PopulateFileSeedCacheMenu() missing 1 required positional argument: 'selected_file_seeds'

### ISSUE THREAD

**Issue by luckydonald** [hydrusnetwork/hydrus#1640]
### Hydrus version

v600

### Qt major version

Qt 6

### Operating system

Windows 10

### Install method

Installer

### Install and OS comments

![image](https://github.com/user-attachments/assets/ea7f6a41-4597-40d7-aeae-084c6cb54db8)

### Bug description and reproduction

It was running in the background. Probably subscription services. Alternatively API usage (browsing: files r, tag r/w, vote services r/w)

### Log output

```py
v600, win32, frozen
TypeError
PopulateFileSeedCacheMenu() missing 1 required positional argument: 'selected_file_seeds'
Traceback (most recent call last):
  File "hydrus\client\gui\QtPorting.py", line 1335, in eventFilter
    else:
          
  File "hydrus\client\gui\QtPorting.py", line 1305, in Execute
    return True
  File "hydrus\client\gui\lists\ClientGUIListCtrl.py", line 819, in _ShowRowsMenu
    def resizeEvent( self, event ):
                   ^^^^^^^^^^^^^^^^^
  File "hydrus\client\gui\pages\ClientGUIManagementPanels.py", line 1570, in _GetListCtrlMenu
TypeError: PopulateFileSeedCacheMenu() missing 1 required positional argument: 'selected_file_seeds'
```

**Comment by luckydonald** [comment]
```py
v600, win32, frozen
TypeError
PopulateFileSeedCacheMenu() missing 1 required positional argument: 'selected_file_seeds'
Traceback (most recent call last):
  File "hydrus\client\gui\QtPorting.py", line 1335, in eventFilter
    else:
          
  File "hydrus\client\gui\QtPorting.py", line 1305, in Execute
    return True
  File "hydrus\client\gui\lists\ClientGUIListCtrl.py", line 819, in _ShowRowsMenu
    def resizeEvent( self, event ):
                   ^^^^^^^^^^^^^^^^^
  File "hydrus\client\gui\pages\ClientGUIManagementPanels.py", line 1570, in _GetListCtrlMenu
TypeError: PopulateFileSeedCacheMenu() missing 1 required positional argument: 'selected_file_seeds'
```

**Comment by Zweibach** [comment]
Update Hydrus.

**Comment by luckydonald** [comment]
👍 

There the was nothing similar in the issue tracker, and v601 was released at the same time I was filling the issue.
Afterwards the changelog didn't mention anything related, so I wanted to write it down before I click away the notifications.
