### ISSUE TITLE
Linux clients older than 593 will not start

### ISSUE THREAD

**Issue by whispersilk** [hydrusnetwork/hydrus#1657]
### Hydrus version

<=592

### Qt major version

Qt 6

### Operating system

Linux (specify distro and version in comments)

### Install method

Extract

### Install and OS comments

Installed by extracting `Hydrus.Network.<version>.-.Linux.-.Executable.tar.zst` (`.tar.gz` for old versions) into an empty folder.

Running on OpenSureTumbleweed 20241218-0.

### Bug description and reproduction

I have a very old Hydrus library that I recently rediscovered on an old hard drive, which was created using Hydrus 400. I planned to go through the gradual upgrade process (400 to 427, to a clean install of 428, etc), but found that attempting to run `client` resulted in `ImportError: cannot import name '_imaging'`. I tried re-downloading from [the v400 tag](https://github.com/hydrusnetwork/hydrus/releases/tag/v400) into a clean folder to ensure that the old installation was not broken in some way, and the clean install would not start either.

As a sanity check, I downloaded and installed [v603](https://github.com/hydrusnetwork/hydrus/releases/tag/v603) and was able to confirm that it runs without issue. I bisected my way through old versions until I found the cutoff: [v593](https://github.com/hydrusnetwork/hydrus/releases/tag/v593) runs, while [v592](https://github.com/hydrusnetwork/hydrus/releases/tag/v592) fails with `ImportError: cannot import name '_imaging' from 'PIL'`.

I don't see anything in the v593 release notes that seems like it would be responsible for things suddenly beginning to work, but have not dug into the changes yet; I figured it was worth asking if anyone else knew what may be happening first.

### Log output

```text
Hydrus v592 (./hydrus_client):

v592, 2024-12-28 21:30:30: hydrus client started
v592, 2024-12-28 21:30:30: hydrus client failed
v592, 2024-12-28 21:30:30: Traceback (most recent call last):
  File "hydrus/hydrus_client_boot.py", line 222, in boot
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "hydrus/client/ClientController.py", line 29, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "hydrus/client/ClientDaemons.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "hydrus/client/metadata/ClientContentUpdates.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "hydrus/client/ClientGlobals.py", line 3, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "hydrus/client/interfaces/ClientControllerInterface.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "hydrus/client/ClientThreading.py", line 13, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "hydrus/client/gui/QtPorting.py", line 26, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "hydrus/client/gui/ClientGUIFunctions.py", line 15, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "hydrus/core/files/images/HydrusImageNormalisation.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "PIL/Image.py", line 100, in <module>
ImportError: cannot import name '_imaging' from 'PIL' (/home/test/Hydrus 592/PIL/__init__.pyc)

v592, 2024-12-28 21:30:30: hydrus client shut down

============================================================================

Hydrus v550 (./hydrus_client):

v550, 2024/12/28 21:31:10: hydrus client started
v550, 2024/12/28 21:31:11: hydrus client failed
v550, 2024/12/28 21:31:11: Traceback (most recent call last):
  File "hydrus/hydrus_client_boot.py", line 244, in boot
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "hydrus/client/ClientController.py", line 34, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "hydrus/client/ClientDownloading.py", line 14, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "hydrus/client/importing/ClientImportFiles.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "hydrus/core/HydrusPSDHandling.py", line 4, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "PIL/Image.py", line 82, in <module>
ImportError: cannot import name '_imaging' from 'PIL' (/home/test/Hydrus 550/PIL/__init__.pyc)

v550, 2024/12/28 21:31:11: hydrus client shut down

============================================================================

Hydrus v500 (./client):

v500, 2024/12/28 21:33:49: hydrus client started
v500, 2024/12/28 21:33:49: hydrus client failed
v500, 2024/12/28 21:33:49: Traceback (most recent call last):
  File "hydrus/hydrus_client.py", line 230, in boot
    from hydrus.client import ClientController
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "hydrus/client/ClientController.py", line 27, in <module>
    from hydrus.client import ClientCaches
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "hydrus/client/ClientCaches.py", line 9, in <module>
    from hydrus.core import HydrusImageHandling
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "hydrus/core/HydrusImageHandling.py", line 23, in <module>
    from PIL import _imaging
ImportError: cannot import name '_imaging' from 'PIL' (/home/test/Hydrus 500/PIL/__init__.pyc)

v500, 2024/12/28 21:33:49: hydrus client shut down

============================================================================

Hydrus v400 (./client):

2024/12/28 21:37:39: hydrus client started
2024/12/28 21:37:39: hydrus client failed
2024/12/28 21:37:39: Traceback (most recent call last):
  File "hydrus/client.py", line 176, in <module>
  File "/home/hydrus/Desktop/hydrus/hydrus/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "hydrus/hydrus/client/ClientController.py", line 16, in <module>
  File "/home/hydrus/Desktop/hydrus/hydrus/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "hydrus/hydrus/client/ClientCaches.py", line 9, in <module>
  File "/home/hydrus/Desktop/hydrus/hydrus/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "hydrus/hydrus/client/ClientFiles.py", line 11, in <module>
  File "/home/hydrus/Desktop/hydrus/hydrus/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "hydrus/hydrus/client/ClientImageHandling.py", line 12, in <module>
  File "/home/hydrus/Desktop/hydrus/hydrus/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
  File "hydrus/hydrus/core/HydrusImageHandling.py", line 21, in <module>
ImportError: cannot import name '_imaging'

2024/12/28 21:37:39: hydrus client shut down
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. Looking at the changelogs and commits, I think in v592 I rolled out the `requests` and `setuptools` library updates to 'running from source' users. `setuptools`, which does some package-finding stuff, is probably the pertinent thing here, and it was updated from 69.1.1 to 70.3.0. This test was then integrated into the main build for v593. In v594, the `PyInstaller` for Linux seems to be updated from 6.2 to 6.7, but this is probably beside the point since your cutoff is v592/v593.

Since we did not have any problems running the build at the time, my best guess here is that this is a new problem related to your newer OS version. I think Pyinstaller and setuptools are importing .so or .pyd files in the step that is failing. Now I think of it, the reason why I updated from 69.1.1 was because of a critical security issue (iirc, downloading modules via setuptools wasn't verifying https or something, although it was not urgent in our case because we do not use it for that). I suspect your OS has a strict block on 69.1.1 running for any reason, or some similar security policy on what setuptools/PyInstaller wants to do here, and thus the import isn't working. It could also just be some weird bug that 70.3.0 fixed.

What to do, then? I think you have three options:

- Find the esoteric permission setting in your OS that is stopping setuptools from working and temporarily disable it??!?
- If you have a Windows machine or can borrow one for a couple hours, do the update here over on that with the Windows extract builds, and then copy it back once you are >=v593. It all works the same as Linux and the databases are 100% portable. Just make sure you backup before you start.
- Look into setting up your own source venv but be careful to get v70.3.0 setuptools. This might be a pain to figure out, since my newer 'setup_venv.sh' scripts are nice but I bet the ones back in ~v400 are pretty rough, and you probably don't want to be editing requirements.txts yourself. I think you'd want to go here: https://hydrusnetwork.github.io/hydrus/running_from_source.html and do the normal easy current version (~v603) setup in a completely new folder on your desktop or something, which we can be confident your OS will be ok with. _Then_ you'll want to do some git magic like `git checkout tags/v421` to rewind the code (and which shouldn't touch the venv) and see if the older version will boot with a new venv. If old v421 will boot with new Qt6 and so on, then you'll be doing the normal update routine, but you'll be checking out newer and newer tag versions. I expect you've seen it, but the current fast and good master update route is:

204 > 238 > 246 > 291 > 328 > 335 (clean install) > 376 > 421 > 466 (clean install) > 474 > 480 > 521 (maybe clean install) > 527 (special clean install) > 535 > 558 > 571 (clean install)

But you can ignore the clean install instructions I'm pretty sure, since you are source code. It looks like you'll be running client.sh prior to v527, and hydrus_client.sh thereafter.

I am not a super Linux or git expert, but I can help with anything you find tricky. ChatGPT can probably walk you through most of it quicker than I can, too. Might be easier to source a copy of Windows though, or a Linux that's happy to run the older executable.

Let me know how it goes. It'd be nice to know if I can add v571->603 or whatever step to the master update route, too.

**Comment by whispersilk** [comment]
Thank you for the detailed response! I have a Windows virtual machine image that I can give access to the appropriate folders, so let me give that a try when I've got a spare hour or two later this week. Regardless of if I can get things working that way or if I have to do something more involved, I'll let you know how v571->v603 goes.

**Comment by whispersilk** [comment]
And done!

Here's what I did: I booted up my Windows virtual machine, mounting my Hydrus library as `H:`, and began the update process by downloading the "Windows - Extract Only" archive for each version in the update path. Everything was smooth sailing until the update from v480 to v521. I performed a clean install of v521, and when I ran client.exe I got the following error:
```
Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception: [WinError 87] The parameter is incorrect: 'H:pywin32_system32'

Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 111, in <module>
  File "PyInstaller\loader\pyimod04_pywin32.py", line 38, in install
  File "os.py", line 1111, in add_dll_directory
OSError: [WinError 87] The parameter is incorrect: 'H:pywin32_system32'

```
After encountering this error, I copied the contents of the Hydrus directory to a folder on `C:` (local to the virtual machine rather than shared from the host) and it worked! It looks like v521 and beyond expect to be in `C:` drive when running in Windows, and will complain if they are not.

But aside from that minor hiccup, I am now fully updated and have the library running in Linux under  v603. Thank you for being so helpful!

For upgrade-path reference, I did *not* perform a clean install from v571 to v603.

**Comment by hydrusnetwork** [comment]
Great, I am glad you are working again. This problem launching from non-C-drive is weird and worrying, and the first I have heard of it! I'm sorry to say that when I try an extract of v521 on an F: drive, it boots ok, and I know of several other users who run the windows build from USB sticks and stuff, so I wonder if this is something particular to your machine or OS version or any custom launch parameters(?) or something.

EDIT: Ah, I chased the pyinstaller code down--it looks like it was trying to join `sys._MEIPASS` to `pywin32_system32` foldername as a potential place to look for dlls and stuff, and then `os.py` threw a wobbler because obviously the path was messed up. `sys._MEIPASS` is set by pyinstaller when it boots and should just be the extract path. So like this should be something nice like `H:\Hydrus Network`, but in your 'H' case it was munged down to `H:`. The join operation is usually uncontroversial and doesn't do weird truncations, so this is an odd one. Maybe some crazy permission issue or folder unicode that threw pyinstaller off? Maybe a symlink?

If you are all updated ok now, it is probably a moot point, but let me know if you discover anything else about this.

**Comment by whispersilk** [comment]
I booted the virtual machine up  to test a suspicion, and it looks like the issue is actually to do with the specific way I set up my mounted `H:` drive.

When I was upgrading, I mounted `/some/path/Hydrus Library` as `H:`, so when I tried to run the client I was running `H:\hydrus_client.exe` rather than `H:\Hydrus Library\hydrus_client.exe`. When I tried extracting into a nested folder so that the executable was at `H:\_NESTED\hydrus_client.exe`, it worked.

So it appears that the truncation is happening because the "parent folder" of the executable was in fact the root of `H:` drive, and `sys._MEIPASS` was being set to `H:` rather than `H:\`.

Hope this helps and thank you for attempting to reproduce on your end as well and narrow down the specific problem!

**Comment by hydrusnetwork** [comment]
Interesting, thank you!
