### ISSUE TITLE
Crash on launch (database update issue)

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#171]
```
2016/05/05 03:01:24: Traceback (most recent call last):
2016/05/05 03:01:24:   File "/opt/hydrus/include/ClientController.py", line 1040, in THREADBootEverything
2016/05/05 03:01:24:     self.InitModel()
2016/05/05 03:01:24:   File "/opt/hydrus/include/ClientController.py", line 478, in InitModel
2016/05/05 03:01:24:     HydrusController.HydrusController.InitModel( self )
2016/05/05 03:01:24:   File "/opt/hydrus/include/HydrusController.py", line 184, in InitModel
2016/05/05 03:01:24:     self._db = self._InitDB()
2016/05/05 03:01:24:   File "/opt/hydrus/include/ClientController.py", line 59, in _InitDB
2016/05/05 03:01:24:     return ClientDB.DB( self, HC.DB_DIR, 'client', no_wal = self._no_wal )
2016/05/05 03:01:24:   File "/opt/hydrus/include/HydrusDB.py", line 240, in __init__
2016/05/05 03:01:24:     raise e
2016/05/05 03:01:24: Exception: Updating the client db to version 202 caused this error:
Traceback (most recent call last):
  File "/opt/hydrus/include/HydrusDB.py", line 221, in __init__
    self._UpdateDB( version )
  File "/opt/hydrus/include/ClientDB.py", line 7641, in _UpdateDB
    self._CacheSpecificMappingsGenerate( file_service_id, tag_service_id )
  File "/opt/hydrus/include/ClientDB.py", line 1738, in _CacheSpecificMappingsGenerate
    self._CacheSpecificMappingsAddFiles( file_service_id, tag_service_id, hash_ids )
  File "/opt/hydrus/include/ClientDB.py", line 1539, in _CacheSpecificMappingsAddFiles
    current_mapping_ids_raw = self._c.execute( 'SELECT namespace_id, tag_id, hash_id FROM ' + current_mappings_table_name + ' WHERE hash_id IN ' + splayed_group_of_hash_ids + ';' ).fetchall()
OperationalError: no such table: external_mappings.current_mappings_2
```

I don't know how old the database is, but I doubt it's more than 5 versions out of date.

Also, a message popped up saying the exception would be written to a log, but this only got output to the terminal and not the client.log file.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
