### ISSUE TITLE
OperationalError: no such table: current_mappings

### ISSUE THREAD

**Issue by SuperDoxin** [hydrusnetwork/hydrus#174]
when starting hydrus I get the following error:
![derp2](https://cloud.githubusercontent.com/assets/377239/15483054/1be44682-2133-11e6-9df6-e8bb4bbcfd8d.png)

sorry about it being an image, the dialog would not allow me to select the text.

the following is printed to stdout:

```
$ ./client
2016/05/23 22:07:54: hydrus client started
2016/05/23 22:07:54: booting controller...
2016/05/23 22:07:54: booting db...
2016/05/23 22:07:56: updating db to v204
2016/05/23 22:07:56: creating new mappings tables: 3
2016/05/23 22:07:56: A serious error occured while trying to start the program. Its traceback will be shown next. It should have also been written to client.log.
2016/05/23 22:07:56: Traceback (most recent call last):
2016/05/23 22:07:56:   File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientController", line 1043, in THREADBootEverything
2016/05/23 22:07:56:   File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientController", line 498, in InitModel
2016/05/23 22:07:56:   File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.HydrusController", line 184, in InitModel
2016/05/23 22:07:56:   File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientController", line 60, in _InitDB
2016/05/23 22:07:56:   File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.HydrusDB", line 240, in __init__
2016/05/23 22:07:56: Exception: Updating the client db to version 204 caused this error:
Traceback (most recent call last):
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.HydrusDB", line 221, in __init__
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientDB", line 8058, in _UpdateDB
OperationalError: no such table: current_mappings

Segmentation fault
```

I'm running on Debian Linux. I hope there's some way to recover my taggings, since the last backup I made is a couple months old.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
