### ISSUE TITLE
Can't update server past 200

### ISSUE THREAD

**Issue by ScoreUnder** [hydrusnetwork/hydrus#177]
It crashes with this error:

```
2016/05/29 17:18:57: Traceback (most recent call last):
  File "/opt/hydrus/server.py", line 63, in <module>
    controller.Run()
  File "/opt/hydrus/include/ServerController.py", line 363, in Run
    self.InitModel()
  File "/opt/hydrus/include/ServerController.py", line 311, in InitModel
    HydrusController.HydrusController.InitModel( self )
  File "/opt/hydrus/include/HydrusController.py", line 184, in InitModel
    self._db = self._InitDB()
  File "/opt/hydrus/include/ServerController.py", line 201, in _InitDB
    return ServerDB.DB( self, HC.DB_DIR, 'server', no_wal = self._no_wal )
  File "/opt/hydrus/include/HydrusDB.py", line 240, in __init__
    raise e
Exception: Updating the server db to version 201 caused this error:
Traceback (most recent call last):
  File "/opt/hydrus/include/HydrusDB.py", line 221, in __init__
    self._UpdateDB( version )
  File "/opt/hydrus/include/ServerDB.py", line 2528, in _UpdateDB
    self._c.execute( 'DROP INDEX mapping_petitions_service_id_account_id_reason_id_tag_id_index;' )
OperationalError: no such index: mapping_petitions_service_id_account_id_reason_id_tag_id_index
```

I had to fix it by taking that line out.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
