### ISSUE TITLE
Error loading client when hydrusnetwork folder is in Cryptomator mount

### ISSUE THREAD

**Issue by alisterpineda** [hydrusnetwork/hydrus#217]
If I have the install directory in my davfs mount folder, I would get the following errors:

```
2017/02/23 23:27:29: hydrus client started
(client:5053): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
(client:5053): Gtk-WARNING **: Unable to locate theme engine in module_path: "adwaita",
2017/02/23 23:27:29: booting controller...
2017/02/23 23:27:29: booting db...
2017/02/23 23:27:30: A serious error occured while trying to start the program. Its traceback will be shown next. It should have also been written to client.log.
2017/02/23 23:27:30: Traceback (most recent call last):
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientController", line 1167, in THREADBootEverything
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientController", line 530, in InitModel
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.HydrusController", line 203, in InitModel
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientController", line 64, in _InitDB
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.ClientDB", line 1054, in __init__
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.HydrusDB", line 205, in __init__
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.HydrusDB", line 341, in _InitDB
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.HydrusDB", line 376, in _InitDBCursor
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/include.HydrusDB", line 288, in _AttachExternalDatabases
OperationalError: disk I/O error
```

**Comment by ScoreUnder** [comment]
What happens if you open the database in something like SQLiteBrowser?

**Comment by alisterpineda** [comment]
Hmm interesting,

Everything is empty.
I also tried copying a an sqlite db file to the davfs folder. It shows empty on the SQLiteBrowser despite knowing there's data in there.

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
