### ISSUE TITLE
DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by Quartzic** [hydrusnetwork/hydrus#224]
This issue can be replicated by creating a brand new install of Hydrus and using the official tag repository. Once you have finished processing the data and restart Hydrus, you will receive a maintenance prompt. Press "Yes" to confirm it, then wait for it to finish. When you boot Hydrus up again, you will receive this error:

```
2017/07/21 09:16:39: Traceback (most recent call last):
  File "include\ClientController.py", line 1188, in THREADBootEverything
    self.InitModel()
  File "include\ClientController.py", line 582, in InitModel
    self._managers[ 'tag_siblings' ] = ClientCaches.TagSiblingsManager( self )
  File "include\ClientCaches.py", line 2549, in __init__
    self._RefreshSiblings()
  File "include\ClientCaches.py", line 2572, in _RefreshSiblings
    service_keys_to_statuses_to_pairs = self._controller.Read( 'tag_siblings' )
  File "include\HydrusController.py", line 318, in Read
    return self._Read( action, *args, **kwargs )
  File "include\HydrusController.py", line 99, in _Read
    result = self.db.Read( action, HC.HIGH_PRIORITY, *args, **kwargs )
  File "include\HydrusDB.py", line 836, in Read
    return job.GetResult()
  File "include\HydrusData.py", line 1725, in GetResult
    raise e
DBException: DatabaseError: database disk image is malformed

Database Traceback (most recent call last):
  File "include\HydrusDB.py", line 521, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "include\ClientDB.py", line 7877, in _Read
    elif action == 'tag_siblings': result = self._GetTagSiblings( *args, **kwargs )
  File "include\ClientDB.py", line 6035, in _GetTagSiblings
    statuses_to_pairs = HydrusData.BuildKeyToSetDict( ( ( status, ( self._GetTag( bad_tag_id ), self._GetTag( good_tag_id ) ) ) for ( status, bad_tag_id, good_tag_id ) in statuses_and_pair_ids ) )
  File "include\HydrusData.py", line 41, in BuildKeyToSetDict
    for ( key, value ) in pairs: d[ key ].add( value )
  File "include\ClientDB.py", line 6035, in <genexpr>
    statuses_to_pairs = HydrusData.BuildKeyToSetDict( ( ( status, ( self._GetTag( bad_tag_id ), self._GetTag( good_tag_id ) ) ) for ( status, bad_tag_id, good_tag_id ) in statuses_and_pair_ids ) )
  File "include\ClientDB.py", line 5865, in _GetTag
    result = self._c.execute( 'SELECT namespace, subtag FROM tags NATURAL JOIN namespaces NATURAL JOIN subtags WHERE tag_id = ?;', ( tag_id, ) ).fetchone()
DatabaseError: database disk image is malformed
```

**Comment by mserajnik** [comment]
Hey, issues here have been reenabled and will be used for bug reports/feature requests in the future.

We are currently clearing out all the existing issues from 2017 and prior.
If your bug report or feature request is still relevant, please create a new issue (or use one of the other channels; see https://hydrusnetwork.github.io/hydrus/).
