### ISSUE TITLE
Release 402 client crashes on launch

### ISSUE THREAD

**Issue by Alex-Addy** [hydrusnetwork/hydrus#329]
Attempting to launch the version 402 client results a in crash log. It crashes before any window appears.

## Environment

Hydrus version: 402 (applies to both installed and extracted form, downloaded from the release page)
Platform: Windows 10 Pro
OS specifics: Clean windows 10 install, first time launching

## What happens
When running 402 client it fails to launch and places a crash log on the desktop. This does not occur with the 401 release.

## Steps to reproduce

1. Download and extract/install release 402
2. Open hydrus folder and double click the `client.exe`
3. Nothing should appear
4. Check desktop for crash log

## Desired outcome
Client launches.

## Error message / Log file / Screenshots
```
Traceback (most recent call last):
  File "site-packages\qtpy\__init__.py", line 204, in <module>
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 19, in <module>
    from hydrus.client.gui import QtPorting as QP
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "hydrus\client\gui\QtPorting.py", line 22, in <module>
    import qtpy
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\qtpy\__init__.py", line 210, in <module>
qtpy.PythonQtError: No Qt bindings could be found
```

**Comment by thatfuckingbird** [comment]
Known bug, will be fixed in v403.
Until then, you can either:
* downgrade to 401
* run 402 from source

**Comment by imtbl** [comment]
For reference: see #244.

**Comment by Alex-Addy** [comment]
Downgrading is working fine. Thanks for the incredibly quick response! And for the great application that is Hydrus.
