### ISSUE TITLE
Capture ffmpeg standard error output

### ISSUE THREAD

**Issue by imtbl** [hydrusnetwork/hydrus#367]
Currently, Hydrus doesn't display any information about the kind of error when ffmpeg encounters an issue and doesn't return any metadata:
```
STDERR Response: b''
2020/07/09 16:58:46: Error when processing [redacted] !
2020/07/09 16:58:46: Traceback (most recent call last):
  File "hydrus/hydrus/client/importing/ClientImportFileSeeds.py", line 1318, in WorkOnURL
  File "hydrus/hydrus/client/importing/ClientImportFileSeeds.py", line 569, in DownloadAndImportRawFile
  File "hydrus/hydrus/client/importing/ClientImportFileSeeds.py", line 816, in Import
  File "hydrus/hydrus/client/importing/ClientImportFileSeeds.py", line 89, in DoWork
  File "hydrus/hydrus/client/importing/ClientImportFileSeeds.py", line 174, in GenerateInfo
  File "hydrus/hydrus/core/HydrusFileHandling.py", line 207, in GetFileInfo
  File "hydrus/hydrus/core/HydrusAudioHandling.py", line 46, in VideoHasAudio
  File "hydrus/hydrus/core/HydrusVideoHandling.py", line 206, in GetFFMPEGInfoLines
hydrus.core.HydrusExceptions.DataMissing: Cannot interact with video because FFMPEG did not return any content.
```
For debugging purposes, it would be useful if Hydrus could capture ffmpeg's standard error output and log that, especially given that ffmpeg apparently doesn't log errors to a file by default.

**Comment by thatfuckingbird** [comment]
Calling ffmpeg in a way that it generates a separate logfile would be better.

**Comment by DonaldTsang** [comment]
Would this feature include MPV errors? #248
