### ISSUE TITLE
[Linux] Unable to start latest release as of Tue Nov 4

### ISSUE THREAD

**Issue by Cazzar** [hydrusnetwork/hydrus#7]
When looking at updating to the latest release on Arch Linux the client and server does not start due to a PIL error:

    $ ./client 
    Traceback (most recent call last):
      File "<string>", line 26, in <module>
      File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
      File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/PIL.PngImagePlugin", line 40, in <module>
      File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
      File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/PIL.Image", line 53, in <module>

    ImportError: cannot import name _imaging

Noting the new release soon, I will keep an eye out on that update, seeing if it breaks similarly.

**Comment by underr** [comment]
I'm having this problem too (using Arch Linux):

```
$ ./client    
           
Traceback (most recent call last):
  File "<string>", line 26, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/PIL.PngImagePlugin", line 40, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
  File "/home/hydrus/Desktop/hydrus/build/client/out00-PYZ.pyz/PIL.Image", line 53, in <module>
ImportError: cannot import name _imaging
```

**Comment by ScoreUnder** [comment]
@hydrusnetwork 
Why is this packaged in an executable? Not being accusatory here, I want to know if it was for the user's convenience launching it, or if it was required to get some libraries to work or something.
(If it were not packaged in an executable, virtualenv could solve this problem)

**Comment by hydrusnetwork** [comment]
@ScoreUnder I don't know anything about distributing programs for Linux, so I just copied my PyInstaller build process that I was using for Windows for Linux. It produced an exe that seems to run ok in Ubuntu.

I would like to make a better release for Linux, so any advise you can give on what is appropriate would be appreciated, probably in your other issue thread!

**Comment by cazzar** [comment]
Generally source and dep information will do, I also found out running from
source doesn't crash even with newer wx libs. Also an option to store the
data in somewhere else under Linux, like /var/hydrus/

**Comment by ScoreUnder** [comment]
Arch guys, I've set up a package on the AUR - tell me if it works!
`yaourt -S hydrus`

**Comment by underr** [comment]
It works perfectly, thanks!
