### ISSUE TITLE
Network Jobs do not honour HTTP 429

### ISSUE THREAD

**Issue by bbappserver** [hydrusnetwork/hydrus#734]
## Environment

Hydrus version:418
Platform: OSX
OS specifics: 

## What happens

Hydrus treats HTTP error 429 as BandwidthException, and then just retries in a standard interval that is very impolite to the server.  This is counter productive because it basically just keeps asking even though the server has already said no.

## Steps to reproduce

1.Send way to many requests to a server as part of a subscription (I was using instagram)
2.The subscription will continue to fire every minute and a half until it errors out for every item.

## Desired outcome

The network job should inform the bandwidth manager for the domain of one of the following.

### A. Honour 429 `Retry-After:` Header
When a 429 is issued a `Retry-After:<seconds>` header is sent on any reasonable web server.  The network job should tell the bandwidth manager that there is not enough bandwidth to perform the job right now, in the same way that it would if there were not enough bandwidth according to bandwidth rules.  The job should also create a temporary hold on the domain until after the specified time.

### B. Exponential Backoff
If the domain is denying requests for a 429 and does not specify a `Retry-After` or is throttling in general really, you should backoff with a multiplier >1 (I like using 1.25, 2 tends to grow too quickly).  Basically tell the domain bandwidth manager that there is a throttle time(t) multiplied by some constant (k) which is initially 1, every time the connection is rejected multiply by the multiplier.  When connection returns to normal (HTTP 200) reset k to 1 or start dividing k by the multiplier, until it returns to 1.

## Error message / Log file / Screenshots

```
2020/11/20 16:25:38: Traceback (most recent call last):
  File "/Users/redacted/git/hydrus/hydrusqt/hydrus/client/networking/ClientNetworkingJobs.py", line 1240, in Start
    raise e
hydrus.core.HydrusExceptions.BandwidthException: 429: {"message": "", "spam": true, "status": "fail"}{"message": "", "spam": true, "status": "fail"}{"message": "", "spam": true, "status": "fail"}{"message": "", "spam": true, "status": "fail"}{"message": "", "spam": true, "status": "fail"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/redacted/git/hydrus/hydrusqt/hydrus/client/importing/ClientImportFileSeeds.py", line 1161, in WorkOnURL
    network_job.WaitUntilDone()
  File "/Users/redacted/git/hydrus/hydrusqt/hydrus/client/networking/ClientNetworkingJobs.py", line 1484, in WaitUntilDone
    raise self._error_exception
  File "/Users/redacted/git/hydrus/hydrusqt/hydrus/client/networking/ClientNetworkingJobs.py", line 1259, in Start
    raise HydrusExceptions.BandwidthException( 'Server reported very limited bandwidth: ' + str( e ) )
hydrus.core.HydrusExceptions.BandwidthException: Server reported very limited bandwidth: 429: {"message": "", "spam": true, "status": "fail"}{"message": "", "spam": true, "status": "fail"}{"message": "", "spam": true, "status": "fail"}{"message": "", "spam": true, "status": "fail"}{"message": "", "spam": true, "status": "fail"}
```

**Comment by bbappserver** [comment]
https://github.com/hydrusnetwork/hydrus/blob/8b436b5bfe99c8bcac61011c8ff8d5a23fe67cb0/hydrus/client/networking/ClientNetworkingJobs.py#L87

**Comment by bbappserver** [comment]
It appears hydrus currently uses a simple linear falloff which is far from sufficient on a lot of commercial servers (though it might work fine on boorus and large galleries with less than stellar administrators).

https://github.com/hydrusnetwork/hydrus/blob/8b436b5bfe99c8bcac61011c8ff8d5a23fe67cb0/hydrus/client/networking/ClientNetworkingJobs.py#L698

Unfortunately linear falloff just aggravates the server's bot detection more, as you are basically going to ask a few seconds later at a time.

There also doesn't appear to be any acknowledgement of 429 headers at all.

**Comment by bbappserver** [comment]
I have patched it but have not created unit tests.
[NetworkJobsImprovements.diff.txt](https://github.com/hydrusnetwork/hydrus/files/5587527/NetworkJobsImprovements.diff.txt)

**Comment by bbappserver** [comment]
To be fair the only site I've ever actually seen return this code was IG.

**Comment by hydrusnetwork** [comment]
Thanks, sorry I got back to this so late. Should be sorted for tomorrow. I now obey the Retry-After, and I did the backoff_factor too for normal waits.
