### ISSUE TITLE
Errors when importing with "only add tags that already exist" filter

### ISSUE THREAD

**Issue by pozieuto** [hydrusnetwork/hydrus#753]
Just an interesting traceback I got recently. I clicked the green 🔁 refresh button on the filtering tab of a duplicates processing page while the hard disk that the database was stored on was in constant use by another application (reading a large file as fast as possible). Like usual, the button itself greyed out and the text next to it changed from "# potential pairs." to "Updating...", but then I got this traceback and those elements were stuck like that until the client was restarted. The fix (restart the client) and mitigation (try not to use the client while the HDD is under heavy load) are simple and sensible, so I wouldn't say this is high priority.

```Python-traceback
DBException
OperationalError: no such table: mem.temp_int_tag_id_0
Traceback (most recent call last):
  File "hydrus\core\HydrusThreading.py", line 382, in run
    callable( *args, **kwargs )
  File "hydrus\client\gui\ClientGUIManagement.py", line 1218, in thread_do_it
    potential_duplicates_count = HG.client_controller.Read( 'potential_duplicates_count', file_search_context, both_files_match )
  File "hydrus\core\HydrusController.py", line 615, in Read
    return self._Read( action, *args, **kwargs )
  File "hydrus\core\HydrusController.py", line 194, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "hydrus\core\HydrusDB.py", line 1074, in Read
    return job.GetResult()
  File "hydrus\core\HydrusData.py", line 1843, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: OperationalError: no such table: mem.temp_int_tag_id_0
Database Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 675, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "hydrus\client\ClientDB.py", line 14890, in _Read
    elif action == 'potential_duplicates_count': result = self._DuplicatesGetPotentialDuplicatesCount( *args, **kwargs )
  File "hydrus\client\ClientDB.py", line 6196, in _DuplicatesGetPotentialDuplicatesCount
    query_hash_ids = self._GetHashIdsFromQuery( file_search_context, apply_implicit_limit = False )
  File "hydrus\client\ClientDB.py", line 8789, in _GetHashIdsFromQuery
    unwanted_hash_ids = self._GetHashIdsFromTag( ClientTags.TAG_DISPLAY_ACTUAL, file_service_key, tag_search_context, tag, hash_ids = query_hash_ids, hash_ids_table_name = temp_table_name, job_key = job_key )
  File "hydrus\client\ClientDB.py", line 9242, in _GetHashIdsFromTag
    return self._GetHashIdsFromTagIds( tag_display_type, file_service_key, tag_search_context, tag_ids, hash_ids = hash_ids, hash_ids_table_name = hash_ids_table_name, job_key = job_key )
  File "hydrus\client\ClientDB.py", line 9254, in _GetHashIdsFromTagIds
    estimated_count = self._GetAutocompleteCountEstimate( tag_display_type, tag_service_id, file_service_id, tag_ids, tag_search_context.include_current_tags, tag_search_context.include_pending_tags )
  File "hydrus\client\ClientDB.py", line 7068, in _GetAutocompleteCountEstimate
    ( current_count, pending_count ) = self._GetAutocompleteCountEstimateStatuses( tag_display_type, tag_service_id, file_service_id, tag_ids )
  File "hydrus\client\ClientDB.py", line 7088, in _GetAutocompleteCountEstimateStatuses
    ids_to_count = self._GetAutocompleteCounts( tag_display_type, tag_service_id, file_service_id, tag_ids, include_current_tags, include_pending_tags )
  File "hydrus\client\ClientDB.py", line 7111, in _GetAutocompleteCounts
    with HydrusDB.TemporaryIntegerTable( self._c, tag_ids, 'tag_id' ) as temp_tag_id_table_name:
  File "hydrus\core\HydrusDB.py", line 1186, in __enter__
    self._cursor.executemany( 'INSERT INTO {} ( {} ) VALUES ( ? );'.format( self._table_name, self._column_name ), ( ( i, ) for i in self._integer_iterable ) )
sqlite3.OperationalError: no such table: mem.temp_int_tag_id_0


Database Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 675, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "hydrus\client\ClientDB.py", line 14890, in _Read
    elif action == 'potential_duplicates_count': result = self._DuplicatesGetPotentialDuplicatesCount( *args, **kwargs )
  File "hydrus\client\ClientDB.py", line 6196, in _DuplicatesGetPotentialDuplicatesCount
    query_hash_ids = self._GetHashIdsFromQuery( file_search_context, apply_implicit_limit = False )
  File "hydrus\client\ClientDB.py", line 8789, in _GetHashIdsFromQuery
    unwanted_hash_ids = self._GetHashIdsFromTag( ClientTags.TAG_DISPLAY_ACTUAL, file_service_key, tag_search_context, tag, hash_ids = query_hash_ids, hash_ids_table_name = temp_table_name, job_key = job_key )
  File "hydrus\client\ClientDB.py", line 9242, in _GetHashIdsFromTag
    return self._GetHashIdsFromTagIds( tag_display_type, file_service_key, tag_search_context, tag_ids, hash_ids = hash_ids, hash_ids_table_name = hash_ids_table_name, job_key = job_key )
  File "hydrus\client\ClientDB.py", line 9254, in _GetHashIdsFromTagIds
    estimated_count = self._GetAutocompleteCountEstimate( tag_display_type, tag_service_id, file_service_id, tag_ids, tag_search_context.include_current_tags, tag_search_context.include_pending_tags )
  File "hydrus\client\ClientDB.py", line 7068, in _GetAutocompleteCountEstimate
    ( current_count, pending_count ) = self._GetAutocompleteCountEstimateStatuses( tag_display_type, tag_service_id, file_service_id, tag_ids )
  File "hydrus\client\ClientDB.py", line 7088, in _GetAutocompleteCountEstimateStatuses
    ids_to_count = self._GetAutocompleteCounts( tag_display_type, tag_service_id, file_service_id, tag_ids, include_current_tags, include_pending_tags )
  File "hydrus\client\ClientDB.py", line 7111, in _GetAutocompleteCounts
    with HydrusDB.TemporaryIntegerTable( self._c, tag_ids, 'tag_id' ) as temp_tag_id_table_name:
  File "hydrus\core\HydrusDB.py", line 1186, in __enter__
    self._cursor.executemany( 'INSERT INTO {} ( {} ) VALUES ( ? );'.format( self._table_name, self._column_name ), ( ( i, ) for i in self._integer_iterable ) )
sqlite3.OperationalError: no such table: mem.temp_int_tag_id_0
```

Hydrus version: 420
Platform: Windows 10 x64 version 1909

**Comment by pozieuto** [comment]
It turns out I am continuing to receive such errors in other areas of the client. At this point I am not sure what is happening, so this is going to read more like a support ticket now.

I updated from 417 to 420 about two days ago. I just realized that it looked like none of my subscriptions have updated with new files in about as long, based on refreshing some pages in my client. However, if I just look at the raw inbox, files have still been importing from subscriptions, but no tags or URLs are being associated with them. Looking at some file import statuses on some subscriptions shows that all recent entries have similar tracebacks. Here are a few different ones:

```python-traceback
OperationalError: no such table: 
Traceback (most recent call last):
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1350, in WorkOnURL
    did_substantial_work |= self.WriteContentUpdates( tag_import_options )
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1464, in WriteContentUpdates
    for ( service_key, content_updates ) in tag_import_options.GetServiceKeysToContentUpdates( self.status, media_result, set( self._tags ), external_filterable_tags = self._external_filterable_tags, external_additional_service_keys_to_tags = self._external_additional_service_keys_to_tags ).items():
  File "hydrus\client\importing\ClientImportOptions.py", line 1386, in GetServiceKeysToContentUpdates
    service_tags = service_tag_import_options.GetTags( service_key, status, media_result, service_filterable_tags, service_additional_tags )
  File "hydrus\client\importing\ClientImportOptions.py", line 1713, in GetTags
    existing_applicable_tags = HG.client_controller.Read( 'filter_existing_tags', service_key, applicable_tags )
  File "hydrus\core\HydrusController.py", line 615, in Read
    return self._Read( action, *args, **kwargs )
  File "hydrus\core\HydrusController.py", line 194, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "hydrus\core\HydrusDB.py", line 1074, in Read
    return job.GetResult()
  File "hydrus\core\HydrusData.py", line 1843, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: OperationalError: no such table: 
Database Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 675, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "hydrus\client\ClientDB.py", line 14838, in _Read
    elif action == 'filter_existing_tags': result = self._FilterExistingTags( *args, **kwargs )
  File "hydrus\client\ClientDB.py", line 6841, in _FilterExistingTags
    counts = self._CacheCombinedFilesMappingsGetAutocompleteCounts( ClientTags.TAG_DISPLAY_STORAGE, service_id, list( tag_ids_to_tags.keys() ) )
  File "hydrus\client\ClientDB.py", line 1219, in _CacheCombinedFilesMappingsGetAutocompleteCounts
    return self._c.execute( 'SELECT tag_id, current_count, pending_count FROM {} CROSS JOIN {} USING ( tag_id );'.format( temp_tag_id_table_name, combined_ac_cache_table_name ) ).fetchall()
sqlite3.OperationalError: no such table: 
```
```python-traceback
OperationalError: no such table: mem.temp_int_tag_id_1
Traceback (most recent call last):
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1350, in WorkOnURL
    did_substantial_work |= self.WriteContentUpdates( tag_import_options )
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1464, in WriteContentUpdates
    for ( service_key, content_updates ) in tag_import_options.GetServiceKeysToContentUpdates( self.status, media_result, set( self._tags ), external_filterable_tags = self._external_filterable_tags, external_additional_service_keys_to_tags = self._external_additional_service_keys_to_tags ).items():
  File "hydrus\client\importing\ClientImportOptions.py", line 1386, in GetServiceKeysToContentUpdates
    service_tags = service_tag_import_options.GetTags( service_key, status, media_result, service_filterable_tags, service_additional_tags )
  File "hydrus\client\importing\ClientImportOptions.py", line 1713, in GetTags
    existing_applicable_tags = HG.client_controller.Read( 'filter_existing_tags', service_key, applicable_tags )
  File "hydrus\core\HydrusController.py", line 615, in Read
    return self._Read( action, *args, **kwargs )
  File "hydrus\core\HydrusController.py", line 194, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "hydrus\core\HydrusDB.py", line 1074, in Read
    return job.GetResult()
  File "hydrus\core\HydrusData.py", line 1843, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: OperationalError: no such table: mem.temp_int_tag_id_1
Database Traceback (most recent call last):
  File "hydrus\client\ClientDB.py", line 6841, in _FilterExistingTags
    counts = self._CacheCombinedFilesMappingsGetAutocompleteCounts( ClientTags.TAG_DISPLAY_STORAGE, service_id, list( tag_ids_to_tags.keys() ) )
  File "hydrus\client\ClientDB.py", line 1219, in _CacheCombinedFilesMappingsGetAutocompleteCounts
    return self._c.execute( 'SELECT tag_id, current_count, pending_count FROM {} CROSS JOIN {} USING ( tag_id );'.format( temp_tag_id_table_name, combined_ac_cache_table_name ) ).fetchall()
sqlite3.OperationalError: no such table: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 675, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "hydrus\client\ClientDB.py", line 14838, in _Read
    elif action == 'filter_existing_tags': result = self._FilterExistingTags( *args, **kwargs )
  File "hydrus\client\ClientDB.py", line 6841, in _FilterExistingTags
    counts = self._CacheCombinedFilesMappingsGetAutocompleteCounts( ClientTags.TAG_DISPLAY_STORAGE, service_id, list( tag_ids_to_tags.keys() ) )
  File "hydrus\core\HydrusDB.py", line 1193, in __exit__
    self._cursor.execute( 'DELETE FROM {};'.format( self._table_name ) )
sqlite3.OperationalError: no such table: mem.temp_int_tag_id_1
```
```python-traceback
OperationalError: no such table: 6, 12022, 15174, 50053, 50051, 66196, 32273, 66194, 15175, 32989, 49969
Traceback (most recent call last):
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1350, in WorkOnURL
    did_substantial_work |= self.WriteContentUpdates( tag_import_options )
  File "hydrus\client\importing\ClientImportFileSeeds.py", line 1464, in WriteContentUpdates
    for ( service_key, content_updates ) in tag_import_options.GetServiceKeysToContentUpdates( self.status, media_result, set( self._tags ), external_filterable_tags = self._external_filterable_tags, external_additional_service_keys_to_tags = self._external_additional_service_keys_to_tags ).items():
  File "hydrus\client\importing\ClientImportOptions.py", line 1386, in GetServiceKeysToContentUpdates
    service_tags = service_tag_import_options.GetTags( service_key, status, media_result, service_filterable_tags, service_additional_tags )
  File "hydrus\client\importing\ClientImportOptions.py", line 1713, in GetTags
    existing_applicable_tags = HG.client_controller.Read( 'filter_existing_tags', service_key, applicable_tags )
  File "hydrus\core\HydrusController.py", line 615, in Read
    return self._Read( action, *args, **kwargs )
  File "hydrus\core\HydrusController.py", line 194, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "hydrus\core\HydrusDB.py", line 1074, in Read
    return job.GetResult()
  File "hydrus\core\HydrusData.py", line 1843, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: OperationalError: no such table: 6, 12022, 15174, 50053, 50051, 66196, 32273, 66194, 15175, 32989, 49969
Database Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 675, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "hydrus\client\ClientDB.py", line 14838, in _Read
    elif action == 'filter_existing_tags': result = self._FilterExistingTags( *args, **kwargs )
  File "hydrus\client\ClientDB.py", line 6841, in _FilterExistingTags
    counts = self._CacheCombinedFilesMappingsGetAutocompleteCounts( ClientTags.TAG_DISPLAY_STORAGE, service_id, list( tag_ids_to_tags.keys() ) )
  File "hydrus\client\ClientDB.py", line 1219, in _CacheCombinedFilesMappingsGetAutocompleteCounts
    return self._c.execute( 'SELECT tag_id, current_count, pending_count FROM {} CROSS JOIN {} USING ( tag_id );'.format( temp_tag_id_table_name, combined_ac_cache_table_name ) ).fetchall()
sqlite3.OperationalError: no such table: 6, 12022, 15174, 50053, 50051, 66196, 32273, 66194, 15175, 32989, 49969
```

I can still manually import files into the client and tag them just fine.

**Comment by pozieuto** [comment]
This is fixed in [421](https://github.com/hydrusnetwork/hydrus/releases/tag/v421). I assume this is the relevant changelog item:
> * fixed a bug when importing files with the 'only add tags that already exist’ filter active, and added a unit test so this should not fail due to a typo again
