### ISSUE TITLE
Client tag API broken

### ISSUE THREAD

**Issue by ShadowJonathan** [hydrusnetwork/hydrus#788]
## Environment

Hydrus version: 426
Platform: Linux
OS specifics: PopOS 20.4

"About Client" output:
![image](https://user-images.githubusercontent.com/22740616/105509585-f09ffd00-5ccd-11eb-8748-e18ff6628756.png)

## What happens

Client API throws a server error upon adding tags

## Desired outcome

Client API working as intended

## Error message / Log file / Screenshots

(Entire python traceback output)

```
Traceback (most recent call last):
  File "/home/jonathan/dev/hydrus_url_to_tags/.venv/lib/python3.8/site-packages/hydrus/__init__.py", line 183, in _api_request
    response.raise_for_status()
  File "/home/jonathan/dev/hydrus_url_to_tags/.venv/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:45869/add_tags/add_tags

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 154, in <module>
    client.add_tags(
  File "/home/jonathan/dev/hydrus_url_to_tags/.venv/lib/python3.8/site-packages/hydrus/__init__.py", line 301, in add_tags
    self._api_request("POST", self._ADD_TAGS_ROUTE, json=json_)
  File "/home/jonathan/dev/hydrus_url_to_tags/.venv/lib/python3.8/site-packages/hydrus/__init__.py", line 194, in _api_request
    raise ServerError(response)
hydrus.ServerError: The repository encountered an error it could not handle! Here is a dump of what happened, which will also be written to your client.log file. If it persists, please forward it to hydrus.admin@gmail.com:

Traceback (most recent call last):
  File "/home/jonathan/.pyenv/versions/3.7.8/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/jonathan/.pyenv/versions/3.7.8/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hydrus/.venv/lib/python3.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/opt/hydrus/.venv/lib/python3.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/opt/hydrus/.venv/lib/python3.7/site-packages/twisted/python/threadpool.py", line 250, in inContext
    result = inContext.theWork()
  File "/opt/hydrus/.venv/lib/python3.7/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/opt/hydrus/.venv/lib/python3.7/site-packages/twisted/python/context.py", line 122, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/opt/hydrus/.venv/lib/python3.7/site-packages/twisted/python/context.py", line 85, in callWithContext
    return func(*args,**kw)
  File "/opt/hydrus/hydrus/client/ClientLocalServerResources.py", line 1091, in _threadDoPOSTJob
    if isinstance( tags[0], str ):
builtins.TypeError: 'set' object is not subscriptable
```

**Comment by hydrusnetwork** [comment]
Thank you, I am sorry. I will fix this and fill out my client api unit tests so this doesn't happen again.
