### ISSUE TITLE
problem saving json object

### ISSUE THREAD

**Issue by alidan** [hydrusnetwork/hydrus#812]
DBException
InterfaceError: Error binding parameter 4 - probably unsupported type.
Traceback (most recent call last):
  File "hydrus\core\HydrusThreading.py", line 401, in run
    callable( *args, **kwargs )
  File "hydrus\client\gui\ClientGUI.py", line 4560, in do_it
    controller.SaveGUISession( session )
  File "hydrus\client\ClientController.py", line 1570, in SaveGUISession
    self.WriteSynchronous( 'serialisable', session )
  File "hydrus\core\HydrusController.py", line 865, in WriteSynchronous
    return self._Write( action, True, *args, **kwargs )
  File "hydrus\core\HydrusController.py", line 247, in _Write
    result = self.db.Write( action, synchronous, *args, **kwargs )
  File "hydrus\core\HydrusDB.py", line 1088, in Write
    if synchronous: return job.GetResult()
  File "hydrus\core\HydrusData.py", line 1848, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: InterfaceError: Error binding parameter 4 - probably unsupported type.
Database Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 668, in _ProcessJob
    result = self._Write( action, *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 20551, in _Write
    elif action == 'serialisable': self._SetJSONDump( *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 16793, in _SetJSONDump
    self._c.execute( 'INSERT INTO json_dumps_named ( dump_type, dump_name, version, timestamp, dump ) VALUES ( ?, ?, ?, ?, ? );', ( dump_type, dump_name, version, object_timestamp, dump_buffer ) )
sqlite3.InterfaceError: Error binding parameter 4 - probably unsupported type.

Database Traceback (most recent call last):
  File "hydrus\core\HydrusDB.py", line 668, in _ProcessJob
    result = self._Write( action, *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 20551, in _Write
    elif action == 'serialisable': self._SetJSONDump( *args, **kwargs )
  File "hydrus\client\db\ClientDB.py", line 16793, in _SetJSONDump
    self._c.execute( 'INSERT INTO json_dumps_named ( dump_type, dump_name, version, timestamp, dump ) VALUES ( ?, ?, ?, ?, ? );', ( dump_type, dump_name, version, object_timestamp, dump_buffer ) )
sqlite3.InterfaceError: Error binding parameter 4 - probably unsupported type.

-------------

Ok I am doing a rather large gallery download from gelbooru, and I have been getting this every so often, not 100% if its concerning or not.

**Comment by alidan** [comment]
![client_2021-02-16_21-10-08](https://user-images.githubusercontent.com/2681758/108150998-5b5d1200-709b-11eb-9609-ac6da3ebf8ed.png)

**Comment by Zweibach** [comment]
The bug report template is there for a reason, use it.

**Comment by alidan** [comment]
hydrus 428 and win 7 are the only thing I left out 
## What happens
I dont know, this error pops up
## Steps to reproduce
I dont know, im downloading alot from gelbooru 
## Desired outcome
know if this is a concern or just expected
## Error message / Log file / Screenshots
um see above
