### ISSUE TITLE
Client API: Adding files by ID to pages returns Error Code 500 if the ID doesn't exist

### ISSUE THREAD

**Issue by Trivernis** [hydrusnetwork/hydrus#961]
### Hydrus version

450

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

5.13.9-arch1-1
installed from the AUR

### Bug description and reproduction

1. Start a request to `manage_pages/add_files` with the `file_ids` only containing one invalid entry (e.g. `[0]`).
2. Wait for the error

Instead of returning 404 or some other 400 error to indicate that the file id doesn't exist, it throws an exception and returns the traceback.

### Log output

```text
2021/08/14 13:23:21: Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/twisted/_threads/_threadworker.py", line 47, in work
    task()
  File "/usr/lib/python3.9/site-packages/twisted/_threads/_team.py", line 181, in doWork
    task()
--- <exception caught here> ---
  File "/usr/lib/python3.9/site-packages/twisted/python/threadpool.py", line 238, in inContext
    result = inContext.theWork()  # type: ignore[attr-defined]
  File "/usr/lib/python3.9/site-packages/twisted/python/threadpool.py", line 254, in <lambda>
    inContext.theWork = lambda: context.call(  # type: ignore[attr-defined]
  File "/usr/lib/python3.9/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/lib/python3.9/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/opt/hydrus/hydrus/client/networking/ClientLocalServerResources.py", line 2255, in _threadDoPOSTJob
    media_results = HG.client_controller.Read( 'media_results_from_ids', hash_ids )
  File "/opt/hydrus/hydrus/core/HydrusController.py", line 684, in Read
    return self._Read( action, *args, **kwargs )
  File "/opt/hydrus/hydrus/core/HydrusController.py", line 201, in _Read
    result = self.db.Read( action, *args, **kwargs )
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 1009, in Read
    return job.GetResult()
  File "/opt/hydrus/hydrus/core/HydrusData.py", line 1882, in GetResult
    raise e
hydrus.core.HydrusExceptions.DBException: DataMissing: Did not find all entries for those hash ids!
Database Traceback (most recent call last):
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 682, in _ProcessJob
    result = self._Read( action, *args, **kwargs )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 14486, in _Read
    elif action == 'media_results_from_ids': result = self._GetMediaResults( *args, **kwargs )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 10826, in _GetMediaResults
    missing_hash_ids_to_hashes = self.modules_hashes_local_cache.GetHashIdsToHashes( hash_ids = missing_hash_ids )
  File "/opt/hydrus/hydrus/client/db/ClientDBDefinitionsCache.py", line 173, in GetHashIdsToHashes
    self._PopulateHashIdsToHashesCache( hash_ids )
  File "/opt/hydrus/hydrus/client/db/ClientDBDefinitionsCache.py", line 68, in _PopulateHashIdsToHashesCache
    hash_ids_to_hashes = self.modules_hashes.GetHashIdsToHashes( hash_ids = uncached_hash_ids )
  File "/opt/hydrus/hydrus/client/db/ClientDBMaster.py", line 274, in GetHashIdsToHashes
    self._PopulateHashIdsToHashesCache( hash_ids, exception_on_error = True )
  File "/opt/hydrus/hydrus/client/db/ClientDBMaster.py", line 77, in _PopulateHashIdsToHashesCache
    raise HydrusExceptions.DataMissing( 'Did not find all entries for those hash ids!' )
hydrus.core.HydrusExceptions.DataMissing: Did not find all entries for those hash ids!


2021/08/14 13:23:21: 45869 POST /manage_pages/add_files 500 in 2.00 milliseconds
```

**Comment by hydrusnetwork** [comment]
Thank you for this report. This is fixed for 453 for several queries that take file_id(s) as a parameter. It now gives 404.
