### ISSUE TITLE
server.py won't work 

### ISSUE THREAD

**Issue by enoxitus** [hydrusnetwork/hydrus#970]
### Hydrus version

v451

### Operating system

Linux (specify distro and version in comments)

### Install method

Running from source

### Install and OS comments

I'm trying to run v451 from source because the Linux binary wouldn't start for me
I'm on Ubuntu 20.04 focal and use the aarch64 Linux 5.4.0-1041-raspi kernel (yes, this is a Raspberry Pi 4) and use python 3.8

### Bug description and reproduction

I installed the packages using this command: "cat requirements_ubuntu.txt | sed -e '/^\s*#.*$/d' -e '/^\s*$/d' | xargs -n 1 pip install", to avoid the install from failing just because it didn't find the appropriate PySide2 version. I installed PyQT5 as a package instead.

Then, I tried running server.py and received the following errors

### Log output

```text
ubuntu@ubuntu:~/hydrus-451$ python3 server.py
2021/08/25 04:52:01: Initialising controller…
2021/08/25 04:52:01: Initialising db…
2021/08/25 04:52:01: Initialising daemons…
2021/08/25 04:52:01: Starting services…
2021/08/25 04:52:01: Running "server admin" on port 45870.
2021/08/25 04:52:01: Services started
2021/08/25 04:52:01: Server is running. Press Ctrl+C to quit.
Unhandled Error
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/python/log.py", line 85, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 686, in _doReadOrWrite
    why = selectable.doRead()
--- <exception caught here> ---
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 1409, in doRead
    protocol.makeConnection(transport)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 197, in makeConnection
    self._tlsConnection = self.factory._createConnection(self)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 800, in _createConnection
    self._applyProtocolNegotiation(connection)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 779, in _applyProtocolNegotiation
    _setAcceptableProtocols(context, protocols)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/_sslverify.py", line 2013, in _setAcceptableProtocols
    supported = protocolNegotiationMechanisms()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/_sslverify.py", line 234, in protocolNegotiationMechanisms
    ctx.set_alpn_select_callback(lambda c: None)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1396, in set_alpn_select_callback
    self._alpn_select_helper = _ALPNSelectHelper(callback)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/OpenSSL/SSL.py", line 391, in __init__
    self.callback = _ffi.callback(
builtins.SystemError: ffi_prep_closure(): bad user_data (it seems that the version of the libffi library seen at runtime is different from the 'ffi.h' file seen at compile-time)

Unhandled Error
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/base.py", line 1318, in run
    self.mainLoop()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/base.py", line 1331, in mainLoop
    reactorBaseSelf.doIteration(t)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/epollreactor.py", line 244, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/python/log.py", line 85, in callWithContext
    return context.call({ILogContext: newCtx}, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/python/context.py", line 83, in callWithContext
    return func(*args, **kw)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 699, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/posixbase.py", line 300, in _disconnectSelectable
    selectable.readConnectionLost(f)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 308, in readConnectionLost
    self.connectionLost(reason)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/internet/tcp.py", line 325, in connectionLost
    protocol.connectionLost(reason)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/protocols/tls.py", line 388, in connectionLost
    self._tlsConnection.bio_shutdown()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/twisted/protocols/policies.py", line 104, in __getattr__
    return getattr(self.transport, name)
builtins.AttributeError: 'NoneType' object has no attribute '_tlsConnection'
```

**Comment by Suika** [comment]
As the error states there is a problem with openssl. I would not recommend to install the packages via pypi due to the architecture and go for https://hydrusnetwork.github.io/hydrus/help/running_from_source_linux_packages.txt. If the packages that are needed are available via package manager, use them.

**Comment by enoxitus** [comment]
> As the error states there is a problem with openssl. I would not recommend to install the packages via pypi due to the architecture and go for https://hydrusnetwork.github.io/hydrus/help/running_from_source_linux_packages.txt. If the packages that are needed are available via package manager, use them.

Thank you, I did actually use that exact list to figure out what packages to install but I used pip. I'll retry installing as many as I can via aptitude and report back whether it worked or not.

**Comment by enoxitus** [comment]
It worked wonderfully, I just had to install everything via my package manager and uninstall all pip packages. Now it runs just fine! 
Thanks again.
