### ISSUE TITLE
Restoring a fully broken client cache db errors out with "vtable constructor failed"

### ISSUE THREAD

**Issue by Suika** [hydrusnetwork/hydrus#975]
### Hydrus version

454

### Operating system

Linux (specify distro and version in comments)

### Install method

Third party (AUR, Docker, Chocolatey, etc. Specify in comments)

### Install and OS comments

Nothing to comment on

### Bug description and reproduction

1. Delete your cache db
2. Start client and try to re-create the cache
3. Fail

### Log output

```text
2021/09/08 17:36:27: Traceback (most recent call last):
  File "/opt/hydrus/hydrus/client/ClientController.py", line 1986, in THREADBootEverything
    self.InitModel()
  File "/opt/hydrus/hydrus/client/ClientController.py", line 899, in InitModel
    HydrusController.HydrusController.InitModel( self )
  File "/opt/hydrus/hydrus/core/HydrusController.py", line 554, in InitModel
    self.db = self._InitDB()
  File "/opt/hydrus/hydrus/client/ClientController.py", line 215, in _InitDB
    return ClientDB.DB( self, self.db_dir, 'client' )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 459, in __init__
    HydrusDB.HydrusDB.__init__( self, controller, db_dir, db_name )
  File "/opt/hydrus/hydrus/core/HydrusDB.py", line 364, in __init__
    self._RepairDB()
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 14211, in _RepairDB
    self._CacheTagsGenerate( file_service_id, tag_service_id )
  File "/opt/hydrus/hydrus/client/db/ClientDB.py", line 3329, in _CacheTagsGenerate
    self._Execute( 'CREATE VIRTUAL TABLE IF NOT EXISTS {} USING fts4( subtag );'.format( subtags_fts4_table_name ) )
  File "/opt/hydrus/hydrus/core/HydrusDBBase.py", line 160, in _Execute
    return self._c.execute( query, *args )
sqlite3.OperationalError: vtable constructor failed: specific_subtags_fts4_cache_10_3
```

**Comment by hydrusnetwork** [comment]
Hey, as we have discussed elsewhere, I have worked on this and published the early version at a branch here:

https://github.com/hydrusnetwork/hydrus/tree/new-repair-test

This will repair everything in client.caches.db, repopulate almost everything (it'll tell you about the local_tags_cache, which still needs a manual action after boot), and will make regular commits so if this VIRTUAL TABLE query fails again, you won't have to re-do everything.

Let me know how it works for you!
